{
  pkgs,
  lib,
  config,
  inputs,
  ...
}:
# Compass dev shell — the single source of the dev + CI toolchain. nix/devenv
# owns everything: the language/runtime toolchains (bun/node/moon vendored as
# nix derivations from tools/toolchain/versions/*.nix, go from the go-overlay
# input) plus everything non-language — the contract codegen tools, the Go
# analysis battery, and the linters the moon gate runs.
#
# Everything here is a system task's dependency: moon execs what this shell puts
# on PATH rather than managing a toolchain of its own.
let
  # Postgres DSN shared by compass-server and dogfood:mint-runner-token. mint
  # MUST open the same store the server migrated, so both consumers reference one
  # binding — a lone edit to either copy would silently point mint at a different
  # database, surfacing only as a runner enroll failure.
  dogfoodDSN = "host=${config.env.PGHOST} port=${toString config.env.PGPORT} dbname=compass sslmode=disable";

  # The go pin (tools/toolchain/versions/go.nix), version-selected from the
  # go-overlay input. go-overlay's flake exposes each version as a package attr
  # named `go_<major>_<minor>_<patch>` (dots→underscores; nix attr names hold no
  # unquoted dots), built over the devenv.lock-pinned nixpkgs via the
  # devenv.yaml `inputs.nixpkgs.follows: nixpkgs`. The parity gate selects the
  # same version through go-overlay's overlay route, so both resolve one
  # derivation.
  goPin = import ./tools/toolchain/versions/go.nix;
  goToolchain = inputs.go-overlay.packages.${pkgs.stdenv.system}."go_${lib.replaceStrings [ "." ] [ "_" ] goPin.version}";

  # bun/node/moon vendored as nix derivations from tools/toolchain/versions/*.nix.
  # The dev shell and the parity gate (tools/toolchain/gate-tools.nix) import this
  # one module, so the two sides cannot drift.
  toolchainTools = import ./tools/toolchain/toolchain-tools.nix { inherit pkgs; };
in
{
  packages = (with pkgs; [
    # compass.v1 contract codegen. buf drives the pipeline; protobuf supplies
    # protoc; protoc-gen-go (messages) + protoc-gen-connect-go (Connect
    # handlers/clients) are the Go lane's plugins, and protoc-gen-es is the TS
    # lane's. All from nixpkgs (pinned), NOT `go install` or a bun devDep, so
    # each resolves to an immutable store path: the plugin version stamped into
    # the generated headers is reproducible and the drift gate stays
    # deterministic.
    #
    # Immutability is the point, not tidiness. buf lazily requires a plugin's
    # closure while executing it, and a store path cannot be rewritten
    # mid-execution. A package store can — a concurrent install tears the read
    # and the gate flakes with a fault that reads like a codegen error.
    #
    # The trade: these versions are the pinned nixpkgs's to choose
    # (devenv.lock), not a lockfile's. A nixpkgs bump that moves a plugin
    # restamps the `@generated by` header, so drift reds with a comment-only
    # diff on a PR touching neither the schema nor the gen trees. That is real
    # drift: run `moon run compass-proto:gen` and commit the restamp with the
    # bump.
    buf
    protobuf # protoc
    protoc-gen-go
    protoc-gen-connect-go
    protoc-gen-es

    # Go gate battery (go/moon.yml): golangci-lint (lint gate incl. the
    # gochecksumtype/exhaustive exhaustiveness check), govulncheck (vuln scan),
    # go-licenses (license fence), nilaway (advisory nil-flow analysis). Go
    # itself is the go-overlay toolchain appended below, alongside the vendored
    # bun/node/moon derivations.
    golangci-lint
    govulncheck
    go-licenses
    nilaway

    # Lint gate. biome + markdownlint-cli2 are nixpkgs derivations here, not
    # `bunx` — one nixpkgs pin means `moon run root:lint` / `root:markdownlint`
    # resolve the identical binary and version for everyone, with no drift
    # between a contributor's node_modules and anyone else's. `@biomejs/biome`
    # stays a package.json devDep for the editor LSP.
    biome
    markdownlint-cli2

    # curl: the compass-server readiness probe (processes below) POSTs to
    # GetServerInfo over the loopback dev-http door to gate readiness on a real
    # serving handler. Pin it here (referenced via `lib.getExe` in the probe)
    # rather than inheriting an ambient system curl, so the one-command bring-up
    # works on any dev box — a non-NixOS nix/devenv host, or a NixOS box without
    # curl in current-system — not only one whose current-system ships curl.
    curl

    # pkg-config: the Wails v3 cgo link needs it to discover the GTK3/WebKitGTK
    # `.pc` files (via PKG_CONFIG_PATH, set over the frozen SEA-1172 closure in
    # `env` below, which owns that rationale). Kept in this parsed list, not the
    # Linux-guarded env block, because it has a bin the toolchain-parity gate
    # resolves and is cross-platform — harmless on macOS, where the app links
    # the system WebKit framework and pkg-config goes unused.
    pkg-config

    # postgresql: the dogfood e2e harness's private postgres
    # (go/cmd/compass-postgres/main.go) shells out to `initdb`/`postgres`/`createdb`
    # via exec.LookPath, so those binaries must be on PATH wherever the e2e suite
    # runs. In the dev shell they arrive free from `services.postgres` (a devenv
    # service), but CI's gate-tools (tools/toolchain/gate-tools.nix, fed by
    # `parity.ts --print-nix-attrs` off THIS list) builds its PATH env ONLY from
    # `packages` — service-provided binaries never reach a CI runner. So the
    # harness prereq has to live here for the CI e2e gate to find `initdb`.
    #
    # Bare `postgresql`, not a version-suffixed attr, for strict parity:
    # `services.postgres.package` defaults to bare `pkgs.postgresql`
    # (forks/devenv/src/modules/services/postgres.nix), which at this devenv.lock
    # pin resolves to postgresql-18.4 — the SAME derivation the service uses, so
    # CI and the dev shell exercise one postgres, not two.
    postgresql
  ])
  # The language toolchains: bun/node/moon vendored from
  # tools/toolchain/versions/*.nix and go from the go-overlay input. Appended
  # OUTSIDE the `with pkgs; [ … ]` literal above because each is a dotted
  # reference, not a bare nixpkgs attribute — and the toolchain-parity gate
  # parses that literal and THROWS on any non-bare token. The gate covers these
  # through its store-path `langs` verdict instead; it never parses this list.
  ++ [
    toolchainTools.bun
    toolchainTools.node
    toolchainTools.moon
    goToolchain
  ];

  env = { }
  # The Compass native app (Wails v3, go/cmd/compass-app) links the Linux
  # GTK3/WebKitGTK stack through cgo. pkg-config (in `packages` above) finds each
  # library's `.pc` file along PKG_CONFIG_PATH, built here over the transitive
  # propagated-dependency closure of the GTK/WebKitGTK set so a `.pc`
  # `Requires:` walk (gdk-3.0 → zlib, pango → freetype2/fontconfig, …) resolves.
  # Both `.pc` install subdirs are searched: a dev output splits its `.pc` files
  # across `lib/pkgconfig` and `share/pkgconfig` (zlib ships `zlib.pc` under
  # `share/`, which gdk-3.0 requires), so searching only `lib/` fails the walk.
  # The package set and subdir order are the frozen SEA-1172 shape
  # (sealed docs/designs/platform/ci-toolchain-shared-defs.md): the sealed CI
  # step image stages the same closure's `-dev` outputs, kept in step by hand.
  #
  # Linux-only, and set in `env` rather than `packages`: on macOS the app links
  # the system WebKit framework, so the closure is Linux's alone; and keeping it
  # out of the parsed `packages` list means the heavy WebKitGTK closure is never
  # realized by the toolchain-parity gate on a CI runner — it is a dev-box build
  # input, and compass CI does not compile the native app.
  // lib.optionalAttrs pkgs.stdenv.isLinux {
    PKG_CONFIG_PATH =
      let
        pcClosure = lib.closePropagation (
          with pkgs;
          [
            dbus
            openssl
            glib
            gtk3
            webkitgtk_4_1
            libsoup_3
            cairo
            pango
            gdk-pixbuf
            atk
            harfbuzz
            librsvg
            gobject-introspection
          ]
        );
      in
      lib.concatStringsSep ":" [
        (lib.makeSearchPathOutput "dev" "lib/pkgconfig" pcClosure)
        (lib.makeSearchPathOutput "dev" "share/pkgconfig" pcClosure)
      ];
  };

  enterShell = ''
    # Bootstrap the workspace on shell entry so a fresh clone is ready right
    # after `direnv allow` — no separate install step. --frozen-lockfile is a
    # fast no-op once node_modules is current.
    bun install --frozen-lockfile
    # Pre-push git hook (a thin shell over `moon ci`). hk install is idempotent,
    # so re-run it on every entry — a guard on the hook file being absent would
    # never pick up `hk.pkl` changes in an already-cloned checkout.
    if command -v hk >/dev/null 2>&1; then
      hk install >/dev/null 2>&1 || echo "devenv: hk install failed; run 'hk install' to enable the pre-push gate"
    fi
  '';

  # One-command Compass dogfood enroll-loop: `devenv up` stands up the full
  # backend a human can drive an agent session against. The chain:
  #
  #   postgres            — the store of record; compass-server opens it at
  #                         startup and applies its embedded migrations under an
  #                         advisory lock (go/internal/store/store.go).
  #   dogfood:gen-cert    — mints the self-signed TLS trust anchor (tls.crt /
  #                         tls.key) the network door serves and the runner
  #                         trusts. Skip-if-present, so a restart never swaps the
  #                         cert out from under a live server/runner pair.
  #   compass-server      — serves compass.v1 on a Unix socket (the local door),
  #                         a loopback gRPC-Web port for the browser UI dev
  #                         server, AND an authenticated TLS network door
  #                         (RunnerService lives only here — runners are remote
  #                         and dial the TLS door, never the loopback socket).
  #                         On network-door startup it mints the bootstrap
  #                         admin-token 0600 under the state dir.
  #   compass-ui          — the browser UI dev server (vite); serves the SolidJS
  #                         board on http://127.0.0.1:5173 and dials the
  #                         server's loopback gRPC-Web dev door directly via
  #                         VITE_COMPASS_BASE_URL. Runs after the server is ready
  #                         so the first browser load never races the migrating
  #                         store.
  #   dogfood:mint-runner-token — registers the `dogfood` runner and writes its
  #                         enrollment token; runs after the server is ready
  #                         (the readiness probe gates on the migrated store).
  #   compass-runner      — enrolls over the TLS door with that token, then
  #                         idles in RunSessions awaiting Provision/Start.
  #
  # Opt-in (NOT wired into up): `dogfood:agent-image` builds+loads the agent
  # base image (heavy closure — kept off the hot up path), and `dogfood:clean`
  # tears down the deterministic-named agent containers so a second session
  # drive does not hit a podman create name collision.
  #
  # Prereqs: a Linux dev box with rootless podman and the uid-1000 subuid/subgid
  # ranges configured (the runner guards on uid 1000 and creates per-container
  # sockets under its runtime dir). Cert expiry: gen-cert is skip-if-present
  # forever against a finite --validity, so once the cert expires the loop fails
  # with an opaque TLS error — rerun `compass-gen-cert --force` (or delete
  # tls.crt/tls.key from the state dir) to rotate.
  #
  # Linux-only: the Postgres service, the backend build stack, and the whole
  # podman-backed runner loop target the Linux dev box.
  services.postgres = lib.optionalAttrs pkgs.stdenv.isLinux {
    enable = true;
    # The single dogfood database compass-server opens. Owned by $USER over the
    # local Unix socket (peer auth) — no password on the loopback dev path.
    initialDatabases = [ { name = "compass"; } ];
  };

  processes = lib.optionalAttrs pkgs.stdenv.isLinux {
    # compass-server: serves compass.v1 on a Unix domain socket (the shipped
    # local door) plus a loopback gRPC-Web port for the browser UI dev server.
    # It builds the binary once, then `exec`s it. process-compose does not run
    # this script directly: it runs `exec devenv-tasks run … compass-server`, so
    # the tree is process-compose → devenv-tasks → compass-server. `exec` here
    # still matters: it collapses the bash-wrapper → binary hop so no `go
    # run`/shell parent is left to orphan (exit status propagates, and the
    # compiled binary sits directly in the process group devenv-tasks signals).
    # On stop, devenv-tasks traps SIGTERM and killpg()s that group (SIGTERM,
    # then SIGKILL after a 5s grace); the SIGTERM reaches compass-server, which
    # traps it in cmd/compass-server and drains both doors. Note the 5s killpg
    # grace equals compass-server's own 5s drain deadline (server/serve.go), so
    # a drain that runs its full budget races the SIGKILL at the boundary. The
    # build is incremental/cached, so the per-restart cost is negligible.
    # Restarts on failure (devenv caps this at 5 by default) so a transient
    # store hiccup recovers.
    compass-server = {
      exec = ''
        # Build once into the state dir, then exec the binary so no shell/`go
        # run` parent lingers between devenv-tasks and compass-server — the
        # binary lands directly in the process group devenv-tasks signals on
        # stop (see the process comment above for the full signal path).
        bin="${config.devenv.state}/compass/compass-server"
        go build -o "$bin" ./cmd/compass-server
        exec "$bin" \
          --socket "$COMPASS_SOCKET" \
          --dev-http "127.0.0.1:${toString config.processes.compass-server.ports.devhttp.value}" \
          --database "$COMPASS_DATABASE_DSN" \
          --listen "127.0.0.1:${toString config.processes.compass-server.ports.network.value}" \
          --tls-cert "${config.devenv.state}/compass/tls.crt" \
          --tls-key "${config.devenv.state}/compass/tls.key"
      '';
      cwd = "${config.devenv.root}/go";
      ports.devhttp.allocate = 50051;
      # The authenticated TLS network door. RunnerService lives only on this
      # door, so the runner (and any remote client) dials it over TLS with the
      # gen-cert trust anchor; the loopback socket/dev-http doors stay for the
      # co-located UI/shell.
      ports.network.allocate = 50052;
      env = {
        # Unix socket under the devenv state dir so the path is stable across
        # restarts and a co-located client (the UI/shell) resolves the same one.
        COMPASS_SOCKET = "${config.devenv.state}/compass/server.sock";
        # pgx keyword/value DSN over the Postgres Unix socket ($PGHOST is the
        # socket dir, $PGPORT the allocated port — set by services.postgres).
        # No user= : pgx defaults to the OS user, which is the peer-auth identity
        # ($USER) that owns the `compass` database (services.postgres above).
        COMPASS_DATABASE_DSN = dogfoodDSN;
      };
      # Wait for Postgres to be accepting connections before starting, so the
      # store opens on the first try rather than crash-restarting until it's up.
      # (dogfood:gen-cert orders itself `before` this process so the TLS cert/key
      # the network door opens over exist by the time the server starts.)
      after = [ "devenv:processes:postgres" ];
      # Ready only once the server actually answers — not merely once the socket
      # file exists. compass-server binds (and chmods) the socket BEFORE it runs
      # the store migrations and starts accepting, so `test -S` would flip ready
      # true while a dial still blocks on the first RPC. Probe GetServerInfo over
      # the loopback dev door instead: it succeeds only after the store is
      # migrated and the handler serves, which is the real signal an `after`-
      # dependent needs.
      ready.exec = ''
        ${lib.getExe pkgs.curl} -fsS --max-time 2 \
          -H 'Content-Type: application/json' \
          -X POST \
          "http://127.0.0.1:${toString config.processes.compass-server.ports.devhttp.value}/compass.v1.CompassService/GetServerInfo" \
          -d '{}' >/dev/null
      '';
      restart.on = "on_failure";
    };

    # compass-ui: the browser UI dev server (vite). Serves the SolidJS board on
    # http://127.0.0.1:5173 and dials compass-server's loopback gRPC-Web dev
    # door directly — no vite proxy: the browser reads the door URL from
    # VITE_COMPASS_BASE_URL at boot (apps/ui/src/live/connection.ts) and the dev
    # door serves wildcard CORS (any origin — it is a loopback dev-only door),
    # which covers this browser consumer (go/server/serve.go devCORS,
    # AllowedOrigins ["*"]). `exec bunx vite` matches the moon dev task
    # (apps/ui/moon.yml) — one convention, two entry points. `after`s the
    # server's readiness probe (a real GetServerInfo answer over the dev door,
    # not merely a bound socket) so the first browser load never races the
    # migrating store.
    compass-ui = {
      exec = ''
        exec bunx vite
      '';
      cwd = "${config.devenv.root}/apps/ui";
      env = {
        # Direct-dial (decided): the browser dials the dev door directly, so the
        # base URL is the server's loopback dev-http port (devenv stays the
        # single owner of that port number).
        VITE_COMPASS_BASE_URL =
          "http://127.0.0.1:${toString config.processes.compass-server.ports.devhttp.value}";
      };
      after = [ "devenv:processes:compass-server" ];
    };

    # compass-runner: enrolls with the server over the TLS network door, then
    # idles awaiting Provision/Start commands. Built into the state dir and
    # exec'd the same way as compass-server (see that process's comment for the
    # build/exec rationale and the devenv-tasks signal path). Runners are
    # remote by design, so this dials the authenticated TLS door
    # (https://127.0.0.1:<network-port>) with the gen-cert cert as the single
    # trust anchor (--ca) — never the loopback socket. The enrollment token is
    # passed via COMPASS_RUNNER_TOKEN env ONLY, never a flag (a flag would leak
    # it into the process table); the exec script reads it from the token file
    # dogfood:mint-runner-token produced. --runtime-dir overrides the root-only
    # /run/compass default with $XDG_RUNTIME_DIR/compass-runner: the runner mints
    # per-container sockets at <runtime-dir>/containers/compass-agent-<32-hex>/
    # agent.sock (a fixed 69-byte suffix) and validates at startup that the widest
    # such path fits the 107-byte AF_UNIX sun_path limit (run.go
    # validateRuntimeDir), capping the dir at 38 bytes — the deep $DEVENV_STATE
    # checkout overflows it, a short per-user /run path (this uid owns it) does
    # not. --egress-allow is omitted:
    # the base loop's local_path clone needs no network, so the agent runs pure
    # default-deny. `ready` is intentionally unset — the runner exposes no HTTP
    # surface and devenv has no log-line readiness type, so it idles unprobed;
    # nothing `after`s it, so that is safe. Restarts on failure because
    # Dial/Enroll is single-shot with no retry, so a transient enroll failure
    # would otherwise leave a permanently dead runner.
    compass-runner = {
      exec = ''
        : "''${XDG_RUNTIME_DIR:?XDG_RUNTIME_DIR must be set; the compass-runner per-container sockets live under it}"
        bin="${config.devenv.state}/compass/compass-runner"
        go build -o "$bin" ./cmd/compass-runner
        export COMPASS_RUNNER_TOKEN="$(cat "${config.devenv.state}/compass/runner.token")"
        exec "$bin" \
          --runner-id dogfood \
          --server "https://127.0.0.1:${toString config.processes.compass-server.ports.network.value}" \
          --ca "${config.devenv.state}/compass/tls.crt" \
          --image compass-agent:latest \
          --runtime-dir "$XDG_RUNTIME_DIR/compass-runner"
      '';
      cwd = "${config.devenv.root}/go";
      # Enroll only once the token exists (mint runs after the server is ready,
      # which is after the store is migrated — so the whole chain is ordered).
      after = [ "dogfood:mint-runner-token" ];
      restart.on = "on_failure";
    };
  };

  # Dogfood loop tasks. All Linux-only (the whole podman-backed loop targets the
  # Linux dev box), so they sit under the same guard as the processes above.
  tasks = lib.optionalAttrs pkgs.stdenv.isLinux {
    # gen-cert: mint the self-signed TLS trust anchor the network door serves and
    # the runner trusts. Built into the state dir and run the same way the server
    # binary is (PATH/build preamble mirrors compass-server). SAN defaults
    # (127.0.0.1,::1,localhost) suffice for the loopback loop, and the binary is
    # skip-if-present, so a restart never swaps the cert out from under a live
    # server/runner pair (cert 0644 public anchor, key 0600). Ordered `before`
    # the compass-server process so the cert/key exist when the network door
    # opens over them.
    "dogfood:gen-cert" = {
      exec = ''
        bin="${config.devenv.state}/compass/compass-gen-cert"
        go build -o "$bin" ./cmd/compass-gen-cert
        exec "$bin" \
          --cert-out "${config.devenv.state}/compass/tls.crt" \
          --key-out "${config.devenv.state}/compass/tls.key"
      '';
      cwd = "${config.devenv.root}/go";
      before = [ "devenv:processes:compass-server" ];
    };

    # mint-runner-token: register the `dogfood` runner and write its enrollment
    # token 0600 (raw, no newline) to the state dir. Reads COMPASS_DATABASE_DSN
    # (the same DSN the server uses) so its store precedence matches. Runs after
    # the server is ready — the readiness probe gates on the migrated store,
    # which mint's store.Open requires. Idempotent: re-registers the same token
    # without rotating when the file exists.
    "dogfood:mint-runner-token" = {
      exec = ''
        bin="${config.devenv.state}/compass/compass-mint-runner-token"
        go build -o "$bin" ./cmd/compass-mint-runner-token
        exec "$bin" \
          --runner-id dogfood \
          --token-out "${config.devenv.state}/compass/runner.token"
      '';
      cwd = "${config.devenv.root}/go";
      env = {
        COMPASS_DATABASE_DSN = dogfoodDSN;
      };
      after = [ "devenv:processes:compass-server" ];
    };

    # agent-image: build AND load the agent base image into
    # containers-storage:compass-agent:latest (the ref the runner resolves with
    # no pull). `container copy` builds then copies; the invocation is pinned to
    # the vendored fork's own CLI (`nix run path:../forks/devenv#devenv`, run
    # from agent-image/ where the fork sits one level up) so it cannot diverge
    # from the fork source the agent-image module set is pinned to. Opt-in (per
    # D5): NOT wired `after` into up — the image closure is large and rebuilding
    # it on every `up` would violate the never-heavy-on-up constraint. The runner
    # starts fine without the image; it only resolves it at Provision time.
    "dogfood:agent-image" = {
      exec = ''
        set -euo pipefail
        # Drop any stale localhost/ tag BEFORE the copy. `container copy` writes
        # the fresh image to docker.io/library/compass-agent:latest, but podman
        # resolves the BARE ref `compass-agent:latest` (what the runner and the
        # e2e fixture use) against localhost/ FIRST — so a leftover
        # localhost/compass-agent:latest from an older build would SHADOW this
        # fresh copy and the runner would silently launch stale agent code.
        # Removing it first makes the bare ref resolve to the image we just built.
        # `podman rmi` exits non-zero when the tag is absent, so tolerate that.
        podman rmi -f localhost/compass-agent:latest 2>/dev/null || true
        nix run path:../forks/devenv#devenv -- container copy agent
      '';
      cwd = "${config.devenv.root}/agent-image";
    };

    # clean: tear down the deterministic-named agent containers and sweep the
    # runner's per-container socket dirs. Opt-in (not wired into up/down):
    # container names are NamePrefix + agent account id (deterministic) and the
    # runner's create-dedup is in-memory, so a second session drive after a
    # restart would hit a `podman create` name collision without this cleanup.
    "dogfood:clean" = {
      exec = ''
        set -euo pipefail
        # Uses the host's rootless podman — the same binary/storage the runner
        # execs to create these containers, so it sees them (a nix-pinned podman
        # could resolve a different containers-storage config).
        ids="$(podman ps -a --filter name=compass-agent- --format '{{.ID}}')"
        if [ -n "$ids" ]; then
          # shellcheck disable=SC2086
          podman rm -f $ids
        fi
        rm -rf "$XDG_RUNTIME_DIR/compass-runner/containers/"
        # Drop the stale localhost/ tag of the agent image. `container copy`
        # writes the fresh image to docker.io/library/compass-agent:latest, but
        # podman resolves the BARE ref `compass-agent:latest` (what the runner and
        # the e2e fixture use) against localhost/ FIRST — so a leftover
        # localhost/compass-agent:latest from an older build SHADOWS every fresh
        # copy, and the runner silently launches stale agent code. `podman rmi`
        # exits non-zero when the tag is absent, so tolerate that: the goal is a
        # clean slate, not a guaranteed prior existence.
        podman rmi -f localhost/compass-agent:latest 2>/dev/null || true
      '';
    };
  };
}
