{
  pkgs,
  lib,
  config,
  inputs,
  ...
}:
# Compass dev shell — the single source of the dev + CI toolchain. nix/devenv
# owns everything: the language/runtime toolchains (bun/node/moon vendored as
# nix derivations from tools/toolchain/versions/*.nix, go from the go-overlay
# input) plus everything non-language — the contract codegen tools, the Go
# analysis battery, and the linters the moon gate runs.
#
# Everything here is a system task's dependency: moon execs what this shell puts
# on PATH rather than managing a toolchain of its own.
let
  # Postgres DSN shared by compass-server and dogfood:mint-runner-token. mint
  # MUST open the same store the server migrated, so both consumers reference one
  # binding — a lone edit to either copy would silently point mint at a different
  # database, surfacing only as a runner enroll failure.
  dogfoodDSN = "host=${config.env.PGHOST} port=${toString config.env.PGPORT} dbname=compass sslmode=disable";

  # Runner id (enrollment subject) shared by dogfood:mint-runner-token and the
  # compass-runner process. The runner's Enroll cross-checks the token subject
  # against its --runner-id, so mint and runner MUST agree or enroll is rejected
  # `unauthenticated` — both consumers reference one binding rather than a pair
  # of copies that could silently drift. An overlay that overrides the runner id
  # sets it here once and both consumers move in lockstep.
  dogfoodRunnerID = "dogfood";

  # The go pin (tools/toolchain/versions/go.nix), version-selected from the
  # go-overlay input. go-overlay's flake exposes each version as a package attr
  # named `go_<major>_<minor>_<patch>` (dots→underscores; nix attr names hold no
  # unquoted dots), built over the devenv.lock-pinned nixpkgs via the
  # devenv.yaml `inputs.nixpkgs.follows: nixpkgs`. The parity gate selects the
  # same version through go-overlay's overlay route, so both resolve one
  # derivation.
  goPin = import ./tools/toolchain/versions/go.nix;
  goToolchain = inputs.go-overlay.packages.${pkgs.stdenv.system}."go_${lib.replaceStrings [ "." ] [ "_" ] goPin.version}";

  # bun/node/moon vendored as nix derivations from tools/toolchain/versions/*.nix.
  # The dev shell and the parity gate (tools/toolchain/gate-tools.nix) import this
  # one module, so the two sides cannot drift.
  toolchainTools = import ./tools/toolchain/toolchain-tools.nix { inherit pkgs; };

  # The Go analysis battery (golangci-lint, govulncheck, go-licenses, nilaway),
  # each rebuilt with the go-overlay toolchain via tools/toolchain/go-analysis.nix
  # rather than taken as the bare nixpkgs attrs: those are built with nixpkgs' go
  # (go1.26 at this pin) and fail every run under this shell's go1.27 with
  # `file requires newer Go version go1.27`. Passed the same goToolchain the gate
  # builds, so both resolve one derivation per tool. Appended below (like
  # goToolchain) rather than listed in the parsed `with pkgs` literal, because
  # each is a dotted reference, not a bare nixpkgs attribute.
  goAnalysis = import ./tools/toolchain/go-analysis.nix { inherit pkgs goToolchain; };
in
{
  packages = (with pkgs; [
    # compass.v1 contract codegen. buf drives the pipeline; protobuf supplies
    # protoc; protoc-gen-go (messages) + protoc-gen-connect-go (Connect
    # handlers/clients) are the Go lane's plugins, and protoc-gen-es is the TS
    # lane's. All from nixpkgs (pinned), NOT `go install` or a bun devDep, so
    # each resolves to an immutable store path: the plugin version stamped into
    # the generated headers is reproducible and the drift gate stays
    # deterministic.
    #
    # Immutability is the point, not tidiness. buf lazily requires a plugin's
    # closure while executing it, and a store path cannot be rewritten
    # mid-execution. A package store can — a concurrent install tears the read
    # and the gate flakes with a fault that reads like a codegen error.
    #
    # The trade: these versions are the pinned nixpkgs's to choose
    # (devenv.lock), not a lockfile's. A nixpkgs bump that moves a plugin
    # restamps the `@generated by` header, so drift reds with a comment-only
    # diff on a PR touching neither the schema nor the gen trees. That is real
    # drift: run `moon run compass-proto:gen` and commit the restamp with the
    # bump.
    buf
    protobuf # protoc
    protoc-gen-go
    protoc-gen-connect-go
    protoc-gen-es

    # Go gate battery (go/moon.yml): golangci-lint (lint), govulncheck (vuln
    # scan), go-licenses (license fence), nilaway (nil-flow analysis) are NOT
    # here — all four are rebuilt with the go-overlay toolchain
    # (tools/toolchain/go-analysis.nix) and appended below with the language
    # toolchains, because the bare nixpkgs attrs are go1.26-built and cannot
    # parse the go1.27 stdlib. Go itself is the go-overlay toolchain appended
    # below, alongside the vendored bun/node/moon derivations.

    # sqlc: generates typed Go from the .sql query files in
    # go/internal/store/queries, compiled against the migrations schema
    # (go/moon.yml sqlc-gen/sqlc-drift). Bare nixpkgs attr so it lives in this
    # parsed literal where the toolchain-parity gate resolves it; the pin ships
    # sqlc 1.31.1.
    sqlc

    # Lint gate. biome + markdownlint-cli2 are nixpkgs derivations here, not
    # `bunx` — one nixpkgs pin means `moon run root:lint` / `root:markdownlint`
    # resolve the identical binary and version for everyone, with no drift
    # between a contributor's node_modules and anyone else's. `@biomejs/biome`
    # stays a package.json devDep for the editor LSP.
    biome
    markdownlint-cli2

    # actionlint: static checker for the GitHub Actions workflows under
    # .github/workflows/ (ci, eng-docs-deploy, publish-agent-image, renovate).
    # A bare nixpkgs attr, so it lives in this parsed literal where the
    # toolchain-parity gate resolves it. Moved off the box into this shell so
    # workflow linting resolves the same pinned binary everywhere.
    actionlint

    # SQL migration lint battery (tools/sql-migration-gate/moon.yml): squawk
    # (migration-safety analysis — full-table rewrites, unsafe DDL, missing
    # CONCURRENTLY) + sqruff (SQL style/lint). Bare nixpkgs attrs so they live
    # in this parsed literal where the toolchain-parity gate resolves them, one
    # pin giving CI and every dev box the identical binary + version.
    squawk
    sqruff

    # curl: the compass-server readiness probe (processes below) POSTs to
    # GetServerInfo over the loopback dev-http door to gate readiness on a real
    # serving handler. Pin it here (referenced via `lib.getExe` in the probe)
    # rather than inheriting an ambient system curl, so the one-command bring-up
    # works on any dev box — a non-NixOS nix/devenv host, or a NixOS box without
    # curl in current-system — not only one whose current-system ships curl.
    curl

    # pkg-config: the Wails v3 cgo link needs it to discover the GTK4/WebKitGTK
    # `.pc` files (via PKG_CONFIG_PATH, set over the GTK closure in
    # `env` below, which owns that rationale). Kept in this parsed list, not the
    # Linux-guarded env block, because it has a bin the toolchain-parity gate
    # resolves and is cross-platform — harmless on macOS, where the app links
    # the system WebKit framework and pkg-config goes unused.
    pkg-config

    # postgresql: the dogfood e2e harness's private postgres
    # (go/cmd/compass-postgres/main.go) shells out to `initdb`/`postgres`/`createdb`
    # via exec.LookPath, so those binaries must be on PATH wherever the e2e suite
    # runs. In the dev shell they arrive free from `services.postgres` (a devenv
    # service), but CI's gate-tools (tools/toolchain/gate-tools.nix, fed by
    # `parity.ts --print-nix-attrs` off THIS list) builds its PATH env ONLY from
    # `packages` — service-provided binaries never reach a CI runner. So the
    # harness prereq has to live here for the CI e2e gate to find `initdb`.
    #
    # Bare `postgresql`, not a version-suffixed attr, for strict parity:
    # `services.postgres.package` defaults to bare `pkgs.postgresql`
    # (the RigelBuild/devenv fork's src/modules/services/postgres.nix), which at this devenv.lock
    # pin resolves to postgresql-18.4 — the SAME derivation the service uses, so
    # CI and the dev shell exercise one postgres, not two.
    postgresql
  ])
  # The language toolchains: bun/node/moon vendored from
  # tools/toolchain/versions/*.nix and go from the go-overlay input, plus the Go
  # analysis battery (golangci-lint/govulncheck/go-licenses/nilaway) rebuilt with
  # that go toolchain (tools/toolchain/go-analysis.nix). Appended OUTSIDE the
  # `with pkgs; [ … ]` literal above because each is a dotted reference, not a
  # bare nixpkgs attribute — and the toolchain-parity gate parses that literal
  # and THROWS on any non-bare token. The gate covers these through its
  # store-path `langs` verdict instead; it never parses this list.
  ++ [
    toolchainTools.bun
    toolchainTools.node
    toolchainTools.moon
    goToolchain
    goAnalysis.golangci-lint
    goAnalysis.govulncheck
    goAnalysis.go-licenses
    goAnalysis.nilaway
  ]
  # hk (jdx/hk): the jj/git pre-push hook runner. A dotted input reference
  # (inputs.hk.packages.<system>.default), not a bare nixpkgs attr, so it is
  # appended OUTSIDE the parsed `with pkgs` literal — the toolchain-parity gate
  # THROWS on any non-bare token in that literal (same reason as goToolchain
  # above). Cross-platform (linux + darwin), so it needs no isLinux guard.
  # `enterShell` runs `hk install` to wire the hooks against the repo-root
  # hk.pkl; this puts the binary that reads that schema on PATH so the two can't
  # drift. Pinned to v1.48.0 via the `hk` input in devenv.yaml.
  ++ [
    inputs.hk.packages.${pkgs.stdenv.system}.default
  ]
  # xvfb-run: a virtual framebuffer wrapper for the multi-window gtk4 e2e
  # (go/cmd/compass-app, design record compass-multi-window §M4) — the real
  # GTK4/WebKit shell needs a display to open windows, and dev boxes + CI
  # runners are headless. Linux-only (X11) and appended OUTSIDE the parsed
  # `packages` literal: the toolchain-parity gate resolves every bare attr in
  # that literal on macOS too, where xvfb-run does not exist. The package is
  # self-contained (its wrapper prepends its own Xvfb to PATH). CI's dedicated
  # e2e step gets it via tools/toolchain/gtk-e2e-env.nix, not this shell.
  ++ lib.optionals pkgs.stdenv.isLinux [ pkgs.xvfb-run ]
  # chromium: the browser the dev-boot smoke gate drives (apps/ui:dev-smoke,
  # design record compass-dev-boot-gate). Playwright points at it via
  # launchOptions.executablePath, resolved from PLAYWRIGHT_CHROMIUM_PATH
  # (apps/ui/playwright.config.ts:31-33). Linux-only (nixpkgs chromium has no
  # darwin build) and appended OUTSIDE the parsed `packages` literal for the
  # same reason as xvfb-run: the toolchain-parity gate resolves every bare attr
  # in that literal on macOS too, where chromium does not exist. CI's dev-smoke
  # step provisions it via tools/toolchain/chromium-e2e-env.nix, not this shell.
  ++ lib.optionals pkgs.stdenv.isLinux [ pkgs.chromium ]
  # skopeo-nix2container: the RigelBuild/nix2container fork's patched skopeo,
  # which understands the `nix:` transport (reads a nix2container image spec
  # directly). The agent-image publish lane (agent-image/publish.sh, the
  # publish-agent-image workflow, tools/agent-image-env-gate) drives it to
  # inspect and copy the built image; installing it HERE, on the dev shell the
  # publish job enters, puts a plain `skopeo` on PATH so those sites invoke it by
  # name rather than a raw, lockfile-bypassing `nix run` (OQ2 Decision 2). It is
  # deliberately NOT in agent-image/devenv.nix `packages`: that devenv is the one
  # the container module bakes into the image via the entrypoint's
  # `source ${shell.envScript}`, so a package there lands skopeo's ~168 MB
  # closure in every published agent image — a publish-only tool the running
  # agent never invokes. This shell is not a container, so nothing bakes it.
  # Resolved from the `nix2container` input pinned in devenv.lock (one source of
  # truth for the rev). Linux-only and appended OUTSIDE the parsed `with pkgs`
  # literal (same reason as xvfb-run/chromium: it is a dotted input reference,
  # not a bare nixpkgs attr, and the toolchain-parity gate throws on any non-bare
  # token in that literal).
  ++ lib.optionals pkgs.stdenv.isLinux [
    inputs.nix2container.packages.${pkgs.stdenv.system}.skopeo-nix2container
  ]
  # cloud-hypervisor / virtiofsd / passt: the microVM VMM userspace toolset the
  # elastic-session runtime's KVM-backed backend drives (design record
  # docs/designs/infra/runtime/compass-elastic-session-runtime/microvm-ci-dev-enablement.md,
  # § E-D1). cloud-hypervisor is the microVM VMM chosen in design D1; virtiofsd
  # is the virtio-fs daemon that serves the guest's filesystem; passt is the
  # userspace network backend instantiating the D6 passt/gvproxy-class net path
  # (E1 picks passt, not gvproxy: C, no in-guest Go runtime, packaged in
  # nixpkgs, and free of gvproxy's podman-machine coupling). All three are
  # ordinary user binaries that open(2) /dev/kvm but need no capability or
  # device node of their own; the host-level /dev/kvm enablement is a separate,
  # out-of-repo concern. Linux-only and appended OUTSIDE the parsed `with pkgs`
  # literal for the same reason as xvfb-run/chromium: the toolchain-parity gate
  # resolves every bare attr in that literal on macOS too, where these
  # Linux-only packages do not exist. No version pin here — the shell provides
  # one pinned version from devenv.lock; the runtime preflight (V2a+) will
  # enforce the floor, and the CI KVM leg will realize these binaries
  # out-of-band from this same pin.
  ++ lib.optionals pkgs.stdenv.isLinux [
    pkgs.cloud-hypervisor
    pkgs.virtiofsd
    pkgs.passt
  ];

  env = {
    # moon execs the vendored nix toolchain on PATH (the .moon/workspace.yml
    # system-task design) instead of resolving go/gofmt through the proto shims
    # under ~/.proto — which are present but back an absent `proto` binary, so
    # every `compass-go:*` moon task (and the jj-hp pre-push `moon ci` gate)
    # dies with a proto-shim exec error without this. Forcing globals makes moon
    # honor the documented system-task contract rather than manage its own
    # toolchain. Platform-independent, so it lives in the base set, not the
    # Linux-only merge below.
    MOON_TOOLCHAIN_FORCE_GLOBALS = "true";
  }
  # The Compass native app (Wails v3, go/cmd/compass-app) links the Linux
  # GTK4/WebKitGTK stack through cgo. pkg-config (in `packages` above) finds each
  # library's `.pc` file along PKG_CONFIG_PATH, built here over the transitive
  # propagated-dependency closure of the GTK/WebKitGTK set so a `.pc`
  # `Requires:` walk (gtk4 → zlib, pango → freetype2/fontconfig, …) resolves.
  # Both `.pc` install subdirs are searched: a dev output splits its `.pc` files
  # across `lib/pkgconfig` and `share/pkgconfig` (zlib ships `zlib.pc` under
  # `share/`, which gtk4 transitively requires), so searching only `lib/` fails the walk.
  # The package set and subdir order are defined once in
  # tools/toolchain/gtk-closure.nix (imported just below), the single
  # definition every in-repo consumer resolves so they cannot drift.
  #
  # Linux-only, and set in `env` rather than `packages`: on macOS the app links
  # the system WebKit framework, so the closure is Linux's alone; and keeping it
  # out of the parsed `packages` list means the heavy WebKitGTK closure is never
  # realized by the toolchain-parity gate on a CI runner. The per-PR moon gate
  # still never compiles the native app; the one CI lane that does — the
  # multi-window gtk4 e2e (compass-multi-window §M4) — is a dedicated,
  # affected-guarded ci.yml step that realizes this same closure out of band via
  # tools/toolchain/gtk-e2e-env.nix, so the moon battery stays GTK-free.
  // lib.optionalAttrs pkgs.stdenv.isLinux {
    PKG_CONFIG_PATH =
      let
        # The GTK4/WebKitGTK set, imported from the shared
        # module so the dev shell and the gtk4 e2e CI helper
        # (tools/toolchain/gtk-e2e-env.nix) resolve one closure and cannot drift.
        pcClosure = lib.closePropagation (import ./tools/toolchain/gtk-closure.nix pkgs);
      in
      lib.concatStringsSep ":" [
        (lib.makeSearchPathOutput "dev" "lib/pkgconfig" pcClosure)
        (lib.makeSearchPathOutput "dev" "share/pkgconfig" pcClosure)
      ];
  };

  enterShell = ''
    # Bootstrap the workspace on shell entry so a fresh clone is ready right
    # after `direnv allow` — no separate install step. --frozen-lockfile is a
    # fast no-op once node_modules is current.
    bun install --frozen-lockfile
    # Pre-push git hook (a thin shell over `moon ci`). hk install is idempotent,
    # so re-run it on every entry — a guard on the hook file being absent would
    # never pick up `hk.pkl` changes in an already-cloned checkout.
    if command -v hk >/dev/null 2>&1; then
      hk install >/dev/null 2>&1 || echo "devenv: hk install failed; run 'hk install' to enable the pre-push gate"
    fi
  '';

  # One-command Compass dogfood enroll-loop: `devenv up` stands up the full
  # backend a human can drive an agent session against. The chain:
  #
  #   postgres            — the store of record; compass-server opens it at
  #                         startup and applies its embedded migrations under an
  #                         advisory lock (go/internal/store/store.go).
  #   dogfood:gen-cert    — mints the self-signed TLS trust anchor (tls.crt /
  #                         tls.key) the network door serves and the runner
  #                         trusts. Skip-if-present, so a restart never swaps the
  #                         cert out from under a live server/runner pair.
  #   compass-server      — serves compass.v1 on a Unix socket (the local door),
  #                         a loopback gRPC-Web port for the browser UI dev
  #                         server, AND an authenticated TLS network door
  #                         (RunnerService lives only here — runners are remote
  #                         and dial the TLS door, never the loopback socket).
  #                         On network-door startup it mints the bootstrap
  #                         admin-token 0600 under the state dir.
  #   compass-ui          — the browser UI dev server (vite); serves the SolidJS
  #                         board on http://127.0.0.1:5173 and dials the
  #                         server's loopback gRPC-Web dev door directly via
  #                         VITE_COMPASS_BASE_URL. Runs after the server is ready
  #                         so the first browser load never races the migrating
  #                         store.
  #   dogfood:mint-runner-token — registers the `dogfood` runner and writes its
  #                         enrollment token; runs after the server is ready
  #                         (the readiness probe gates on the migrated store).
  #   compass-runner      — enrolls over the TLS door with that token, then
  #                         idles in RunSessions awaiting Provision/Start.
  #
  # Opt-in (NOT wired into up): `dogfood:agent-image` builds+loads the agent
  # base image (heavy closure — kept off the hot up path), and `dogfood:clean`
  # tears down the deterministic-named agent containers so a second session
  # drive does not hit a podman create name collision.
  #
  # Prereqs (the podman loop only — compass-runner, agent-image, clean): a Linux
  # dev box with rootless podman and the uid-1000 subuid/subgid ranges configured
  # (the runner guards on uid 1000 and creates per-container sockets under its
  # runtime dir); the postgres/server/UI/cert/token half runs macOS-native and
  # needs no Linux prereqs. Cert expiry: gen-cert is skip-if-present
  # forever against a finite --validity, so once the cert expires the loop fails
  # with an opaque TLS error — rerun `compass-gen-cert --force` (or delete
  # tls.crt/tls.key from the state dir) to rotate.
  #
  # Postgres, compass-server, and compass-ui run cross-platform (macOS-native
  # dogfood); only the podman-backed loop (compass-runner and the agent-image /
  # clean tasks) targets the Linux dev box.
  services.postgres = {
    enable = true;
    # The single dogfood database compass-server opens. Owned by $USER over the
    # local Unix socket (peer auth) — no password on the loopback dev path.
    initialDatabases = [ { name = "compass"; } ];
  };

  processes = {
    # compass-server: serves compass.v1 on a Unix domain socket (the shipped
    # local door) plus a loopback gRPC-Web port for the browser UI dev server.
    # It builds the binary once, then `exec`s it. process-compose does not run
    # this script directly: it runs `exec devenv-tasks run … compass-server`, so
    # the tree is process-compose → devenv-tasks → compass-server. `exec` here
    # still matters: it collapses the bash-wrapper → binary hop so no `go
    # run`/shell parent is left to orphan (exit status propagates, and the
    # compiled binary sits directly in the process group devenv-tasks signals).
    # On stop, devenv-tasks traps SIGTERM and killpg()s that group (SIGTERM,
    # then SIGKILL after a 5s grace); the SIGTERM reaches compass-server, which
    # traps it in cmd/compass-server and drains both doors. Note the 5s killpg
    # grace equals compass-server's own 5s drain deadline (server/serve.go), so
    # a drain that runs its full budget races the SIGKILL at the boundary. The
    # build is incremental/cached, so the per-restart cost is negligible.
    # Restarts on failure (devenv caps this at 5 by default) so a transient
    # store hiccup recovers.
    compass-server = {
      exec = ''
        # Build once into the state dir, then exec the binary so no shell/`go
        # run` parent lingers between devenv-tasks and compass-server — the
        # binary lands directly in the process group devenv-tasks signals on
        # stop (see the process comment above for the full signal path).
        bin="${config.devenv.state}/compass/compass-server"
        # Stamp the same scheme the release and CI lanes stamp: the semver base
        # from version.txt (the single source all build paths read), plus a
        # suffix marking this artifact as a dev-shell build. The suffix is a
        # literal `+dev` rather than `+g<shortrev>`: the repo is worked through
        # jj workspaces, where `.git` may be a file or absent, so shelling out
        # to `git rev-parse` inside the process script would be a build that
        # fails depending on which working copy it runs in.
        version_base="$(cat "${config.devenv.root}/version.txt")"
        # Validate rather than normalize: the flake path trims whitespace, so a
        # `-n` test alone would let whitespace-only or CRLF content through here
        # and diverge from it. Rejecting anything outside the semver character
        # set fails closed on all of those — and, unlike stripping whitespace,
        # never turns a malformed value into a plausible-looking stamp.
        case "$version_base" in
          "" | *[!0-9A-Za-z.+-]*)
            echo "version.txt missing or not a version string: '$version_base'" >&2
            exit 1
            ;;
        esac
        # `|| exit 1` because this script is rendered without `set -e`: a failed
        # build would otherwise fall through to the `exec` below and silently
        # run the previously-built binary, reporting a stale version.
        go build -ldflags "-X main.version=$version_base+dev" \
          -o "$bin" ./cmd/compass-server || exit 1
        exec "$bin" \
          --socket "$COMPASS_SOCKET" \
          --dev-http "127.0.0.1:${toString config.processes.compass-server.ports.devhttp.value}" \
          --database "$COMPASS_DATABASE_DSN" \
          --listen "127.0.0.1:${toString config.processes.compass-server.ports.network.value}" \
          --tls-cert "${config.devenv.state}/compass/tls.crt" \
          --tls-key "${config.devenv.state}/compass/tls.key"
      '';
      cwd = "${config.devenv.root}/go";
      ports.devhttp.allocate = 50051;
      # The authenticated TLS network door. RunnerService lives only on this
      # door, so the runner (and any remote client) dials it over TLS with the
      # gen-cert trust anchor; the loopback socket/dev-http doors stay for the
      # co-located UI/shell.
      ports.network.allocate = 50052;
      env = {
        # Unix socket under the devenv state dir so the path is stable across
        # restarts and a co-located client (the UI/shell) resolves the same one.
        COMPASS_SOCKET = "${config.devenv.state}/compass/server.sock";
        # pgx keyword/value DSN over the Postgres Unix socket ($PGHOST is the
        # socket dir, $PGPORT the allocated port — set by services.postgres).
        # No user= : pgx defaults to the OS user, which is the peer-auth identity
        # ($USER) that owns the `compass` database (services.postgres above).
        COMPASS_DATABASE_DSN = dogfoodDSN;
      };
      # Wait for Postgres to be accepting connections before starting, so the
      # store opens on the first try rather than crash-restarting until it's up.
      # (dogfood:gen-cert orders itself `before` this process so the TLS cert/key
      # the network door opens over exist by the time the server starts.)
      after = [ "devenv:processes:postgres" ];
      # Ready only once the server actually answers — not merely once the socket
      # file exists. compass-server binds (and chmods) the socket BEFORE it runs
      # the store migrations and starts accepting, so `test -S` would flip ready
      # true while a dial still blocks on the first RPC. Probe GetServerInfo over
      # the loopback dev door instead: it succeeds only after the store is
      # migrated and the handler serves, which is the real signal an `after`-
      # dependent needs.
      ready.exec = ''
        ${lib.getExe pkgs.curl} -fsS --max-time 2 \
          -H 'Content-Type: application/json' \
          -X POST \
          "http://127.0.0.1:${toString config.processes.compass-server.ports.devhttp.value}/compass.v1.CompassService/GetServerInfo" \
          -d '{}' >/dev/null
      '';
      restart.on = "on_failure";
    };

    # compass-ui: the browser UI dev server (vite). Serves the SolidJS board on
    # http://127.0.0.1:5173 and dials compass-server's loopback gRPC-Web dev
    # door directly — no vite proxy: the browser reads the door URL from
    # VITE_COMPASS_BASE_URL at boot (apps/ui/src/live/connection.ts) and the dev
    # door serves wildcard CORS (any origin — it is a loopback dev-only door),
    # which covers this browser consumer (go/server/serve.go devCORS,
    # AllowedOrigins ["*"]). `exec bunx vite` matches the moon dev task
    # (apps/ui/moon.yml) — one convention, two entry points. `after`s the
    # server's readiness probe (a real GetServerInfo answer over the dev door,
    # not merely a bound socket) so the first browser load never races the
    # migrating store.
    compass-ui = {
      exec = ''
        exec bunx vite
      '';
      cwd = "${config.devenv.root}/apps/ui";
      env = {
        # Direct-dial (decided): the browser dials the dev door directly, so the
        # base URL is the server's loopback dev-http port (devenv stays the
        # single owner of that port number).
        VITE_COMPASS_BASE_URL =
          "http://127.0.0.1:${toString config.processes.compass-server.ports.devhttp.value}";
      };
      after = [ "devenv:processes:compass-server" ];
    };
  }
  // lib.optionalAttrs pkgs.stdenv.isLinux {
    # compass-runner: enrolls with the server over the TLS network door, then
    # idles awaiting Provision/Start commands. Built into the state dir and
    # exec'd the same way as compass-server (see that process's comment for the
    # build/exec rationale and the devenv-tasks signal path). Runners are
    # remote by design, so this dials the authenticated TLS door
    # (https://127.0.0.1:<network-port>) with the gen-cert cert as the single
    # trust anchor (--ca) — never the loopback socket. The enrollment token is
    # passed via COMPASS_RUNNER_TOKEN env ONLY, never a flag (a flag would leak
    # it into the process table); the exec script reads it from the token file
    # dogfood:mint-runner-token produced. --runtime-dir overrides the root-only
    # /run/compass default with $XDG_RUNTIME_DIR/compass-runner: the runner mints
    # per-container sockets at <runtime-dir>/containers/compass-agent-<32-hex>/
    # agent.sock (a fixed 69-byte suffix) and validates at startup that the widest
    # such path fits the 107-byte AF_UNIX sun_path limit (run.go
    # validateRuntimeDir), capping the dir at 38 bytes — the deep $DEVENV_STATE
    # checkout overflows it, a short per-user /run path (this uid owns it) does
    # not. --egress-allow is omitted:
    # the base loop's local_path clone needs no network, so the agent runs pure
    # default-deny. `ready` is intentionally unset — the runner exposes no HTTP
    # surface and devenv has no log-line readiness type, so it idles unprobed;
    # nothing `after`s it, so that is safe. Restarts on failure because
    # Dial/Enroll is single-shot with no retry, so a transient enroll failure
    # would otherwise leave a permanently dead runner.
    compass-runner = {
      exec = ''
        : "''${XDG_RUNTIME_DIR:?XDG_RUNTIME_DIR must be set; the compass-runner per-container sockets live under it}"
        bin="${config.devenv.state}/compass/compass-runner"
        go build -o "$bin" ./cmd/compass-runner
        export COMPASS_RUNNER_TOKEN="$(cat "${config.devenv.state}/compass/runner.token")"
        exec "$bin" \
          --runner-id ${dogfoodRunnerID} \
          --server "https://127.0.0.1:${toString config.processes.compass-server.ports.network.value}" \
          --ca "${config.devenv.state}/compass/tls.crt" \
          --image compass-agent:latest \
          --runtime-dir "$XDG_RUNTIME_DIR/compass-runner"
      '';
      cwd = "${config.devenv.root}/go";
      # Enroll only once the token exists (mint runs after the server is ready,
      # which is after the store is migrated — so the whole chain is ordered).
      after = [ "dogfood:mint-runner-token" ];
      restart.on = "on_failure";
    };
  };

  # Dogfood loop tasks. gen-cert and mint-runner-token run cross-platform (they
  # back the macOS-native server/UI dogfood); agent-image and clean stay
  # Linux-only, as the whole podman-backed loop targets the Linux dev box.
  tasks = {
    # gen-cert: mint the self-signed TLS trust anchor the network door serves and
    # the runner trusts. Built into the state dir and run the same way the server
    # binary is (PATH/build preamble mirrors compass-server). SAN defaults
    # (127.0.0.1,::1,localhost) suffice for the loopback loop, and the binary is
    # skip-if-present, so a restart never swaps the cert out from under a live
    # server/runner pair (cert 0644 public anchor, key 0600). Ordered `before`
    # the compass-server process so the cert/key exist when the network door
    # opens over them.
    "dogfood:gen-cert" = {
      exec = ''
        bin="${config.devenv.state}/compass/compass-gen-cert"
        go build -o "$bin" ./cmd/compass-gen-cert
        exec "$bin" \
          --cert-out "${config.devenv.state}/compass/tls.crt" \
          --key-out "${config.devenv.state}/compass/tls.key"
      '';
      cwd = "${config.devenv.root}/go";
      before = [ "devenv:processes:compass-server" ];
    };

    # mint-runner-token: register the `dogfood` runner and write its enrollment
    # token 0600 (raw, no newline) to the state dir. Reads COMPASS_DATABASE_DSN
    # (the same DSN the server uses) so its store precedence matches. Runs after
    # the server is ready — the readiness probe gates on the migrated store,
    # which mint's store.Open requires. Idempotent: re-registers the same token
    # without rotating when the file exists.
    "dogfood:mint-runner-token" = {
      exec = ''
        bin="${config.devenv.state}/compass/compass-mint-runner-token"
        go build -o "$bin" ./cmd/compass-mint-runner-token
        exec "$bin" \
          --runner-id ${dogfoodRunnerID} \
          --token-out "${config.devenv.state}/compass/runner.token"
      '';
      cwd = "${config.devenv.root}/go";
      env = {
        COMPASS_DATABASE_DSN = dogfoodDSN;
      };
      after = [ "devenv:processes:compass-server" ];
    };
  }
  // lib.optionalAttrs pkgs.stdenv.isLinux {
    # agent-image and clean are Linux-only: the podman-backed image build/teardown
    # targets the Linux dev box.
    # agent-image: build AND load the agent base image into
    # containers-storage:compass-agent:latest (the ref the runner resolves with
    # no pull). `container copy` builds then copies; the devenv fork rev is
    # resolved from agent-image/devenv.lock at runtime (via
    # tools/toolchain/devenv-cli, `nix run "$src" -- …`) so it names exactly the
    # fork source the agent-image module set is pinned to — the same source
    # ci.yml's seed step resolves. Opt-in (per D5): NOT wired `after` into up —
    # the image closure is large and rebuilding it on every `up` would violate
    # the never-heavy-on-up constraint. The runner starts fine without the image;
    # it only resolves it at Provision time.
    "dogfood:agent-image" = {
      exec = ''
        set -euo pipefail
        # Drop any stale localhost/ tag BEFORE the copy. `container copy` writes
        # the fresh image to docker.io/library/compass-agent:latest, but podman
        # resolves the BARE ref `compass-agent:latest` (what the runner and the
        # e2e fixture use) against localhost/ FIRST — so a leftover
        # localhost/compass-agent:latest from an older build would SHADOW this
        # fresh copy and the runner would silently launch stale agent code.
        # Removing it first makes the bare ref resolve to the image we just built.
        # `podman rmi` exits non-zero when the tag is absent, so tolerate that.
        podman rmi -f localhost/compass-agent:latest 2>/dev/null || true
        src=$(bun "${config.devenv.root}/tools/toolchain/devenv-cli/index.ts" --lock "${config.devenv.root}/agent-image/devenv.lock" --mode flakeref)
        nix run "$src" -- container copy agent
      '';
      cwd = "${config.devenv.root}/agent-image";
    };

    # clean: tear down the deterministic-named agent containers and sweep the
    # runner's per-container socket dirs. Opt-in (not wired into up/down):
    # container names are NamePrefix + agent account id (deterministic) and the
    # runner's create-dedup is in-memory, so a second session drive after a
    # restart would hit a `podman create` name collision without this cleanup.
    "dogfood:clean" = {
      exec = ''
        set -euo pipefail
        # Uses the host's rootless podman — the same binary/storage the runner
        # execs to create these containers, so it sees them (a nix-pinned podman
        # could resolve a different containers-storage config).
        ids="$(podman ps -a --filter name=compass-agent- --format '{{.ID}}')"
        if [ -n "$ids" ]; then
          # shellcheck disable=SC2086
          podman rm -f $ids
        fi
        rm -rf "$XDG_RUNTIME_DIR/compass-runner/containers/"
        # Drop the stale localhost/ tag of the agent image. `container copy`
        # writes the fresh image to docker.io/library/compass-agent:latest, but
        # podman resolves the BARE ref `compass-agent:latest` (what the runner and
        # the e2e fixture use) against localhost/ FIRST — so a leftover
        # localhost/compass-agent:latest from an older build SHADOWS every fresh
        # copy, and the runner silently launches stale agent code. `podman rmi`
        # exits non-zero when the tag is absent, so tolerate that: the goal is a
        # clean slate, not a guaranteed prior existence.
        podman rmi -f localhost/compass-agent:latest 2>/dev/null || true
      '';
    };
  };
}
