{
  pkgs,
  lib,
  config,
  inputs,
  ...
}:
# Compass dev shell — the single source of the dev + CI toolchain. nix/devenv
# owns the language/runtime toolchains, the contract codegen tools, the Go
# analysis battery, and the linters the moon gate runs. Everything here is a
# system task's dependency: moon execs what this shell puts on PATH.
let
  # Postgres DSN shared by compass-server and dogfood:mint-runner-token. mint
  # MUST open the same store the server migrated, so both reference one binding —
  # a lone edit to either copy would silently point mint at a different database.
  dogfoodDSN = "host=${config.env.PGHOST} port=${toString config.env.PGPORT} dbname=compass sslmode=disable";

  # Runner id (enrollment subject) shared by dogfood:mint-runner-token and the
  # compass-runner process. Enroll cross-checks the token subject against
  # --runner-id, so mint and runner MUST agree or enroll is rejected — both
  # reference one binding so an overlay override moves them in lockstep.
  dogfoodRunnerID = "dogfood";

  # The go pin (tools/toolchain/versions/go.nix), version-selected from the
  # go-overlay input, which exposes each version as `go_<major>_<minor>_<patch>`
  # built over the devenv.lock-pinned nixpkgs. The parity gate selects the same
  # version through go-overlay's overlay route, so both resolve one derivation.
  goPin = import ./tools/toolchain/versions/go.nix;
  goToolchain = inputs.go-overlay.packages.${pkgs.stdenv.system}."go_${lib.replaceStrings [ "." ] [ "_" ] goPin.version}";

  # bun/node/moon vendored as nix derivations from tools/toolchain/versions/*.nix.
  # The dev shell and the parity gate (tools/toolchain/gate-tools.nix) import this
  # one module, so the two sides cannot drift.
  toolchainTools = import ./tools/toolchain/toolchain-tools.nix { inherit pkgs; };

  # The Go analysis battery (golangci-lint, govulncheck, go-licenses, nilaway),
  # each rebuilt with the go-overlay toolchain rather than the bare nixpkgs
  # attrs: those are go1.26-built and fail under go1.27 with `file requires newer
  # Go version`. Appended below (dotted refs), not in the parsed `with pkgs` list.
  goAnalysis = import ./tools/toolchain/go-analysis.nix { inherit pkgs goToolchain; };
in
{
  packages = (with pkgs; [
    # compass.v1 contract codegen. buf drives the pipeline; protobuf supplies
    # protoc; protoc-gen-go/-connect-go are the Go lane's plugins, protoc-gen-es
    # the TS lane's. All from pinned nixpkgs, not `go install`/bun devDep, so
    # each is an immutable store path buf cannot have torn mid-execution by a
    # concurrent install (which flakes the gate with a fake codegen error). A
    # nixpkgs bump that moves a plugin restamps the `@generated by` header: real
    # drift — run `moon run compass-proto:gen` and commit the restamp.
    buf
    protobuf # protoc
    protoc-gen-go
    protoc-gen-connect-go
    protoc-gen-es

    # Go gate battery (golangci-lint/govulncheck/go-licenses/nilaway) is NOT
    # here — all four are rebuilt with the go-overlay toolchain and appended
    # below, because the bare nixpkgs attrs are go1.26-built and cannot parse the
    # go1.27 stdlib. Go itself is the go-overlay toolchain, also appended below.

    # sqlc: generates typed Go from the .sql query files in
    # go/internal/store/queries, compiled against the migrations schema. Bare
    # nixpkgs attr so the toolchain-parity gate resolves it in this literal.
    sqlc

    # Lint gate. biome + rumdl are nixpkgs derivations here, not `bunx` — one
    # pin means `moon run root:lint`/`root:markdownlint` resolve the identical
    # binary for everyone. `@biomejs/biome` stays a package.json devDep for the LSP.
    biome
    rumdl

    # actionlint: static checker for the .github/workflows/ files. A bare nixpkgs
    # attr in this parsed literal so the toolchain-parity gate resolves it,
    # giving the same pinned binary everywhere.
    actionlint

    # SQL migration lint battery: squawk (migration-safety) + sqruff (SQL
    # style/lint). Bare nixpkgs attrs in this parsed literal so the parity gate
    # resolves them, one pin giving CI and every dev box the identical binaries.
    squawk
    sqruff

    # curl: the compass-server readiness probe POSTs to GetServerInfo over the
    # loopback dev-http door. Pinned here (via `lib.getExe`) rather than an
    # ambient system curl, so one-command bring-up works on any dev box —
    # including a NixOS box without curl in current-system.
    curl

    # pkg-config: the Wails v3 cgo link needs it to discover the GTK4/WebKitGTK
    # `.pc` files (via PKG_CONFIG_PATH, set in `env` below). In this parsed list,
    # not the Linux env block, because it has a gate-resolved bin and is
    # cross-platform — harmless on macOS where the app links system WebKit.
    pkg-config

    # postgresql: the dogfood e2e harness's private postgres shells out to
    # `initdb`/`postgres`/`createdb` via exec.LookPath. In the dev shell those
    # arrive from `services.postgres`, but CI's gate-tools builds its PATH ONLY
    # from `packages` — service binaries never reach a CI runner — so the prereq
    # must live here for the CI e2e gate. Bare `postgresql` (not version-suffixed)
    # for strict parity: it is the same derivation `services.postgres.package`
    # defaults to (postgresql-18.4 at this pin), so CI and dev share one postgres.
    postgresql
  ])
  # The language toolchains (bun/node/moon vendored, go from go-overlay) plus the
  # Go analysis battery rebuilt with that go toolchain. Appended OUTSIDE the
  # `with pkgs` literal because each is a dotted reference and the parity gate
  # THROWS on any non-bare token there; the gate covers these via `langs` instead.
  ++ [
    toolchainTools.bun
    toolchainTools.node
    toolchainTools.moon
    goToolchain
    goAnalysis.golangci-lint
    goAnalysis.govulncheck
    goAnalysis.go-licenses
    goAnalysis.nilaway
  ]
  # hk (jdx/hk): the jj/git pre-push hook runner. A dotted input reference,
  # appended outside the parsed literal (parity gate throws on non-bare tokens).
  # Cross-platform, so no isLinux guard. `enterShell` runs `hk install` against
  # the repo-root hk.pkl; pinned to v1.48.0 via the `hk` input in devenv.yaml.
  ++ [
    inputs.hk.packages.${pkgs.stdenv.system}.default
  ]
  # xvfb-run: virtual framebuffer wrapper for the multi-window gtk4 e2e — the
  # real GTK4/WebKit shell needs a display and dev boxes + CI runners are
  # headless. Linux-only, appended outside the parsed literal (the parity gate
  # resolves every bare attr on macOS too, where xvfb-run does not exist).
  ++ lib.optionals pkgs.stdenv.isLinux [ pkgs.xvfb-run ]
  # chromium: the browser the dev-boot smoke gate drives (apps/ui:dev-smoke).
  # Playwright points at it via PLAYWRIGHT_CHROMIUM_PATH. Linux-only (no darwin
  # build), appended outside the parsed literal for the same macOS reason as
  # xvfb-run. CI's dev-smoke provisions it via chromium-e2e-env.nix, not here.
  ++ lib.optionals pkgs.stdenv.isLinux [ pkgs.chromium ]
  # skopeo-nix2container: the nix2container fork's patched skopeo understanding
  # the `nix:` transport. The agent-image publish lane drives it; installing a
  # plain `skopeo` here lets those sites invoke it by name, not a
  # lockfile-bypassing `nix run`. Deliberately NOT in agent-image/devenv.nix,
  # whose packages get baked into every published image — this would add skopeo's
  # ~168 MB closure the running agent never uses. Resolved from the pinned
  # `nix2container` input; Linux-only, appended outside the parsed literal.
  ++ lib.optionals pkgs.stdenv.isLinux [
    inputs.nix2container.packages.${pkgs.stdenv.system}.skopeo-nix2container
  ]
  # cloud-hypervisor / virtiofsd / passt: the microVM VMM userspace toolset the
  # elastic-session runtime's KVM backend drives (compass-elastic-session-runtime
  # § E-D1): the VMM, the virtio-fs daemon, and the passt userspace net backend
  # (E1 picks passt over gvproxy). All are ordinary user binaries opening
  # /dev/kvm; host /dev/kvm enablement is out-of-repo. Linux-only, appended
  # outside the parsed literal (same macOS reason as xvfb-run). No pin here — the
  # shell provides one from devenv.lock; the runtime preflight enforces the floor.
  ++ lib.optionals pkgs.stdenv.isLinux [
    pkgs.cloud-hypervisor
    pkgs.virtiofsd
    pkgs.passt
  ]
  # secretspec: the CLI the Go secrets write path spawns BY NAME, so the write
  # path is unreachable unless this shell puts one on PATH. From the
  # `secretspec-nixpkgs` input, not this shell's nixpkgs, whose rev carries
  # 0.14.0 with no `age` provider (the encrypted-at-rest default). Matches the Go
  # SDK pin in go/go.mod, so read and write paths advance together. Dotted ref,
  # appended outside the parsed literal.
  ++ [
    inputs.secretspec-nixpkgs.legacyPackages.${pkgs.stdenv.system}.secretspec
  ];

  env = {
    # moon execs the vendored nix toolchain on PATH instead of resolving
    # go/gofmt through the ~/.proto shims, which back an absent `proto` binary
    # and otherwise kill every `compass-go:*` moon task with a shim exec error.
    # Platform-independent, so in the base set, not the Linux merge below.
    MOON_TOOLCHAIN_FORCE_GLOBALS = "true";

    # The FFI cdylib the secrets READ path dlopens (a different seam from the
    # write-path CLI); without it a local `go test` skips the armed forge-secret
    # pgtest and the shell stops matching CI. An absolute path, so in `env`.
    SECRETSPEC_FFI_LIB =
      "${(import ./tools/toolchain/secretspec-env.nix).libsecretspec}/lib/libsecretspec${pkgs.stdenv.hostPlatform.extensions.sharedLibrary}";

  }
  # The Compass native app (Wails v3) links the Linux GTK4/WebKitGTK stack
  # through cgo. pkg-config finds each `.pc` file along PKG_CONFIG_PATH, built
  # here over the transitive closure of the GTK set so a `Requires:` walk
  # resolves; both `lib/pkgconfig` and `share/pkgconfig` are searched (zlib ships
  # its `.pc` under `share/`). The set is defined once in gtk-closure.nix so
  # consumers cannot drift. Linux-only, and in `env` not `packages`: on macOS the
  # app links system WebKit, and this keeps the heavy closure off the parity gate.
  // lib.optionalAttrs pkgs.stdenv.isLinux {
    PKG_CONFIG_PATH =
      let
        # The GTK4/WebKitGTK set, from the shared module so the dev shell and the
        # gtk4 e2e CI helper resolve one closure and cannot drift.
        pcClosure = lib.closePropagation (import ./tools/toolchain/gtk-closure.nix pkgs);
      in
      lib.concatStringsSep ":" [
        (lib.makeSearchPathOutput "dev" "lib/pkgconfig" pcClosure)
        (lib.makeSearchPathOutput "dev" "share/pkgconfig" pcClosure)
      ];

    # The visual-regression gate (apps/ui:visual-gate) rasterizes text with these
    # faces, pinned to the same devenv.lock nixpkgs CI uses (with hinting/AA also
    # pinned), so a local run and a CI run rasterize identically. The config sees
    # ONLY the pinned faces, so the host's font set cannot sway the output.
    # Linux-only: chromium is Linux-only so darwin cannot run the gate, and
    # FONTCONFIG_FILE is process-tree-wide.
    FONTCONFIG_FILE = (import tools/toolchain/chromium-e2e-env.nix).fontconfig;

    # The gate's baselines are captured against this exact Chromium, so a dev
    # shell that leaves it unset falls through playwright.config.ts's default to
    # the host browser and reds every shot on version skew alone.
    PLAYWRIGHT_CHROMIUM_PATH =
      "${(import tools/toolchain/chromium-e2e-env.nix).chromium}/bin/chromium";
  };

  enterShell = ''
    # Bootstrap the workspace on shell entry so a fresh clone is ready right
    # after `direnv allow` — no separate install step. --frozen-lockfile is a
    # fast no-op once node_modules is current.
    bun install --frozen-lockfile
    # Pre-push git hook (a thin shell over `moon ci`). hk install is idempotent,
    # so re-run it on every entry — a guard on the hook file being absent would
    # never pick up `hk.pkl` changes in an already-cloned checkout.
    if command -v hk >/dev/null 2>&1; then
      hk install >/dev/null 2>&1 || echo "devenv: hk install failed; run 'hk install' to enable the pre-push gate"
    fi
  '';

  # One-command Compass dogfood enroll-loop: `devenv up` stands up the full
  # backend (postgres + nats → gen-cert → compass-server → compass-ui →
  # mint-runner-token → compass-runner, plus build-cli). Ordering is load-bearing:
  # each stage `after`s the store/cert/token the next needs, and dogfood:build-cli
  # uses a `before` edge (nothing execs it, so an `after` edge would drop it from
  # `up`'s upstream-only closure). A CLI compile error thus fails `up` WHOLESALE —
  # accepted so a non-compiling CLI cannot be ignored (`--mode single` escapes it).
  # Opt-in (NOT in up): dogfood:agent-image (heavy closure) and dogfood:clean.
  # The podman loop (runner/agent-image/clean) needs a Linux box with rootless
  # podman + uid-1000 subuid/subgid; the postgres/server/UI/cert/token half runs
  # macOS-native. gen-cert is skip-if-present forever, so an expired cert fails
  # the loop with an opaque TLS error — rerun `compass-gen-cert --force` to rotate.
  services.postgres = {
    enable = true;
    # The single dogfood database compass-server opens. Owned by $USER over the
    # local Unix socket (peer auth) — no password on the loopback dev path.
    initialDatabases = [ { name = "compass"; } ];
  };

  processes = {
    # nats: the event-fabric broker. compass-server publishes comms events to it
    # and delivery consumes them, so the server refuses to boot without it.
    # JetStream stores under the state dir; loopback-only, like the stack's.
    nats = {
      exec = ''
        exec ${lib.getExe pkgs.nats-server} -js -a 127.0.0.1 \
          -p ${toString config.processes.nats.ports.client.value} \
          -m ${toString config.processes.nats.ports.monitor.value} \
          -sd "${config.devenv.state}/nats"
      '';
      ports.client.allocate = 4222;
      ports.monitor.allocate = 8222;
      # /healthz answers 200 only once JetStream is enabled, the same readiness
      # verdict the self-host stack probes.
      ready.exec = ''
        ${lib.getExe pkgs.curl} -fsS --max-time 2 \
          "http://127.0.0.1:${toString config.processes.nats.ports.monitor.value}/healthz" >/dev/null
      '';
      restart.on = "on_failure";
    };

    # compass-server: serves compass.v1 on a Unix socket plus a loopback
    # gRPC-Web port. Builds once then `exec`s the binary so no shell/`go run`
    # parent lingers — the binary sits directly in the process group devenv-tasks
    # killpg()s on stop (SIGTERM, then SIGKILL after a 5s grace). That 5s grace
    # equals compass-server's own 5s drain deadline, so a full-budget drain races
    # the SIGKILL. Restarts on failure (devenv caps at 5) so a store hiccup recovers.
    compass-server = {
      exec = ''
        # Build once into the state dir, then exec the binary so no shell/`go
        # run` parent lingers between devenv-tasks and compass-server — the
        # binary lands directly in the process group devenv-tasks signals on
        # stop (see the process comment above for the full signal path).
        bin="${config.devenv.state}/compass/compass-server"
        # Stamp the same scheme the release and CI lanes stamp: the semver base
        # from version.txt (the single source all build paths read), plus a
        # suffix marking this artifact as a dev-shell build. The suffix is a
        # literal `+dev` rather than `+g<shortrev>`: the repo is worked through
        # jj workspaces, where `.git` may be a file or absent, so shelling out
        # to `git rev-parse` inside the process script would be a build that
        # fails depending on which working copy it runs in.
        version_base="$(cat "${config.devenv.root}/version.txt")"
        # Trim the same four bytes nixpkgs `lib.strings.trim` strips on the
        # flake side (space, tab, CR, LF — both ends), THEN apply the same
        # character class the flake applies to its trimmed value. Both steps
        # are needed for the two lanes to accept exactly the same file: the
        # flake trims before matching, so checking the untrimmed bytes here
        # would reject a CRLF or tab-padded file the flake happily stamps —
        # `nix build` green while `devenv up` hard-fails on one tree. Trimming
        # only the surrounding whitespace (never inner) keeps the guard from
        # turning a malformed value into a plausible-looking stamp: `0.1.0 rc1`
        # is rejected, not silently stamped as `0.1.0rc1`. The class is a shape
        # filter, not a full semver parse. The two lanes are held in agreement
        # by the flake-gate:version-guard parity gate, which runs both guards
        # over a shared candidate table.
        while :; do
          case "$version_base" in
            [$' \t\r\n']*) version_base="''${version_base#?}" ;;
            *[$' \t\r\n']) version_base="''${version_base%?}" ;;
            *) break ;;
          esac
        done
        case "$version_base" in
          "" | *[!0-9A-Za-z.+-]*)
            printf 'version.txt missing or not a version string: %q\n' \
              "$version_base" >&2
            exit 1
            ;;
        esac
        # Explicit `|| exit 1` rather than leaning on the `set -e` devenv
        # injects into the rendered task script (its src/modules/tasks.nix
        # emits it for every non-status bash task): a failed build must not
        # fall through to the `exec` below and silently run the previously-built
        # binary at a stale version, and that must hold whether or not the
        # pinned devenv keeps rendering the wrapper.
        go build -ldflags "-X main.version=$version_base+dev" \
          -o "$bin" ./cmd/compass-server || exit 1
        exec "$bin" \
          --socket "$COMPASS_SOCKET" \
          --dev-http "127.0.0.1:${toString config.processes.compass-server.ports.devhttp.value}" \
          --database "$COMPASS_DATABASE_DSN" \
          --listen "127.0.0.1:${toString config.processes.compass-server.ports.network.value}" \
          --tls-cert "${config.devenv.state}/compass/tls.crt" \
          --tls-key "${config.devenv.state}/compass/tls.key"
      '';
      cwd = "${config.devenv.root}/go";
      ports.devhttp.allocate = 50051;
      # The authenticated TLS network door. RunnerService lives only on this
      # door, so the runner (and any remote client) dials it over TLS with the
      # gen-cert trust anchor; the loopback socket/dev-http doors stay for the
      # co-located UI/shell.
      ports.network.allocate = 50052;
      env = {
        # Unix socket under the devenv state dir so the path is stable across
        # restarts and a co-located client (the UI/shell) resolves the same one.
        COMPASS_SOCKET = "${config.devenv.state}/compass/server.sock";
        # pgx keyword/value DSN over the Postgres Unix socket. No user= : pgx
        # defaults to the OS user, the peer-auth identity that owns `compass`.
        COMPASS_DATABASE_DSN = dogfoodDSN;
        # The event fabric; compass-server reads it when --nats-url is absent.
        COMPASS_NATS_URL = "nats://127.0.0.1:${toString config.processes.nats.ports.client.value}";
      };
      # Wait for Postgres and NATS before starting: the server opens the store
      # and connects the event fabric at boot, and fails closed on either.
      # (dogfood:gen-cert orders `before` this so the TLS cert/key exist when
      # the network door opens.)
      after = [ "devenv:processes:postgres" "devenv:processes:nats" ];
      # Ready only once the server answers, not merely once the socket exists:
      # compass-server binds the socket BEFORE migrating and accepting, so
      # `test -S` would flip ready true while a dial still blocks. Probe
      # GetServerInfo, which succeeds only after the store is migrated.
      ready.exec = ''
        ${lib.getExe pkgs.curl} -fsS --max-time 2 \
          -H 'Content-Type: application/json' \
          -X POST \
          "http://127.0.0.1:${toString config.processes.compass-server.ports.devhttp.value}/compass.v1.CompassService/GetServerInfo" \
          -d '{}' >/dev/null
      '';
      restart.on = "on_failure";
    };

    # compass-ui: the browser UI dev server (vite). Serves the SolidJS board on
    # :5173 and dials compass-server's loopback gRPC-Web dev door directly (no
    # vite proxy) — the browser reads the URL from VITE_COMPASS_BASE_URL and the
    # dev door serves wildcard CORS. `after`s the server's readiness probe so
    # the first browser load never races the migrating store.
    compass-ui = {
      exec = ''
        exec bunx vite
      '';
      cwd = "${config.devenv.root}/apps/ui";
      env = {
        # Direct-dial: the browser dials the dev door directly, so the base URL
        # is the server's loopback dev-http port.
        VITE_COMPASS_BASE_URL =
          "http://127.0.0.1:${toString config.processes.compass-server.ports.devhttp.value}";
      };
      after = [ "devenv:processes:compass-server" ];
    };
  }
  // lib.optionalAttrs pkgs.stdenv.isLinux {
    # compass-runner: enrolls with the server over the TLS network door, then
    # idles awaiting Provision/Start. Built and exec'd like compass-server.
    # Runners are remote by design, so this dials the authenticated TLS door with
    # the gen-cert cert as sole trust anchor (--ca), never the loopback socket.
    # The token is passed via COMPASS_RUNNER_TOKEN env ONLY (a flag would leak it
    # into the process table). --runtime-dir overrides the root-only /run/compass
    # with $XDG_RUNTIME_DIR/compass-runner: per-container socket paths must fit
    # the 107-byte AF_UNIX limit (validateRuntimeDir caps the dir at 38 bytes),
    # which the deep $DEVENV_STATE checkout overflows and a short /run path does
    # not. Restarts on failure because Dial/Enroll is single-shot with no retry.
    compass-runner = {
      exec = ''
        set -euo pipefail
        : "''${XDG_RUNTIME_DIR:?XDG_RUNTIME_DIR must be set; the compass-runner per-container sockets live under it}"
        bin="${config.devenv.state}/compass/compass-runner"
        go build -o "$bin" ./cmd/compass-runner
        # Assign, then export. `export VAR="$(cmd)"` is itself a command whose
        # own exit status (0) masks the substitution's, so `set -e` never sees a
        # failed read: an empty token misreports as unset, a truncated one
        # fails Enroll as `unauthenticated`.
        COMPASS_RUNNER_TOKEN="$(cat "${config.devenv.state}/compass/runner.token")"
        export COMPASS_RUNNER_TOKEN
        exec "$bin" \
          --runner-id ${dogfoodRunnerID} \
          --server "https://127.0.0.1:${toString config.processes.compass-server.ports.network.value}" \
          --ca "${config.devenv.state}/compass/tls.crt" \
          --image compass-agent:latest \
          --runtime-dir "$XDG_RUNTIME_DIR/compass-runner"
      '';
      cwd = "${config.devenv.root}/go";
      # Enroll only once the token exists (mint runs after the server is ready,
      # which is after the store is migrated — so the whole chain is ordered).
      after = [ "dogfood:mint-runner-token" ];
      restart.on = "on_failure";
    };
  };

  # Dogfood loop tasks. gen-cert, build-cli and mint-runner-token run
  # cross-platform (backing the macOS-native dogfood); agent-image and clean stay
  # Linux-only, as the whole podman-backed loop targets the Linux dev box.
  tasks = {
    # gen-cert: mint the self-signed TLS trust anchor the network door serves and
    # the runner trusts. Skip-if-present, so a restart never swaps the cert out
    # from under a live server/runner pair. Ordered `before` compass-server so
    # the cert/key exist when the network door opens.
    "dogfood:gen-cert" = {
      exec = ''
        set -euo pipefail
        bin="${config.devenv.state}/compass/compass-gen-cert"
        go build -o "$bin" ./cmd/compass-gen-cert
        exec "$bin" \
          --cert-out "${config.devenv.state}/compass/tls.crt" \
          --key-out "${config.devenv.state}/compass/tls.key"
      '';
      cwd = "${config.devenv.root}/go";
      before = [ "devenv:processes:compass-server" ];
    };

    # build-cli: build the operator CLI (`./cmd/compass`) into the state dir so a
    # human always has a binary matching the source. Unlike the four execed
    # builds, nothing runs this at boot, so it needs a `before` edge to land in
    # `up`'s upstream-only closure at all (an `after` edge dropped it entirely).
    # The build is unconditional and `rm -f "$bin"` first: `go build -o` leaves
    # the old binary on failure, so a failed rebuild would silently run stale code
    # (undetectable while `--version` is static — RIG-3346); removing first makes
    # that a self-announcing "no such file". A compile error fails the task, thus
    # `up`, taking the whole downstream stack with it — accepted so a broken CLI
    # cannot be ignored (`devenv up --mode single` is the escape hatch).
    "dogfood:build-cli" = {
      exec = ''
        set -euo pipefail
        bin="${config.devenv.state}/compass/compass"
        rm -f "$bin"
        go build -o "$bin" ./cmd/compass
      '';
      cwd = "${config.devenv.root}/go";
      before = [ "devenv:processes:compass-server" ];
    };

    # mint-runner-token: register the `dogfood` runner and write its enrollment
    # token 0600 to the state dir. Reads the same DSN the server uses so store
    # precedence matches. Runs after the server is ready (its probe gates on the
    # migrated store). Idempotent: re-registers the same token when the file exists.
    "dogfood:mint-runner-token" = {
      exec = ''
        set -euo pipefail
        bin="${config.devenv.state}/compass/compass-mint-runner-token"
        go build -o "$bin" ./cmd/compass-mint-runner-token
        exec "$bin" \
          --runner-id ${dogfoodRunnerID} \
          --token-out "${config.devenv.state}/compass/runner.token"
      '';
      cwd = "${config.devenv.root}/go";
      env = {
        COMPASS_DATABASE_DSN = dogfoodDSN;
      };
      after = [ "devenv:processes:compass-server" ];
    };
  }
  // lib.optionalAttrs pkgs.stdenv.isLinux {
    # agent-image: build AND load the agent base image into
    # containers-storage:compass-agent:latest (the ref the runner resolves with no
    # pull). The devenv fork rev is resolved from agent-image/devenv.lock at
    # runtime, so it names exactly the source the module set is pinned to. Opt-in
    # (per D5): NOT wired into up — the image closure is large and rebuilding it
    # on every `up` would violate the never-heavy-on-up constraint.
    "dogfood:agent-image" = {
      exec = ''
        set -euo pipefail
        # Drop any stale localhost/ tag BEFORE the copy. `container copy` writes
        # the fresh image to docker.io/library/compass-agent:latest, but podman
        # resolves the BARE ref `compass-agent:latest` (what the runner and the
        # e2e fixture use) against localhost/ FIRST — so a leftover
        # localhost/compass-agent:latest from an older build would SHADOW this
        # fresh copy and the runner would silently launch stale agent code.
        # Removing it first makes the bare ref resolve to the image we just built.
        # `podman rmi` exits non-zero when the tag is absent, so tolerate that.
        podman rmi -f localhost/compass-agent:latest 2>/dev/null || true
        src=$(bun "${config.devenv.root}/tools/toolchain/devenv-cli/index.ts" --lock "${config.devenv.root}/agent-image/devenv.lock" --mode flakeref)
        nix run "$src" -- container copy agent
      '';
      cwd = "${config.devenv.root}/agent-image";
    };

    # clean: tear down the deterministic-named agent containers and sweep the
    # runner's per-container socket dirs. Opt-in (not wired into up/down): the
    # names are deterministic and the runner's create-dedup is in-memory, so a
    # second session drive after a restart would hit a `podman create` collision.
    "dogfood:clean" = {
      exec = ''
        set -euo pipefail
        # Same guard the compass-runner process uses, and it runs FIRST: under
        # `set -u` an unset XDG_RUNTIME_DIR otherwise aborts the task after the
        # containers are already removed, so it half-succeeds and reports failure.
        : "''${XDG_RUNTIME_DIR:?XDG_RUNTIME_DIR must be set; the compass-runner per-container sockets live under it}"
        # Uses the host's rootless podman — the same binary/storage the runner
        # execs to create these containers, so it sees them (a nix-pinned podman
        # could resolve a different containers-storage config).
        ids="$(podman ps -a --filter name=compass-agent- --format '{{.ID}}')"
        if [ -n "$ids" ]; then
          # shellcheck disable=SC2086
          podman rm -f $ids
        fi
        rm -rf "$XDG_RUNTIME_DIR/compass-runner/containers/"
        # Drop the stale localhost/ tag of the agent image. `container copy`
        # writes the fresh image to docker.io/library/compass-agent:latest, but
        # podman resolves the BARE ref `compass-agent:latest` (what the runner and
        # the e2e fixture use) against localhost/ FIRST — so a leftover
        # localhost/compass-agent:latest from an older build SHADOWS every fresh
        # copy, and the runner silently launches stale agent code. `podman rmi`
        # exits non-zero when the tag is absent, so tolerate that: the goal is a
        # clean slate, not a guaranteed prior existence.
        podman rmi -f localhost/compass-agent:latest 2>/dev/null || true
      '';
    };
  };
}
