#!/usr/bin/env bun
// Renders the homebrew-tap `compass-cli` formula from a release's tag and its
// SHA256SUMS. `renderFormula` is pure; main() reads SHA256SUMS and writes the
// formula, and the release lane commits it to RigelBuild/homebrew-tap.

const REPO = "RigelBuild/compass";

/** The CLI release assets the formula installs, keyed by the Homebrew arch block. */
const PLATFORMS = [
	{ block: "on_macos", cpu: "on_arm", suffix: "darwin-arm64" },
	{ block: "on_linux", cpu: "on_intel", suffix: "linux-amd64" },
] as const;

/** Parse `sha256sum` output into a file name → hex digest map. */
export function parseSha256Sums(text: string): Map<string, string> {
	const sums = new Map<string, string>();
	for (const line of text.split("\n")) {
		if (line.trim() === "") continue;
		const match = /^([0-9a-f]{64}) [ *](.+)$/.exec(line);
		if (!match?.[1] || !match[2]) {
			throw new Error(`SHA256SUMS: malformed line ${JSON.stringify(line)}`);
		}
		sums.set(match[2], match[1]);
	}
	return sums;
}

/** Render Formula/compass-cli.rb for a semver release tag (`vX.Y.Z`). */
export function renderFormula(tag: string, sums: Map<string, string>): string {
	const version = /^v(\d+\.\d+\.\d+)$/.exec(tag)?.[1];
	if (!version) {
		throw new Error(
			`tag ${JSON.stringify(tag)} is not a semver release tag (vX.Y.Z)`,
		);
	}
	const blocks = PLATFORMS.map(({ block, cpu, suffix }) => {
		const asset = `compass_${tag}_${suffix}`;
		const sha = sums.get(asset);
		if (!sha) throw new Error(`SHA256SUMS has no entry for ${asset}`);
		return `  ${block} do
    ${cpu} do
      url "https://github.com/${REPO}/releases/download/${tag}/${asset}"
      sha256 "${sha}"
    end
  end`;
	});
	return `# Generated by the compass release workflow (tools/homebrew-tap); do not edit.
class CompassCli < Formula
  desc "Operator CLI for a Compass fleet"
  homepage "https://github.com/${REPO}"
  version "${version}"
  license "AGPL-3.0-only"

${blocks.join("\n\n")}

  def install
    bin.install Dir["compass_*"].first => "compass"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/compass --version")
  end
end
`;
}

if (import.meta.main) {
	const [tag, sumsPath, outPath] = process.argv.slice(2);
	if (!tag || !sumsPath || !outPath) {
		console.error("usage: homebrew-tap <tag> <SHA256SUMS> <out.rb>");
		process.exit(2);
	}
	const sums = parseSha256Sums(await Bun.file(sumsPath).text());
	await Bun.write(outPath, renderFormula(tag, sums));
}
