// sea-ref-gate (RIG-2804) — fail-closed CI check that the compass tree carries
// no `SEA-NNN` issue reference. The Linear team key was renamed SEA→RIG with
// issue numbers preserved 1:1 (SEA-1512 == RIG-1512); a one-time codemod flipped
// every tracked ref (RIG-2804 P1). This gate keeps the boundary from silently
// re-rotting — the same fail-closed pattern as orion-ref-gate and
// design-ledger-gate.
//
// SCOPE: the `SEA-<n>` issue-ref token ONLY. A sibling to orion-ref-gate, not an
// extension of it: orion-ref-gate is deliberately scoped to its single token
// and states that it does not double as a general brand-token gate, so the SEA
// boundary gets its own gate rather than bloating that one.
//
// What counts as a reference: the UPPERCASE-NUMERIC whole-word token
// `SEA-<digits>` (e.g. `SEA-1512`, `Refs SEA-965`). This is exactly what the P1
// codemod flipped, so the gate is symmetric with it. Deliberately NOT matched
// (mirrors the codemod, which left these untouched):
//   - lowercase `sea-1243` branch-slug artifacts — historical git branch names
//     quoted in design records; the team rename does not rewrite the past.
//   - `SEA-nnn` / `SEA-NNN` / `SEA-N` prose placeholders — the digit class
//     rejects letters, so these stay as generic "some issue number" prose.
//
// CARVE-OUTS (never scanned):
//   - forks/**            vendored upstream subtrees; any SEA-like token there
//                         is upstream text, not a compass-authored issue ref.
//                         (First-party forks/README.md is NOT carved out.)
//   - tools/sea-ref-gate/**  this gate's own source + fixtures name the token to
//                         describe what it forbids.
//   - apps/eng-docs/src/content/docs/**, apps/eng-docs/dist/**  generated copies
//                         of docs/ (gitignored; regenerated by gather.ts). The
//                         canonical source under docs/ is what the gate governs.
//   - an explicit ALLOWLIST of exact repo-relative paths, each with a reason,
//                         for a genuine non-issue-ref use. Empty today.
//
// The scan reads tracked files via `git grep`, so untracked build output and
// node_modules are never considered.
//
// Exit codes:
//   0 - no references (clean)
//   1 - one or more references (printed one per line as `<file>:<line>: <text>`)
//   2 - usage / internal error (e.g. not a git tree)
//
// Usage: bun run tools/sea-ref-gate/index.ts

import { $ } from "bun";

/** The retired Linear team key, as an uppercase-numeric issue ref. */
export const SEA_REF_RE = /\bSEA-\d+\b/;

/**
 * Repo-relative path prefixes never scanned. A reference under one of these is
 * either upstream text (forks/), a generated copy (eng-docs), or this gate's
 * own description of what it forbids.
 */
export const CARVEOUT_PREFIXES: readonly string[] = [
	"forks/",
	"tools/sea-ref-gate/",
	"apps/eng-docs/src/content/docs/",
	"apps/eng-docs/dist/",
];

/**
 * Exact repo-relative paths never scanned — generated files that mechanically
 * carry a token.
 */
export const CARVEOUT_PATHS: readonly string[] = ["bun.lock"];

/**
 * Exact repo-relative paths exempted with a reason — for a genuine non-issue-ref
 * use of the token. Empty today: every tracked `SEA-<n>` in compass was a live
 * issue ref and was flipped. Add a path here ONLY with a one-line reason, and
 * prefer rewording the text.
 */
export const ALLOWLIST: Readonly<Record<string, string>> = {};

/** One scanned line carrying the token. */
export interface Reference {
	readonly file: string;
	readonly line: number;
	readonly text: string;
}

/** True when a repo-relative path is carved out of the scan. */
export function isCarveOut(path: string): boolean {
	if (path in ALLOWLIST) return true;
	// forks/README.md is first-party compass prose, not a vendored subtree —
	// it is scanned like any other authored file.
	if (path === "forks/README.md") return false;
	if (CARVEOUT_PATHS.includes(path)) return true;
	return CARVEOUT_PREFIXES.some((prefix) => path.startsWith(prefix));
}

/**
 * Whole-word, uppercase-numeric match for the retired issue-ref token in one
 * line. Lowercase `sea-<n>` slugs and `SEA-<letters>` placeholders do not match.
 */
export function lineHasToken(text: string): boolean {
	return SEA_REF_RE.test(text);
}

/**
 * The pure gate decision: given `git grep -n` style hits (each `file:line:text`)
 * return the references that are NOT carved out. Pure — the caller supplies the
 * raw hits, so tests drive it over fixtures with no git.
 */
export function findViolations(grepHits: readonly string[]): Reference[] {
	const out: Reference[] = [];
	for (const hit of grepHits) {
		const trimmed = hit.trimEnd();
		if (trimmed.length === 0) continue;
		// `git grep -n` emits `path:line:text`; text may itself contain colons.
		const firstColon = trimmed.indexOf(":");
		const secondColon = trimmed.indexOf(":", firstColon + 1);
		if (firstColon < 0 || secondColon < 0) continue;
		const file = trimmed.slice(0, firstColon);
		const line = Number(trimmed.slice(firstColon + 1, secondColon));
		const text = trimmed.slice(secondColon + 1);
		if (!Number.isInteger(line)) continue;
		if (isCarveOut(file)) continue;
		if (!lineHasToken(text)) continue;
		out.push({ file, line, text });
	}
	return out;
}

/** Injected I/O, so the runner is testable without a real git tree. */
export interface Deps {
	/** Return `git grep -n` hits for the token across tracked files. */
	grep: () => Promise<string[]>;
	log: (msg: string) => void;
	err: (msg: string) => void;
}

export async function runOnce(deps: Deps): Promise<number> {
	let hits: string[];
	try {
		hits = await deps.grep();
	} catch (e) {
		deps.err(`sea-ref-gate: cannot scan the tree: ${String(e)}`);
		return 2;
	}
	const violations = findViolations(hits);
	if (violations.length > 0) {
		deps.err(
			`sea-ref-gate: ${violations.length} retired SEA-NNN issue reference(s) in the tree:`,
		);
		for (const v of violations)
			deps.err(`  ${v.file}:${v.line}: ${v.text.trim()}`);
		deps.err(
			"The Linear team key is RIG (issue numbers preserved 1:1). " +
				"Write RIG-<n>, not SEA-<n>.",
		);
		return 1;
	}
	deps.log("sea-ref-gate: clean — no retired SEA-NNN issue references.");
	return 0;
}

/** `git grep -nIE 'SEA-[0-9]+'` over tracked files; empty on no match (exit 1). */
async function gitGrep(): Promise<string[]> {
	const raw = await $`git grep -nIE ${"SEA-[0-9]+"}`.nothrow().text();
	return raw.split("\n").filter((l) => l.length > 0);
}

if (import.meta.main) {
	const code = await runOnce({
		grep: gitGrep,
		log: (m) => console.log(m),
		err: (m) => console.error(m),
	});
	process.exit(code);
}
