// Code generated by gen_credential_keys.go; DO NOT EDIT.
//
// Source: @oh-my-pi/pi-coding-agent src/config/settings-schema.ts (isCredential
// markers: `credential: true` at the def level OR `ui.secret === true`). Refresh
// with `cd go/internal/store && go generate ./...` at an SDK bump.

package store

// credentialKeys is the SDK's credential-marked setting paths (isCredential).
// A settings/config.yml that sets any of these is rejected at the store door.
var credentialKeys = []string{
	"auth.broker.token",
	"dev.autoqaPush.token",
	"hindsight.apiToken",
	"images.urls.credentials",
	"mnemopi.embeddingApiKey",
	"mnemopi.llmApiKey",
	"searxng.basicPassword",
	"searxng.token",
}

// schemaTotalPaths is the number of top-level paths the schema carried when
// this file was generated. The generator compares against it to catch a
// parser that has stopped collecting properly (see gen_credential_keys.go).
const schemaTotalPaths = 481
