//go:build ignore

// gen_credential_keys.go regenerates credential_keys_gen.go from the OMP SDK's
// settings schema. It is the authoritative refresh step for the store door's
// credential denylist (RIG-1678 T1, OQ-2 (c)): the door rejects a
// settings/config.yml that sets any SDK credential-marked path, and that path
// set MUST track the SDK's own isCredential marker across SDK bumps.
//
// isCredential (@oh-my-pi/pi-coding-agent src/config/settings-schema.ts,
// `export function isCredential`) marks a path credential when its schema def
// carries EITHER `credential: true` at the def level OR `ui.secret === true`.
// This generator reproduces that exact rule by structurally parsing the
// SETTINGS_SCHEMA object literal — a self-contained scan with no Node/Bun
// runtime and no native-module load, so it stays reproducible at an SDK bump
// (running isCredential itself would drag the SDK's native `@oh-my-pi/pi-*`
// modules and their platform binaries into the build).
//
// The schema is read from the INSTALLED package in node_modules rather than a
// vendored copy, so the denylist tracks the pinned dependency. It resolves
// through the CONSUMING package's own dependency edge (see schemaRelPath), so
// the denylist is generated from the schema compass-agent actually runs.
//
// Refresh at an SDK bump: from go/internal/store, run
//
//	go generate ./...
//
// (the //go:generate directive on credentialKeys in agent_config.go invokes
// this), then commit the regenerated credential_keys_gen.go. This is the
// SDK-bump checklist entry CP-3's prevention property names — any new
// credential-marked SDK path lands in the denylist here.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
)

// schemaRelPath is the settings schema, relative to this generator's own
// directory (go/internal/store) — resolved from runtime.Caller so `go generate`
// finds it regardless of the caller's working directory.
//
// It deliberately resolves through the CONSUMING workspace package's own
// node_modules edge rather than bun's `node_modules/.bun/node_modules/` hoist
// alias. That alias is a flat namespace with one entry per package NAME, so
// with two dependents on different versions it can resolve to a version the
// agent does not run — and it would fail silently, since the wrong schema
// still parses fine. This path expresses the real invariant: the schema
// belonging to the package that consumes the SDK.
//
// The schema lives in gitignored node_modules, so an SDK bump changes this
// generator's input without touching any tracked file. The
// `compass-go:credential-keys-drift` CI task is what makes such a bump fail
// loudly if the denylist was not regenerated; a `bun install` must have run
// before `go generate`.
const schemaRelPath = "../../../packages/compass-agent/node_modules/@oh-my-pi/pi-coding-agent/src/config/settings-schema.ts"

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "gen_credential_keys:", err)
		os.Exit(1)
	}
}

func run() error {
	_, self, _, ok := runtime.Caller(0)
	if !ok {
		return fmt.Errorf("cannot resolve generator source path")
	}
	schemaPath := filepath.Join(filepath.Dir(self), schemaRelPath)
	src, err := os.ReadFile(schemaPath)
	if err != nil {
		return fmt.Errorf("read settings schema %q: %w", schemaPath, err)
	}

	keys, total, err := extractCredentialKeys(string(src))
	if err != nil {
		return fmt.Errorf("parse settings schema: %w", err)
	}
	if len(keys) == 0 {
		return fmt.Errorf("no credential-marked paths found — schema shape changed, refusing to emit an empty denylist")
	}
	// A plausibility floor on the TOTAL parsed key count. The empty-denylist
	// guard above only catches a total parse failure; the hand-rolled parser's
	// real risk is UNDER-collection — a def shape it mishandles yields a short
	// list, not an error, which would silently drop a path from the door's
	// denylist. The pinned schema carries ~480 top-level paths, so a count far
	// below that means the parser lost its footing on a new shape.
	if total < minSchemaKeys {
		return fmt.Errorf("parsed only %d top-level schema paths (expected >= %d) — schema shape changed and the parser is likely under-collecting; refusing to emit a possibly-short denylist", total, minSchemaKeys)
	}
	sort.Strings(keys)

	var b bytes.Buffer
	fmt.Fprintln(&b, "// Code generated by gen_credential_keys.go; DO NOT EDIT.")
	fmt.Fprintln(&b, "//")
	fmt.Fprintln(&b, "// Source: @oh-my-pi/pi-coding-agent src/config/settings-schema.ts (isCredential")
	fmt.Fprintln(&b, "// markers: `credential: true` at the def level OR `ui.secret === true`). Refresh")
	fmt.Fprintln(&b, "// with `go generate ./...` from go/internal/store at an SDK bump.")
	fmt.Fprintln(&b, "")
	fmt.Fprintln(&b, "package store")
	fmt.Fprintln(&b, "")
	fmt.Fprintln(&b, "// credentialKeys is the SDK's credential-marked setting paths (isCredential).")
	fmt.Fprintln(&b, "// A settings/config.yml that sets any of these is rejected at the store door.")
	fmt.Fprintln(&b, "var credentialKeys = []string{")
	for _, k := range keys {
		fmt.Fprintf(&b, "\t%q,\n", k)
	}
	fmt.Fprintln(&b, "}")

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return fmt.Errorf("gofmt generated source: %w", err)
	}
	outPath := filepath.Join(filepath.Dir(self), "credential_keys_gen.go")
	if err := os.WriteFile(outPath, formatted, 0o644); err != nil {
		return fmt.Errorf("write %q: %w", outPath, err)
	}
	fmt.Fprintf(os.Stderr, "gen_credential_keys: wrote %d credential paths to %s\n", len(keys), outPath)
	return nil
}

// minSchemaKeys is the plausibility floor for the total top-level path count
// (see the check in run). The pinned schema has ~480; this is set well below to
// stay quiet across ordinary schema growth or trimming while still catching a
// parser that has stopped walking the literal properly.
const minSchemaKeys = 400

// extractCredentialKeys parses the SETTINGS_SCHEMA object literal in the schema
// source and returns every top-level key whose def is credential-marked, plus
// the total number of top-level keys walked (for run's plausibility floor). It
// mirrors isCredential: a def is credential-marked when it has `credential:
// true` directly, or a `ui` object with `secret: true`.
func extractCredentialKeys(src string) ([]string, int, error) {
	p := &jsParser{s: src}
	if err := p.seekSchema(); err != nil {
		return nil, 0, err
	}
	schema, err := p.parseObject()
	if err != nil {
		return nil, 0, err
	}
	var keys []string
	for key, val := range schema {
		def, ok := val.(map[string]any)
		if !ok {
			continue
		}
		if isLiteralTrue(def["credential"]) {
			keys = append(keys, key)
			continue
		}
		if ui, ok := def["ui"].(map[string]any); ok && isLiteralTrue(ui["secret"]) {
			keys = append(keys, key)
		}
	}
	return keys, len(schema), nil
}

// isLiteralTrue reports whether a parsed def value is the literal `true`.
// Non-object values arrive as their trimmed raw text, so ordinary authoring
// that decorates the literal must not read as false: a trailing line or block
// comment (`credential: true // yes`) and a `as const` assertion are both
// stripped before comparing. Anything else — a helper call, a variable, a
// computed expression — is deliberately NOT treated as true, since the
// generator cannot evaluate it.
func isLiteralTrue(v any) bool {
	s, ok := v.(string)
	if !ok {
		return false
	}
	if i := strings.Index(s, "//"); i >= 0 {
		s = s[:i]
	}
	for {
		i := strings.Index(s, "/*")
		if i < 0 {
			break
		}
		j := strings.Index(s[i+2:], "*/")
		if j < 0 {
			s = s[:i]
			break
		}
		s = s[:i] + s[i+2+j+2:]
	}
	s = strings.TrimSpace(s)
	s = strings.TrimSuffix(s, "const")
	s = strings.TrimSpace(strings.TrimSuffix(strings.TrimSpace(s), "as"))
	return s == "true"
}

// jsParser is a minimal structural parser over a JS/TS source string. It reads
// object literals into map[string]any (nested objects → maps; every other value
// → its trimmed raw text, so a scalar `true` compares equal to the string
// "true"), skipping arrays and arbitrary expressions with balanced bracket,
// string, template, and comment handling. It is not a full JS parser — only
// enough to walk SETTINGS_SCHEMA's shape.
type jsParser struct {
	s string
	i int
}

// seekSchema advances past `SETTINGS_SCHEMA` and its `=` to the opening `{` of
// the schema object literal, leaving the cursor on that brace.
func (p *jsParser) seekSchema() error {
	idx := strings.Index(p.s, "SETTINGS_SCHEMA")
	if idx < 0 {
		return fmt.Errorf("SETTINGS_SCHEMA not found")
	}
	p.i = idx + len("SETTINGS_SCHEMA")
	p.skipTrivia()
	if p.i >= len(p.s) || p.s[p.i] != '=' {
		return fmt.Errorf("expected '=' after SETTINGS_SCHEMA")
	}
	p.i++
	p.skipTrivia()
	if p.i >= len(p.s) || p.s[p.i] != '{' {
		return fmt.Errorf("expected '{' opening SETTINGS_SCHEMA")
	}
	return nil
}

// parseObject parses `{ key: value, ... }` starting at the current `{`,
// returning key → value (nested object as map[string]any, else raw text).
func (p *jsParser) parseObject() (map[string]any, error) {
	if p.i >= len(p.s) || p.s[p.i] != '{' {
		return nil, fmt.Errorf("parseObject: expected '{' at offset %d", p.i)
	}
	p.i++ // consume '{'
	obj := map[string]any{}
	for {
		p.skipTrivia()
		if p.i >= len(p.s) {
			return nil, fmt.Errorf("parseObject: unterminated object")
		}
		if p.s[p.i] == '}' {
			p.i++
			return obj, nil
		}
		key, err := p.parseKey()
		if err != nil {
			return nil, err
		}
		p.skipTrivia()
		if p.i >= len(p.s) || p.s[p.i] != ':' {
			return nil, fmt.Errorf("parseObject: expected ':' after key %q", key)
		}
		p.i++ // consume ':'
		val, err := p.parseValue()
		if err != nil {
			return nil, err
		}
		obj[key] = val
		p.skipTrivia()
		if p.i < len(p.s) && p.s[p.i] == ',' {
			p.i++
		}
	}
}

// parseKey reads a property name: a quoted string or a bare identifier.
func (p *jsParser) parseKey() (string, error) {
	p.skipTrivia()
	if p.i >= len(p.s) {
		return "", fmt.Errorf("parseKey: unexpected EOF")
	}
	c := p.s[p.i]
	if c == '"' || c == '\'' || c == '`' {
		return p.parseStringLiteral()
	}
	start := p.i
	for p.i < len(p.s) {
		c := p.s[p.i]
		if (c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') || c == '_' || c == '$' {
			p.i++
			continue
		}
		break
	}
	if p.i == start {
		return "", fmt.Errorf("parseKey: no identifier at offset %d", start)
	}
	return p.s[start:p.i], nil
}

// parseValue returns a nested map for an object value, or the trimmed raw text
// for any other value (array, scalar, or expression), consuming a balanced span
// up to the next top-level ',' or '}'.
func (p *jsParser) parseValue() (any, error) {
	p.skipTrivia()
	if p.i >= len(p.s) {
		return nil, fmt.Errorf("parseValue: unexpected EOF")
	}
	if p.s[p.i] == '{' {
		obj, err := p.parseObject()
		if err != nil {
			return nil, err
		}
		// A nested object value may be followed by a type cast (e.g. `} as
		// const`); consume and discard it so the enclosing object parse resumes
		// on the next top-level ',' or '}'.
		p.skipTrivia()
		if p.i < len(p.s) && p.s[p.i] != ',' && p.s[p.i] != '}' {
			if _, err := p.parseRawExpr(); err != nil {
				return nil, err
			}
		}
		return obj, nil
	}
	return p.parseRawExpr()
}

// parseRawExpr consumes a value expression up to (not including) the next
// top-level ',' or '}', respecting nested (), [], {}, strings, templates, and
// comments. Returns the trimmed raw text.
func (p *jsParser) parseRawExpr() (string, error) {
	start := p.i
	depth := 0
	angle := 0
	for p.i < len(p.s) {
		c := p.s[p.i]
		switch c {
		case '/':
			if p.i+1 < len(p.s) && (p.s[p.i+1] == '/' || p.s[p.i+1] == '*') {
				p.skipComment()
				continue
			}
			p.i++
		case '"', '\'', '`':
			if _, err := p.parseStringLiteral(); err != nil {
				return "", err
			}
		case '(', '[', '{':
			depth++
			p.i++
		case ')', ']', '}':
			if depth == 0 {
				return strings.TrimSpace(p.s[start:p.i]), nil
			}
			depth--
			p.i++
		case '<':
			// A generic type-argument list in a cast (e.g. `Record<string,
			// unknown>`) carries top-level commas that are NOT value
			// separators; track angle depth so they are skipped.
			angle++
			p.i++
		case '>':
			if angle > 0 {
				angle--
			}
			p.i++
		case ',':
			if depth == 0 && angle == 0 {
				return strings.TrimSpace(p.s[start:p.i]), nil
			}
			p.i++
		default:
			p.i++
		}
	}
	return strings.TrimSpace(p.s[start:p.i]), nil
}

// parseStringLiteral consumes a '...' , "..." , or `...` string starting at the
// current quote, handling escapes and (for templates) ${ } interpolation with
// balanced braces. Returns the unescaped-raw inner text for a simple string;
// for templates the raw inner text (interpolation left as-is) — callers only
// use it for keys, which are never templates.
func (p *jsParser) parseStringLiteral() (string, error) {
	quote := p.s[p.i]
	p.i++ // consume opening quote
	start := p.i
	for p.i < len(p.s) {
		c := p.s[p.i]
		if c == '\\' {
			p.i += 2
			continue
		}
		if quote == '`' && c == '$' && p.i+1 < len(p.s) && p.s[p.i+1] == '{' {
			p.i += 2
			braces := 1
			for p.i < len(p.s) && braces > 0 {
				switch p.s[p.i] {
				case '{':
					braces++
				case '}':
					braces--
				}
				p.i++
			}
			continue
		}
		if c == quote {
			inner := p.s[start:p.i]
			p.i++ // consume closing quote
			return inner, nil
		}
		p.i++
	}
	return "", fmt.Errorf("parseStringLiteral: unterminated string")
}

// skipTrivia skips whitespace and comments.
func (p *jsParser) skipTrivia() {
	for p.i < len(p.s) {
		c := p.s[p.i]
		if c == ' ' || c == '\t' || c == '\n' || c == '\r' {
			p.i++
			continue
		}
		if c == '/' && p.i+1 < len(p.s) && (p.s[p.i+1] == '/' || p.s[p.i+1] == '*') {
			p.skipComment()
			continue
		}
		break
	}
}

// skipComment skips a // line or /* block */ comment starting at the current
// '/'. The caller guarantees the two-char opener.
func (p *jsParser) skipComment() {
	if p.s[p.i+1] == '/' {
		p.i += 2
		for p.i < len(p.s) && p.s[p.i] != '\n' {
			p.i++
		}
		return
	}
	p.i += 2
	for p.i < len(p.s) {
		if p.s[p.i] == '*' && p.i+1 < len(p.s) && p.s[p.i+1] == '/' {
			p.i += 2
			return
		}
		p.i++
	}
}
