// @ts-check

import starlight from "@astrojs/starlight";
import { defineConfig } from "astro/config";
import { sidebar } from "./src/sidebar.generated.ts";

// Public engineering docsite (SEA-1763). Renders the compass monorepo's
// reviewed markdown — the docs/ tree gathered into src/content/docs/ by
// scripts/gather.ts — to a public Cloudflare Pages site. Unlike sealed's
// internal docsite this is PUBLIC: no Cloudflare Access gate and no PostHog
// analytics. Shares the Sealed brand (IBM Plex + paper-tone palette +
// color-bar accent) via src/styles/custom.css.
//
// Sidebar is generated by scripts/gather.ts (src/sidebar.generated.ts) — one
// group per populated nav section across the monorepo.
export default defineConfig({
	// Placeholder until the domain lands (eng.compass.rigel.build). Q4 ruling.
	site: "https://compass-eng-docs.pages.dev",
	trailingSlash: "ignore",
	integrations: [
		starlight({
			title: "Compass Engineering Docs",
			description: "Compass — public engineering docs.",
			customCss: ["./src/styles/custom.css"],
			// One dark Shiki theme for both site modes so token colors are
			// always designed for the dark terminal-feel background the code
			// blocks are painted on (set in custom.css).
			expressiveCode: {
				themes: ["tokyo-night"],
				useStarlightDarkModeSwitch: false,
				themeCssSelector: false,
			},
			tableOfContents: { minHeadingLevel: 2, maxHeadingLevel: 4 },
			pagefind: true,
			// Generated nav: one group per populated section. gather.ts classifies
			// every source into a section, mirrors it under src/content/docs/<section>/,
			// and emits the matching autogenerate groups here.
			sidebar,
			// Edit-on-GitHub per page, wired in T2. sealed's docsite leaves this
			// `{}` and its gather.ts injects a per-page `editUrl` frontmatter
			// pointing at each file's true canonical source. The T1 gather is a
			// stub that injects no per-page editUrl; a global `baseUrl` would only
			// resolve to the gitignored, gather-generated `src/content/docs/`
			// mirror (untracked → 404), so per the design record T1 ships no edit
			// link and T2 supplies the real per-page `editUrl`.
			editLink: {},
			lastUpdated: true,
		}),
	],
});
