// @ts-check

import starlight from "@astrojs/starlight";
import { defineConfig } from "astro/config";
import { sidebar } from "./src/sidebar.generated.ts";

// Public engineering docsite (RIG-1763). Renders the compass monorepo's
// reviewed markdown — the docs/ tree gathered into src/content/docs/ by
// scripts/gather.ts — to a public Cloudflare Pages site. This is PUBLIC: no
// auth gate and no analytics. Shares the Rigel brand (Night Owl
// palette + Space/Departure Mono type) with the Compass product surface via
// src/styles/fonts.css + src/styles/custom.css.
//
// Sidebar is generated by scripts/gather.ts (src/sidebar.generated.ts) — one
// group per populated nav section across the monorepo.
export default defineConfig({
	// Placeholder until the domain lands (eng.compass.rigel.build). Q4 ruling.
	site: "https://compass-eng-docs.pages.dev",
	trailingSlash: "ignore",
	integrations: [
		starlight({
			title: "Compass Engineering Docs",
			description: "Compass — public engineering docs.",
			customCss: ["./src/styles/fonts.css", "./src/styles/custom.css"],
			// One dark Shiki theme: night-owl, so code token colors are drawn
			// from the same Night Owl palette the rest of the surface uses
			// (set in custom.css).
			expressiveCode: {
				themes: ["night-owl"],
				useStarlightDarkModeSwitch: false,
				themeCssSelector: false,
			},
			tableOfContents: { minHeadingLevel: 2, maxHeadingLevel: 4 },
			pagefind: true,
			// Generated nav: one group per populated section. gather.ts classifies
			// every source into a section, mirrors it under src/content/docs/<section>/,
			// and emits the matching autogenerate groups here.
			sidebar,
			// Edit-on-GitHub per page, wired in T2. The internal docsite leaves this
			// `{}` and its gather.ts injects a per-page `editUrl` frontmatter
			// pointing at each file's true canonical source. The T1 gather is a
			// stub that injects no per-page editUrl; a global `baseUrl` would only
			// resolve to the gitignored, gather-generated `src/content/docs/`
			// mirror (untracked → 404), so per the design record T1 ships no edit
			// link and T2 supplies the real per-page `editUrl`.
			editLink: {},
			lastUpdated: true,
		}),
	],
});
