//go:build linux

package guestd

import (
	"errors"
	"fmt"
	"net"
	"strings"

	"github.com/insomniacslk/dhcp/dhcpv4"
)

// netConfig is the network state guestd applies to the guest, derived from a
// DHCP lease. It is deliberately separate from the socket I/O so the derivation
// (leaseToConfig) is unit-testable against a hand-built DHCPv4 ACK, per T2's
// test cycle — the real socket exchange is proven by T4.
type netConfig struct {
	// addr is the leased address with its prefix length (from YourIPAddr +
	// the subnet mask option), suitable for `netlink.ParseAddr`-style CIDR.
	addr net.IPNet
	// gateway is the default-route next hop (the first Router option), or nil
	// when the lease offers none.
	gateway net.IP
	// dns is the ordered nameserver list (the Domain Name Server option).
	dns []net.IP
	// searchDomains is the resolver search list: the DNS domain search option
	// when present, else the single Domain Name when present.
	searchDomains []string
}

// leaseToConfig derives the applied network configuration from a DHCP ACK. It is
// pure: no sockets, no netlink. The address plan is host-controlled (passt's
// launch flags decide what the lease offers, §(c)); guestd just applies what it
// is handed. A lease with no assigned address is a fail-closed error — there is
// nothing to bring up.
func leaseToConfig(ack *dhcpv4.DHCPv4) (netConfig, error) {
	if ack == nil {
		return netConfig{}, errors.New("dhcp ack is nil")
	}
	ip := ack.YourIPAddr
	if ip == nil || ip.IsUnspecified() {
		return netConfig{}, errors.New("dhcp ack carries no assigned address (yiaddr)")
	}
	ip4 := ip.To4()
	if ip4 == nil {
		return netConfig{}, fmt.Errorf("dhcp ack assigned address %s is not IPv4", ip)
	}

	// The subnet mask fixes the prefix length. passt always offers one (§(c));
	// absent or malformed, fall back to a /32 host route rather than guessing a
	// classful default. A /32 leaves a gateway outside the host route off-link,
	// so applyNetConfig's default route would fail-close (ENETUNREACH) — correct
	// for a spike where the mask is always present, and a loud failure beats a
	// wrong guessed prefix.
	mask := ack.SubnetMask()
	if len(mask) != net.IPv4len {
		mask = net.CIDRMask(32, 32)
	}
	cfg := netConfig{
		addr: net.IPNet{IP: ip4, Mask: mask},
		dns:  ack.DNS(),
	}
	if routers := ack.Router(); len(routers) > 0 {
		cfg.gateway = routers[0]
	}

	// Search list: prefer the explicit DNS domain search option when it carries
	// labels; fall back to the single Domain Name. A present-but-empty search
	// option must not shadow a usable Domain Name, so guard on content, not just
	// presence. Either can be absent.
	if search := ack.DomainSearch(); search != nil && len(search.Labels) > 0 {
		cfg.searchDomains = append(cfg.searchDomains, search.Labels...)
	} else if dn := ack.DomainName(); dn != "" {
		cfg.searchDomains = append(cfg.searchDomains, dn)
	}
	return cfg, nil
}

// renderResolvConf renders /etc/resolv.conf content from the lease DNS servers
// and optional search domains. It emits one `nameserver` line per server in
// order and a single `search` line when any search domains are present. The
// output always ends with a trailing newline; an empty server list yields a
// header-only file (a valid, if useless, resolv.conf) rather than an error —
// the caller decides whether no-DNS is fatal.
func renderResolvConf(dns []net.IP, search ...string) string {
	var b strings.Builder
	b.WriteString("# Generated by compass-guestd.\n")
	if len(search) > 0 {
		b.WriteString("search ")
		b.WriteString(strings.Join(search, " "))
		b.WriteString("\n")
	}
	for _, ns := range dns {
		b.WriteString("nameserver ")
		b.WriteString(ns.String())
		b.WriteString("\n")
	}
	return b.String()
}
