//go:build linux

package guestd

// Hermetic suite for the pure network-config helpers: renderResolvConf (lease
// DNS → /etc/resolv.conf text) and leaseToConfig (a DHCPv4 ACK → the applied
// addr/gw/dns/search). Both are the socket-free half of net bringup (§(d) step
// 2) — the socket exchange is T4's. leaseToConfig is driven against hand-built
// dhcpv4.DHCPv4 ACKs, no real DHCP server.

import (
	"net"
	"testing"

	"github.com/insomniacslk/dhcp/dhcpv4"
	"github.com/insomniacslk/dhcp/rfc1035label"
)

func TestRenderResolvConf(t *testing.T) {
	tests := []struct {
		name   string
		dns    []net.IP
		search []string
		want   string
	}{
		{
			name: "single nameserver, no search",
			dns:  []net.IP{net.ParseIP("10.0.2.3")},
			want: "# Generated by compass-guestd.\nnameserver 10.0.2.3\n",
		},
		{
			name:   "ordered nameservers with search",
			dns:    []net.IP{net.ParseIP("10.0.2.3"), net.ParseIP("10.0.2.4")},
			search: []string{"internal", "corp.example"},
			want:   "# Generated by compass-guestd.\nsearch internal corp.example\nnameserver 10.0.2.3\nnameserver 10.0.2.4\n",
		},
		{
			name: "no dns yields header-only file",
			want: "# Generated by compass-guestd.\n",
		},
		{
			name:   "search only, no dns",
			search: []string{"example.com"},
			want:   "# Generated by compass-guestd.\nsearch example.com\n",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := renderResolvConf(tt.dns, tt.search...)
			if got != tt.want {
				t.Fatalf("renderResolvConf(%v, %v) =\n%q\nwant\n%q", tt.dns, tt.search, got, tt.want)
			}
		})
	}
}

// buildACK constructs a DHCPv4 ACK with the given options, mirroring what passt's
// DHCP server offers. Modifiers set yiaddr, mask, router, DNS, and search.
func buildACK(t *testing.T, mods ...dhcpv4.Modifier) *dhcpv4.DHCPv4 {
	t.Helper()
	ack, err := dhcpv4.New(mods...)
	if err != nil {
		t.Fatalf("building ACK: %v", err)
	}
	return ack
}

func TestLeaseToConfig(t *testing.T) {
	t.Run("full lease derives addr, gateway, dns, and search", func(t *testing.T) {
		ack := buildACK(t,
			dhcpv4.WithYourIP(net.IPv4(192, 168, 10, 5)),
			dhcpv4.WithNetmask(net.CIDRMask(24, 32)),
			dhcpv4.WithRouter(net.IPv4(192, 168, 10, 1)),
			dhcpv4.WithDNS(net.IPv4(192, 168, 10, 53), net.IPv4(8, 8, 8, 8)),
			dhcpv4.WithDomainSearchList("internal.example"),
		)
		cfg, err := leaseToConfig(ack)
		if err != nil {
			t.Fatalf("leaseToConfig: %v", err)
		}
		if got := cfg.addr.String(); got != "192.168.10.5/24" {
			t.Fatalf("addr = %q, want 192.168.10.5/24", got)
		}
		if !cfg.gateway.Equal(net.IPv4(192, 168, 10, 1)) {
			t.Fatalf("gateway = %v, want 192.168.10.1", cfg.gateway)
		}
		if len(cfg.dns) != 2 || !cfg.dns[0].Equal(net.IPv4(192, 168, 10, 53)) || !cfg.dns[1].Equal(net.IPv4(8, 8, 8, 8)) {
			t.Fatalf("dns = %v, want [192.168.10.53 8.8.8.8] in order", cfg.dns)
		}
		if len(cfg.searchDomains) != 1 || cfg.searchDomains[0] != "internal.example" {
			t.Fatalf("searchDomains = %v, want [internal.example]", cfg.searchDomains)
		}
	})

	t.Run("domain name is fallback search when no search list", func(t *testing.T) {
		ack := buildACK(t,
			dhcpv4.WithYourIP(net.IPv4(10, 0, 0, 2)),
			dhcpv4.WithNetmask(net.CIDRMask(8, 32)),
			dhcpv4.WithOption(dhcpv4.OptDomainName("fallback.example")),
		)
		cfg, err := leaseToConfig(ack)
		if err != nil {
			t.Fatalf("leaseToConfig: %v", err)
		}
		if len(cfg.searchDomains) != 1 || cfg.searchDomains[0] != "fallback.example" {
			t.Fatalf("searchDomains = %v, want [fallback.example]", cfg.searchDomains)
		}
	})

	t.Run("explicit search list wins over domain name", func(t *testing.T) {
		ack := buildACK(t,
			dhcpv4.WithYourIP(net.IPv4(10, 0, 0, 2)),
			dhcpv4.WithNetmask(net.CIDRMask(24, 32)),
			dhcpv4.WithOption(dhcpv4.OptDomainName("domainname.example")),
			dhcpv4.WithOption(dhcpv4.OptDomainSearch(&rfc1035label.Labels{Labels: []string{"searchlist.example"}})),
		)
		cfg, err := leaseToConfig(ack)
		if err != nil {
			t.Fatalf("leaseToConfig: %v", err)
		}
		if len(cfg.searchDomains) != 1 || cfg.searchDomains[0] != "searchlist.example" {
			t.Fatalf("searchDomains = %v, want [searchlist.example]", cfg.searchDomains)
		}
	})

	t.Run("no gateway leaves gateway nil", func(t *testing.T) {
		ack := buildACK(t,
			dhcpv4.WithYourIP(net.IPv4(10, 0, 0, 2)),
			dhcpv4.WithNetmask(net.CIDRMask(24, 32)),
		)
		cfg, err := leaseToConfig(ack)
		if err != nil {
			t.Fatalf("leaseToConfig: %v", err)
		}
		if cfg.gateway != nil {
			t.Fatalf("gateway = %v, want nil", cfg.gateway)
		}
	})

	t.Run("missing subnet mask falls back to /32", func(t *testing.T) {
		ack := buildACK(t, dhcpv4.WithYourIP(net.IPv4(10, 0, 0, 2)))
		cfg, err := leaseToConfig(ack)
		if err != nil {
			t.Fatalf("leaseToConfig: %v", err)
		}
		if got := cfg.addr.String(); got != "10.0.0.2/32" {
			t.Fatalf("addr = %q, want 10.0.0.2/32", got)
		}
	})

	t.Run("nil ack is fail-closed", func(t *testing.T) {
		if _, err := leaseToConfig(nil); err == nil {
			t.Fatal("leaseToConfig(nil) = nil error, want fail-closed error")
		}
	})

	t.Run("lease with no assigned address is fail-closed", func(t *testing.T) {
		ack := buildACK(t, dhcpv4.WithNetmask(net.CIDRMask(24, 32)))
		if _, err := leaseToConfig(ack); err == nil {
			t.Fatal("leaseToConfig(no yiaddr) = nil error, want fail-closed error")
		}
	})
}
