// orion-ref-gate (RIG-2489) — fail-closed CI check that the PUBLIC repo
// RigelBuild/compass carries no reference to the PRIVATE internal monorepo
// (RigelBuild/orion).
//
// The compass repo is public, and its docs/ tree is rendered to a public,
// no-auth docsite (apps/eng-docs → compass-eng-docs.pages.dev). A reference to
// the private monorepo — its name, a path inside it, one of its PR numbers, or
// a quoted snippet of its source — is a private-information leak. A one-time
// sweep removed the existing references; this gate keeps the boundary from
// silently re-rotting, the same way design-ledger-gate keeps the ledger honest.
//
// SCOPE: orion ONLY. This gate scans for one token and does not double as a
// general brand-token gate; other one-time cleanups that are not being re-added
// need no standing scan here.
//
// What counts as a reference: the whole-word token `orion` (any case), which
// catches the repo name, `RigelBuild/orion`, an `orion <path>` citation, and
// "ported from orion" provenance prose alike. The scan is deliberately blunt —
// a single blunt token with a small, explicit allowlist beats a clever regex
// that tries to tell a "good" orion from a "bad" one.
//
// CARVE-OUTS (never scanned):
//   - forks/**            vendored upstream subtrees; byte-identity is their
//                         verification basis, and any `orion` there is upstream
//                         text, not a compass-authored reference. (First-party
//                         forks/README.md is NOT carved out — it is compass
//                         prose.)
//   - tools/orion-ref-gate/**  this gate's own source + fixtures name the token
//                         to describe what it forbids.
//   - apps/eng-docs/src/content/docs/**, apps/eng-docs/dist/**  generated
//                         copies of docs/ (gitignored; regenerated by
//                         gather.ts). The canonical source under docs/ is what
//                         the gate governs.
//   - an explicit ALLOWLIST of exact repo-relative paths, each with a reason,
//                         for a genuine non-private-repo use (e.g. an English
//                         word or a constellation name). Empty today.
//
// The scan reads tracked files via `git grep`, so untracked build output and
// node_modules (where "Orion" appears as a constellation in vendored model
// data) are never considered.
//
// Exit codes:
//   0 - no references (clean)
//   1 - one or more references (printed one per line as `<file>:<line>: <text>`)
//   2 - usage / internal error (e.g. not a git tree)
//
// Usage: bun run tools/orion-ref-gate/index.ts

import { $ } from "bun";

/** The private monorepo's token. Whole-word, case-insensitive. */
export const PRIVATE_TOKEN = "orion";

/**
 * Repo-relative path prefixes never scanned. A reference under one of these is
 * either upstream text (forks/), a generated copy (eng-docs / bun.lock), or
 * this gate's own description of what it forbids.
 */
export const CARVEOUT_PREFIXES: readonly string[] = [
	"forks/",
	"tools/orion-ref-gate/",
	"apps/eng-docs/src/content/docs/",
	"apps/eng-docs/dist/",
];

/**
 * Exact repo-relative paths never scanned — generated files that mechanically
 * carry a package/project name (which itself contains this gate's own name).
 */
export const CARVEOUT_PATHS: readonly string[] = ["bun.lock"];

/**
 * Exact repo-relative paths exempted with a reason — for a genuine
 * non-private-repo use of the token (an English word, a constellation name).
 * Empty today: every tracked use of `orion` in compass is the private repo.
 * Add a path here ONLY with a one-line reason, and prefer rewording the text.
 */
export const ALLOWLIST: Readonly<Record<string, string>> = {};

/** One scanned line carrying the token. */
export interface Reference {
	readonly file: string;
	readonly line: number;
	readonly text: string;
}

/** True when a repo-relative path is carved out of the scan. */
export function isCarveOut(path: string): boolean {
	if (path in ALLOWLIST) return true;
	// forks/README.md is first-party compass prose, not a vendored subtree —
	// it is scanned like any other authored file.
	if (path === "forks/README.md") return false;
	if (CARVEOUT_PATHS.includes(path)) return true;
	return CARVEOUT_PREFIXES.some((prefix) => path.startsWith(prefix));
}

/**
 * Whole-word, case-insensitive match for the private token in one line. The
 * gate's own compound name (`orion-ref-gate`) is not a private-repo reference,
 * so a bare `orion` immediately followed by `-ref-gate` does not count.
 */
export function lineHasToken(text: string): boolean {
	const stripped = text.replace(/orion-ref-gate/gi, "");
	return new RegExp(`\\b${PRIVATE_TOKEN}\\b`, "i").test(stripped);
}

/**
 * The pure gate decision: given `git grep -n` style hits (each `file:line:text`)
 * return the references that are NOT carved out. Pure — the caller supplies the
 * raw hits, so tests drive it over fixtures with no git.
 */
export function findViolations(grepHits: readonly string[]): Reference[] {
	const out: Reference[] = [];
	for (const hit of grepHits) {
		const trimmed = hit.trimEnd();
		if (trimmed.length === 0) continue;
		// `git grep -n` emits `path:line:text`; text may itself contain colons.
		const firstColon = trimmed.indexOf(":");
		const secondColon = trimmed.indexOf(":", firstColon + 1);
		if (firstColon < 0 || secondColon < 0) continue;
		const file = trimmed.slice(0, firstColon);
		const line = Number(trimmed.slice(firstColon + 1, secondColon));
		const text = trimmed.slice(secondColon + 1);
		if (!Number.isInteger(line)) continue;
		if (isCarveOut(file)) continue;
		if (!lineHasToken(text)) continue;
		out.push({ file, line, text });
	}
	return out;
}

/** Injected I/O, so the runner is testable without a real git tree. */
export interface Deps {
	/** Return `git grep -n` hits for the whole-word token across tracked files. */
	grep: () => Promise<string[]>;
	log: (msg: string) => void;
	err: (msg: string) => void;
}

export async function runOnce(deps: Deps): Promise<number> {
	let hits: string[];
	try {
		hits = await deps.grep();
	} catch (e) {
		deps.err(`orion-ref-gate: cannot scan the tree: ${String(e)}`);
		return 2;
	}
	const violations = findViolations(hits);
	if (violations.length > 0) {
		deps.err(
			`orion-ref-gate: ${violations.length} reference(s) to the private monorepo in the public repo:`,
		);
		for (const v of violations)
			deps.err(`  ${v.file}:${v.line}: ${v.text.trim()}`);
		deps.err(
			"A public repo must not name, cite, or quote the private internal monorepo. " +
				'Refer to it by architectural role instead — say "the managed service", or ' +
				"describe the core capability directly so it need not be named. " +
				"See docs/concepts/self-host-and-managed.md.",
		);
		return 1;
	}
	deps.log("orion-ref-gate: clean — no private-monorepo references.");
	return 0;
}

/**
 * `git grep -nwI -i <token>` over tracked files. `git grep` exits 0 with
 * matches, 1 on no match (a legitimately clean, empty result), and >=2 on a
 * real error (e.g. not a git work tree). We must distinguish the last from the
 * clean case: swallowing it would make the gate report clean on a broken scan —
 * fail-OPEN, the exact false-green a fail-closed gate exists to stop. Exit >=2
 * throws, so runOnce's catch returns exit 2.
 */
async function gitGrep(): Promise<string[]> {
	const res = await $`git grep -nwiI ${PRIVATE_TOKEN}`.nothrow().quiet();
	if (res.exitCode >= 2)
		throw new Error(
			`git grep exited ${res.exitCode}: ${res.stderr.toString().trim()}`,
		);
	return res.stdout
		.toString()
		.split("\n")
		.filter((l) => l.length > 0);
}

if (import.meta.main) {
	const code = await runOnce({
		grep: gitGrep,
		log: (m) => console.log(m),
		err: (m) => console.error(m),
	});
	process.exit(code);
}
