/**
 * The generator-stamp gate (SEA-1405).
 *
 * `protoc-gen-es` comes from the pinned nixpkgs (devenv.nix), so its version is
 * the nixpkgs's to choose and there is no lockfile pin to compare against. What
 * DOES record which generator produced the checked-in code is the
 * `// @generated by protoc-gen-es v<version>` header every file in the gen
 * trees carries.
 *
 * This gate asserts those stamps agree with each other AND with the plugin on
 * PATH. A `devenv.lock` bump that moves the plugin surfaces as a named skew
 * ("baked X != gen-tree stamp Y"), and a partial regeneration — the two TS gen
 * trees are produced by separate `buf generate` invocations, so one can restamp
 * while the other lags — surfaces as a named intra-tree disagreement.
 *
 * `compass-proto:drift` catches the OUTCOME of both, but reports it as a
 * comment-only diff on a PR that touched neither the schema nor the gen trees.
 * This gate names the cause, so the fix reads as `moon run compass-proto:gen`
 * rather than as a mystery red.
 *
 * Pure: the command runner and the generated source texts are injected, so the
 * whole decision is unit-testable without a filesystem or a plugin.
 */

/** Spawns a command and returns its captured output. Injected for testability. */
export type CommandRunner = (
	argv: string[],
) => Promise<{ code: number; stdout: string; stderr: string }>;

/** A checked-in generated file: its repo-relative path and its full text. */
export interface StampSource {
	path: string;
	text: string;
}

export interface GateResult {
	pass: boolean;
	/** One line, suitable as a summary. */
	detail: string;
	/** Multi-line remediation context. Empty on pass. */
	output: string;
}

/**
 * The plugin's own banner line. Anchored on `protoc-gen-es` so a wrapper line
 * carrying an unrelated semver cannot shadow the real version.
 */
const BANNER = /protoc-gen-es v(\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.+-]+)?)/;

/** The header protoc-gen-es writes at the top of every file it generates. */
const STAMP =
	/@generated by protoc-gen-es v(\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.+-]+)?)/;

const VERSION_ARGV = ["protoc-gen-es", "--version"];

const REGEN =
	"Fix: run `moon run compass-proto:gen` and commit the restamped generated trees.";

export async function assertGeneratorStamp(
	run: CommandRunner,
	sources: StampSource[],
): Promise<GateResult> {
	// An empty source set fails closed. A glob that matches nothing would
	// otherwise make the gate vacuously green — passing by never looking, which
	// is indistinguishable from passing by agreeing.
	if (sources.length === 0) {
		return {
			pass: false,
			detail: "no generated sources to check",
			output:
				"no generated `_pb.ts` sources were found, so there is no `@generated by protoc-gen-es v<version>` stamp to compare against the plugin on PATH. Either the glob is wrong or the gen trees are missing.",
		};
	}

	const stamps: Array<{ path: string; version: string }> = [];
	for (const source of sources) {
		const version = source.text.match(STAMP)?.[1];
		if (version === undefined) {
			return {
				pass: false,
				detail: "gen-tree stamp unreadable",
				output: `no \`// @generated by protoc-gen-es v<version>\` header in ${source.path}`,
			};
		}
		stamps.push({ path: source.path, version });
	}

	const first = stamps[0] as { path: string; version: string };
	const other = stamps.find((s) => s.version !== first.version);
	if (other !== undefined) {
		return {
			pass: false,
			detail: `gen-tree stamps disagree: ${first.version} (${first.path}) vs ${other.version} (${other.path})`,
			output: `the checked-in generated trees are stamped by more than one protoc-gen-es version, the likely cause of which is a partial regeneration — the trees come from three separate \`buf generate\` invocations. ${REGEN}`,
		};
	}
	const stamped = first.version;

	const r = await run(VERSION_ARGV);
	// protoc-gen-es exits 0 and prints its banner when healthy, so the exit code
	// is load-bearing: fail closed BEFORE parsing rather than trust the banner of
	// a dying plugin. A banner-then-die wrapper (wrong arch, missing interpreter)
	// must not grade as a working plugin.
	if (r.code !== 0) {
		return {
			pass: false,
			detail: `\`${VERSION_ARGV.join(" ")}\` exited ${r.code}`,
			output: `${r.stdout}\n${r.stderr}`.trim(),
		};
	}

	const actual = r.stdout.match(BANNER)?.[1];
	if (actual === undefined) {
		return {
			pass: false,
			detail: `no version in \`${VERSION_ARGV.join(" ")}\` output`,
			output: `${r.stdout}\n${r.stderr}`.trim(),
		};
	}

	if (actual !== stamped) {
		return {
			pass: false,
			detail: `baked ${actual} != gen-tree stamp ${stamped}`,
			output: `the plugin on PATH (${actual}) and the checked-in generated code (stamped ${stamped}) disagree: regenerating would rewrite every generated file's header. ${REGEN}`,
		};
	}

	return {
		pass: true,
		detail: `${actual} == gen-tree stamp (${sources.length} files)`,
		output: "",
	};
}

/**
 * Maps a gate result to a process exit code, emitting the summary and any
 * remediation context. The single line that makes the gate fail-closed at the
 * process boundary; extracted from the I/O shell so an accidental inversion of
 * the exit mapping reds a unit test rather than only the integration check.
 */
export function report(result: GateResult): number {
	if (!result.pass) {
		console.error(`protoc-gen-es-stamp: ${result.detail}`);
		if (result.output) console.error(result.output);
		return 1;
	}
	console.log(`protoc-gen-es-stamp ok: ${result.detail}`);
	return 0;
}
