import { describe, expect, test } from "bun:test";
import {
	assertGeneratorStamp,
	type CommandRunner,
	type StampSource,
} from "./stamp-gate";

/** A runner that reports a healthy plugin at `version`. */
const healthy = (version: string): CommandRunner => {
	return async () => ({
		code: 0,
		stdout: `protoc-gen-es v${version}\n`,
		stderr: "",
	});
};

const stamped = (path: string, version: string): StampSource => ({
	path,
	text: `// @generated by protoc-gen-es v${version} with parameter "target=ts"\n\nexport const X = 1;\n`,
});

describe("assertGeneratorStamp", () => {
	test("passes when every stamp agrees with the plugin on PATH", async () => {
		const r = await assertGeneratorStamp(healthy("2.12.0"), [
			stamped(
				"packages/compass-agent/src/gen/compass/v1/agent_pb.ts",
				"2.12.0",
			),
			stamped(
				"packages/compass-client/src/gen/compass/v1/compass_pb.ts",
				"2.12.0",
			),
		]);
		expect(r.pass).toBe(true);
		expect(r.detail).toContain("2.12.0");
		// The count is part of the pass line: a green over one file and a green
		// over forty are different claims, and the gate should not render them
		// identically.
		expect(r.detail).toContain("2 files");
	});

	// FAIL-CLOSED 1. A glob that matches nothing must not grade as agreement.
	// This is the whole reason the gate cannot be a `grep | uniq` one-liner:
	// an empty pipeline is silent, and silence reads as consensus.
	test("fails closed on an empty source set", async () => {
		const r = await assertGeneratorStamp(healthy("2.12.0"), []);
		expect(r.pass).toBe(false);
		expect(r.detail).toBe("no generated sources to check");
	});

	// FAIL-CLOSED 2. protoc-gen-es exits 0 and prints its banner when healthy,
	// so a wrapper that prints a plausible banner and then dies would otherwise
	// be parsed as a working plugin. The exit code is checked BEFORE the banner.
	test("fails closed on a non-zero plugin exit even when the banner parses", async () => {
		const bannerThenDie: CommandRunner = async () => ({
			code: 127,
			stdout: "protoc-gen-es v2.12.0\n",
			stderr: "error while loading shared libraries",
		});
		const r = await assertGeneratorStamp(bannerThenDie, [
			stamped(
				"packages/compass-client/src/gen/compass/v1/compass_pb.ts",
				"2.12.0",
			),
		]);
		expect(r.pass).toBe(false);
		expect(r.detail).toContain("exited 127");
	});

	test("names both sides of an intra-tree stamp disagreement", async () => {
		const r = await assertGeneratorStamp(healthy("2.12.0"), [
			stamped(
				"packages/compass-agent/src/gen/compass/v1/agent_pb.ts",
				"2.12.0",
			),
			stamped(
				"packages/compass-client/src/gen/compass/v1/compass_pb.ts",
				"2.12.1",
			),
		]);
		expect(r.pass).toBe(false);
		// Both versions AND both paths: the reader has to know which tree lagged,
		// not merely that something disagreed.
		expect(r.detail).toContain("2.12.0");
		expect(r.detail).toContain("2.12.1");
		expect(r.detail).toContain("agent_pb.ts");
		expect(r.detail).toContain("compass_pb.ts");
	});

	test("names the skew when the plugin moves under an unchanged tree", async () => {
		const r = await assertGeneratorStamp(healthy("2.13.0"), [
			stamped(
				"packages/compass-client/src/gen/compass/v1/compass_pb.ts",
				"2.12.0",
			),
		]);
		expect(r.pass).toBe(false);
		expect(r.detail).toBe("baked 2.13.0 != gen-tree stamp 2.12.0");
		expect(r.output).toContain("compass-proto:gen");
	});

	test("fails when a generated file carries no stamp at all", async () => {
		const r = await assertGeneratorStamp(healthy("2.12.0"), [
			{
				path: "packages/compass-client/src/gen/compass/v1/compass_pb.ts",
				text: "export const X = 1;\n",
			},
		]);
		expect(r.pass).toBe(false);
		expect(r.detail).toBe("gen-tree stamp unreadable");
		expect(r.output).toContain("compass_pb.ts");
	});

	test("fails when the plugin exits 0 but prints no recognisable version", async () => {
		const silent: CommandRunner = async () => ({
			code: 0,
			stdout: "\n",
			stderr: "",
		});
		const r = await assertGeneratorStamp(silent, [
			stamped(
				"packages/compass-client/src/gen/compass/v1/compass_pb.ts",
				"2.12.0",
			),
		]);
		expect(r.pass).toBe(false);
		expect(r.detail).toContain("no version in");
	});

	// The banner regex is anchored on the plugin's own name so an unrelated
	// semver printed alongside it cannot shadow the real one. Without the
	// anchor a wrapper's own version wins and the gate compares the wrong pair
	// — passing or failing for a reason that has nothing to do with the plugin.
	test("reads the plugin's own version, not a bystander semver on the same output", async () => {
		const noisy: CommandRunner = async () => ({
			code: 0,
			stdout: "wrapper v9.9.9\nprotoc-gen-es v2.12.0\n",
			stderr: "",
		});
		const r = await assertGeneratorStamp(noisy, [
			stamped(
				"packages/compass-client/src/gen/compass/v1/compass_pb.ts",
				"2.12.0",
			),
		]);
		expect(r.pass).toBe(true);
	});

	// Prerelease and build metadata are legal semver and nixpkgs does ship them.
	// A regex accepting only `x.y.z` would report "no version in output" for a
	// perfectly healthy plugin — a false red, which costs more than a false
	// green because a closed door does not get re-tested.
	test("accepts a prerelease version on both sides", async () => {
		const r = await assertGeneratorStamp(healthy("2.13.0-rc.1"), [
			stamped(
				"packages/compass-client/src/gen/compass/v1/compass_pb.ts",
				"2.13.0-rc.1",
			),
		]);
		expect(r.pass).toBe(true);
	});
});
