// T1 placeholder (SEA-1763) — replaced by the real corpus gather in T2 (SEA-1764).
//
// The real gather mirrors the compass monorepo's reviewed markdown into the
// gitignored src/content/docs/ tree and emits src/sidebar.generated.ts, exactly
// as sealed/apps/docs/scripts/gather.ts does. That port (compass taxonomy,
// link rewriting, frontmatter injection) is T2's scope, not T1's.
//
// For the scaffold, this stub writes only what a green `astro build` / `astro
// check` needs on an EMPTY corpus:
//   - a single placeholder index page, so Starlight's `docs` content collection
//     is non-empty (Starlight errors on an empty collection), and
//   - an empty `src/sidebar.generated.ts` exporting `sidebar = []`, which
//     astro.config.mjs imports.
// It maps NO real docs. When T2 lands the real gather, delete this file's body
// and port the sealed implementation.

import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

async function main(): Promise<void> {
	// apps/eng-docs/scripts/gather.ts → app root is one level up.
	const scriptDir = dirname(fileURLToPath(import.meta.url));
	const appDir = dirname(scriptDir);
	const contentRoot = join(appDir, "src", "content", "docs");

	await mkdir(contentRoot, { recursive: true });

	// Placeholder root landing page so the collection is non-empty and `/` has a
	// route. Replaced by the real generated index + section pages in T2.
	await writeFile(
		join(contentRoot, "index.md"),
		"---\n" +
			'title: "Compass Engineering Docs"\n' +
			'description: "Public engineering docs for the compass monorepo."\n' +
			"template: splash\n" +
			"---\n\n" +
			"Scaffold placeholder — the reviewed documentation corpus is gathered here\n" +
			"in T2 (SEA-1764).\n",
	);

	// Empty sidebar (no populated sections yet); astro.config.mjs imports this.
	await writeFile(
		join(appDir, "src", "sidebar.generated.ts"),
		"// Generated by scripts/gather.ts — do not edit.\n" +
			"// T1 placeholder (SEA-1763): empty until the real corpus gather lands in T2.\n" +
			"export const sidebar = [];\n",
	);

	console.log(
		`gather (T1 stub): wrote placeholder index + empty sidebar into ${contentRoot}`,
	);
}

if (import.meta.main) {
	await main();
}
