-- 0005_agent_persona: the agent's system-prompt text, baked at creation (SEA-1571).
-- persona is the agent's system-prompt override, its source-of-truth field on the
-- agent account (Matt-ruled: source = AgentAccount, not a wire field on provision).
-- Empty string means no persona override. It is read at provision time and
-- materialized to the container by the runner (a separate lane); this migration
-- is only the durable column + the store round-trip that carries it.
--
-- NOT NULL DEFAULT '' so every existing and future agent row always has a value:
-- a joined agent row reads the empty default rather than NULL, matching the
-- "empty = no override" contract and keeping the create/read path branch-free.
ALTER TABLE agent_accounts ADD COLUMN persona TEXT NOT NULL DEFAULT '';
