// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_activity.sql

package db

import (
	"context"
)

const activityFor = `-- name: ActivityFor :many
SELECT agent_account_id, activity, activity_at_unix_ms
FROM agent_activity
WHERE agent_account_id = ANY($1::text[])
`

func (q *Queries) ActivityFor(ctx context.Context, dollar_1 []string) ([]AgentActivity, error) {
	rows, err := q.db.Query(ctx, activityFor, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentActivity
	for rows.Next() {
		var i AgentActivity
		if err := rows.Scan(&i.AgentAccountID, &i.Activity, &i.ActivityAtUnixMs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setActivity = `-- name: SetActivity :exec

INSERT INTO agent_activity (agent_account_id, activity, activity_at_unix_ms)
VALUES ($1, $2, $3)
ON CONFLICT (agent_account_id)
DO UPDATE SET activity = EXCLUDED.activity,
              activity_at_unix_ms = EXCLUDED.activity_at_unix_ms
`

type SetActivityParams struct {
	AgentAccountID   string
	Activity         string
	ActivityAtUnixMs int64
}

// Agent-activity queries (sqlc adoption T5, RIG-3034). These replace the inline
// SQL literals in internal/store/agent_activity.go; the hand-written Store
// methods keep their signatures and map the ActivityFor rows into the
// AgentActivity domain struct (agentActivityFromRow-equivalent, done inline in
// the Go — absent-from-table means absent-from-map).
func (q *Queries) SetActivity(ctx context.Context, arg SetActivityParams) error {
	_, err := q.db.Exec(ctx, setActivity, arg.AgentAccountID, arg.Activity, arg.ActivityAtUnixMs)
	return err
}
