// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_config.sql

package db

import (
	"context"
)

const currentAgentConfig = `-- name: CurrentAgentConfig :one
SELECT version, bundle FROM agent_config_bundle WHERE singleton = TRUE
`

type CurrentAgentConfigRow struct {
	Version string
	Bundle  []byte
}

func (q *Queries) CurrentAgentConfig(ctx context.Context) (CurrentAgentConfigRow, error) {
	row := q.db.QueryRow(ctx, currentAgentConfig)
	var i CurrentAgentConfigRow
	err := row.Scan(&i.Version, &i.Bundle)
	return i, err
}

const deleteAgentConfig = `-- name: DeleteAgentConfig :exec
DELETE FROM agent_config_bundle WHERE singleton = TRUE
`

func (q *Queries) DeleteAgentConfig(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAgentConfig)
	return err
}

const putAgentConfig = `-- name: PutAgentConfig :exec

INSERT INTO agent_config_bundle (singleton, version, bundle)
VALUES (TRUE, $1, $2)
ON CONFLICT (singleton)
DO UPDATE SET version = EXCLUDED.version, bundle = EXCLUDED.bundle, updated_at = now()
`

type PutAgentConfigParams struct {
	Version string
	Bundle  []byte
}

// Agent config-bundle queries (sqlc adoption T5, RIG-3034). These replace the
// inline SQL literals in internal/store/agent_config.go; the hand-written Store
// methods keep their signatures and own the bundle validation/hash and the
// tar-walk member inventory (Go-side, over the returned BYTEA). The config
// bundle is a fleet-wide singleton row (singleton = TRUE).
func (q *Queries) PutAgentConfig(ctx context.Context, arg PutAgentConfigParams) error {
	_, err := q.db.Exec(ctx, putAgentConfig, arg.Version, arg.Bundle)
	return err
}
