// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_placements.sql

package db

import (
	"context"
)

const agentForContainer = `-- name: AgentForContainer :one
SELECT agent_account_id FROM agent_placements WHERE container_name = $1
`

func (q *Queries) AgentForContainer(ctx context.Context, containerName string) (string, error) {
	row := q.db.QueryRow(ctx, agentForContainer, containerName)
	var agent_account_id string
	err := row.Scan(&agent_account_id)
	return agent_account_id, err
}

const deleteAgentPlacement = `-- name: DeleteAgentPlacement :exec
DELETE FROM agent_placements WHERE container_name = $1
`

func (q *Queries) DeleteAgentPlacement(ctx context.Context, containerName string) error {
	_, err := q.db.Exec(ctx, deleteAgentPlacement, containerName)
	return err
}

const listAgentPlacementsForRunner = `-- name: ListAgentPlacementsForRunner :many
SELECT agent_account_id, runner_id, container_name
  FROM agent_placements
 WHERE runner_id = $1
 ORDER BY agent_account_id
`

type ListAgentPlacementsForRunnerRow struct {
	AgentAccountID string
	RunnerID       string
	ContainerName  string
}

func (q *Queries) ListAgentPlacementsForRunner(ctx context.Context, runnerID string) ([]ListAgentPlacementsForRunnerRow, error) {
	rows, err := q.db.Query(ctx, listAgentPlacementsForRunner, runnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentPlacementsForRunnerRow
	for rows.Next() {
		var i ListAgentPlacementsForRunnerRow
		if err := rows.Scan(&i.AgentAccountID, &i.RunnerID, &i.ContainerName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const placementForAgent = `-- name: PlacementForAgent :one
SELECT runner_id, container_name FROM agent_placements WHERE agent_account_id = $1
`

type PlacementForAgentRow struct {
	RunnerID      string
	ContainerName string
}

func (q *Queries) PlacementForAgent(ctx context.Context, agentAccountID string) (PlacementForAgentRow, error) {
	row := q.db.QueryRow(ctx, placementForAgent, agentAccountID)
	var i PlacementForAgentRow
	err := row.Scan(&i.RunnerID, &i.ContainerName)
	return i, err
}

const recordAgentPlacement = `-- name: RecordAgentPlacement :exec

INSERT INTO agent_placements (agent_account_id, runner_id, container_name)
VALUES ($1, $2, $3)
ON CONFLICT (agent_account_id) DO UPDATE
   SET runner_id      = EXCLUDED.runner_id,
       container_name = EXCLUDED.container_name,
       updated_at     = now()
`

type RecordAgentPlacementParams struct {
	AgentAccountID string
	RunnerID       string
	ContainerName  string
}

// Agent-placement queries (sqlc adoption T5, RIG-3034). These replace the inline
// SQL literals in internal/store/agent_placements.go; the hand-written Store
// methods keep their signatures and map the placement rows into the
// AgentPlacement domain struct (AccountID newtype done inline in the Go).
func (q *Queries) RecordAgentPlacement(ctx context.Context, arg RecordAgentPlacementParams) error {
	_, err := q.db.Exec(ctx, recordAgentPlacement, arg.AgentAccountID, arg.RunnerID, arg.ContainerName)
	return err
}
