// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_transcripts.sql

package db

import (
	"context"
)

const bindLifetime = `-- name: BindLifetime :one

UPDATE agent_sessions
   SET base_entry_seq = COALESCE(
           (SELECT MAX(te.entry_seq)
              FROM agent_session_transcript_entries te
             WHERE te.session_id = $1), 0)
 WHERE session_id = $1
RETURNING base_entry_seq
`

// Agent-transcript queries (sqlc adoption T5, RIG-3034). These replace the
// inline SQL literals in internal/store/agent_transcripts.go; the hand-written
// Store methods keep their exact signatures and own the two-tier flush
// orchestration (PUT-before-prune, the RepeatableRead/ReadOnly resume snapshot
// tx, the safety-valve cut-point loop) plus the uint64<->int64 seq narrowing
// (toInt64/toUint64). They map generated rows into TranscriptEntryRow and
// ArchiveSegmentRow (via the transcriptRowsFromDB/segmentRowsFromDB helpers).
//
// COALESCE(MAX/SUM(...), 0) sites carry an explicit ::BIGINT cast so sqlc types
// them int64 rather than interface{} (mirrors messages.sql MessagesHeadSeq). The
// SessionTranscript and SafetyValveSegments reads are each issued on BOTH the
// pool (the eponymous method) and a snapshot tx (SessionResumeSnapshot, via
// WithTx), so one generated query backs both call sites.
func (q *Queries) BindLifetime(ctx context.Context, sessionID string) (int64, error) {
	row := q.db.QueryRow(ctx, bindLifetime, sessionID)
	var base_entry_seq int64
	err := row.Scan(&base_entry_seq)
	return base_entry_seq, err
}

const collectSegment = `-- name: CollectSegment :many
SELECT entry_seq, entry_json
   FROM agent_session_transcript_entries
  WHERE session_id = $1 AND entry_seq >= $2 AND entry_seq <= $3
  ORDER BY entry_seq
`

type CollectSegmentParams struct {
	SessionID  string
	EntrySeq   int64
	EntrySeq_2 int64
}

type CollectSegmentRow struct {
	EntrySeq  int64
	EntryJson string
}

func (q *Queries) CollectSegment(ctx context.Context, arg CollectSegmentParams) ([]CollectSegmentRow, error) {
	rows, err := q.db.Query(ctx, collectSegment, arg.SessionID, arg.EntrySeq, arg.EntrySeq_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CollectSegmentRow
	for rows.Next() {
		var i CollectSegmentRow
		if err := rows.Scan(&i.EntrySeq, &i.EntryJson); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hotTailBytes = `-- name: HotTailBytes :one
SELECT COALESCE(SUM(octet_length(entry_json)), 0)::BIGINT AS bytes
   FROM agent_session_transcript_entries
  WHERE session_id = $1 AND entry_seq > $2
`

type HotTailBytesParams struct {
	SessionID string
	EntrySeq  int64
}

func (q *Queries) HotTailBytes(ctx context.Context, arg HotTailBytesParams) (int64, error) {
	row := q.db.QueryRow(ctx, hotTailBytes, arg.SessionID, arg.EntrySeq)
	var bytes int64
	err := row.Scan(&bytes)
	return bytes, err
}

const hotTailSizes = `-- name: HotTailSizes :many
SELECT entry_seq, octet_length(entry_json)::BIGINT AS bytes
   FROM agent_session_transcript_entries
  WHERE session_id = $1 AND entry_seq > $2
  ORDER BY entry_seq
`

type HotTailSizesParams struct {
	SessionID string
	EntrySeq  int64
}

type HotTailSizesRow struct {
	EntrySeq int64
	Bytes    int64
}

func (q *Queries) HotTailSizes(ctx context.Context, arg HotTailSizesParams) ([]HotTailSizesRow, error) {
	rows, err := q.db.Query(ctx, hotTailSizes, arg.SessionID, arg.EntrySeq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HotTailSizesRow
	for rows.Next() {
		var i HotTailSizesRow
		if err := rows.Scan(&i.EntrySeq, &i.Bytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertArchiveSegment = `-- name: InsertArchiveSegment :exec
INSERT INTO agent_session_archive_segments
            (session_id, object_key, min_entry_seq, max_entry_seq, kind)
     VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (session_id, object_key) DO NOTHING
`

type InsertArchiveSegmentParams struct {
	SessionID   string
	ObjectKey   string
	MinEntrySeq int64
	MaxEntrySeq int64
	Kind        string
}

func (q *Queries) InsertArchiveSegment(ctx context.Context, arg InsertArchiveSegmentParams) error {
	_, err := q.db.Exec(ctx, insertArchiveSegment,
		arg.SessionID,
		arg.ObjectKey,
		arg.MinEntrySeq,
		arg.MaxEntrySeq,
		arg.Kind,
	)
	return err
}

const insertTranscriptEntry = `-- name: InsertTranscriptEntry :execrows
INSERT INTO agent_session_transcript_entries
            (session_id, entry_seq, checkpoint, entry_json, idempotency_key)
     VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (idempotency_key) DO NOTHING
`

type InsertTranscriptEntryParams struct {
	SessionID      string
	EntrySeq       int64
	Checkpoint     bool
	EntryJson      string
	IdempotencyKey string
}

func (q *Queries) InsertTranscriptEntry(ctx context.Context, arg InsertTranscriptEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertTranscriptEntry,
		arg.SessionID,
		arg.EntrySeq,
		arg.Checkpoint,
		arg.EntryJson,
		arg.IdempotencyKey,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const latestCheckpointSeq = `-- name: LatestCheckpointSeq :one
SELECT COALESCE(MAX(entry_seq), 0)::BIGINT AS seq
   FROM agent_session_transcript_entries
  WHERE session_id = $1 AND checkpoint
`

func (q *Queries) LatestCheckpointSeq(ctx context.Context, sessionID string) (int64, error) {
	row := q.db.QueryRow(ctx, latestCheckpointSeq, sessionID)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const pruneTranscriptEntries = `-- name: PruneTranscriptEntries :exec
DELETE FROM agent_session_transcript_entries
  WHERE session_id = $1 AND entry_seq >= $2 AND entry_seq <= $3
`

type PruneTranscriptEntriesParams struct {
	SessionID  string
	EntrySeq   int64
	EntrySeq_2 int64
}

func (q *Queries) PruneTranscriptEntries(ctx context.Context, arg PruneTranscriptEntriesParams) error {
	_, err := q.db.Exec(ctx, pruneTranscriptEntries, arg.SessionID, arg.EntrySeq, arg.EntrySeq_2)
	return err
}

const remarkSafetyValveSuperseded = `-- name: RemarkSafetyValveSuperseded :exec
UPDATE agent_session_archive_segments
   SET kind = 'superseded'
 WHERE session_id = $1 AND kind = 'safety_valve' AND max_entry_seq < $2
`

type RemarkSafetyValveSupersededParams struct {
	SessionID   string
	MaxEntrySeq int64
}

func (q *Queries) RemarkSafetyValveSuperseded(ctx context.Context, arg RemarkSafetyValveSupersededParams) error {
	_, err := q.db.Exec(ctx, remarkSafetyValveSuperseded, arg.SessionID, arg.MaxEntrySeq)
	return err
}

const safetyValveSegments = `-- name: SafetyValveSegments :many
SELECT object_key, min_entry_seq, max_entry_seq, kind
   FROM agent_session_archive_segments
  WHERE session_id = $1 AND kind = $2
  ORDER BY min_entry_seq
`

type SafetyValveSegmentsParams struct {
	SessionID string
	Kind      string
}

type SafetyValveSegmentsRow struct {
	ObjectKey   string
	MinEntrySeq int64
	MaxEntrySeq int64
	Kind        string
}

func (q *Queries) SafetyValveSegments(ctx context.Context, arg SafetyValveSegmentsParams) ([]SafetyValveSegmentsRow, error) {
	rows, err := q.db.Query(ctx, safetyValveSegments, arg.SessionID, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SafetyValveSegmentsRow
	for rows.Next() {
		var i SafetyValveSegmentsRow
		if err := rows.Scan(
			&i.ObjectKey,
			&i.MinEntrySeq,
			&i.MaxEntrySeq,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionBase = `-- name: SessionBase :one
SELECT base_entry_seq FROM agent_sessions WHERE session_id = $1
`

func (q *Queries) SessionBase(ctx context.Context, sessionID string) (int64, error) {
	row := q.db.QueryRow(ctx, sessionBase, sessionID)
	var base_entry_seq int64
	err := row.Scan(&base_entry_seq)
	return base_entry_seq, err
}

const sessionMaxEntrySeq = `-- name: SessionMaxEntrySeq :one
SELECT COALESCE(MAX(entry_seq), 0)::BIGINT AS seq
   FROM agent_session_transcript_entries
  WHERE session_id = $1
`

func (q *Queries) SessionMaxEntrySeq(ctx context.Context, sessionID string) (int64, error) {
	row := q.db.QueryRow(ctx, sessionMaxEntrySeq, sessionID)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const sessionTranscript = `-- name: SessionTranscript :many
SELECT e.entry_seq, e.checkpoint, e.entry_json
   FROM agent_session_transcript_entries e
  WHERE e.session_id = $1
    AND e.entry_seq >= COALESCE(
            (SELECT MAX(cp.entry_seq)
               FROM agent_session_transcript_entries cp
              WHERE cp.session_id = $1 AND cp.checkpoint), 0)
  ORDER BY entry_seq
`

type SessionTranscriptRow struct {
	EntrySeq   int64
	Checkpoint bool
	EntryJson  string
}

func (q *Queries) SessionTranscript(ctx context.Context, sessionID string) ([]SessionTranscriptRow, error) {
	rows, err := q.db.Query(ctx, sessionTranscript, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionTranscriptRow
	for rows.Next() {
		var i SessionTranscriptRow
		if err := rows.Scan(&i.EntrySeq, &i.Checkpoint, &i.EntryJson); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
