// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channels.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const agentOwnersByIDs = `-- name: AgentOwnersByIDs :many
SELECT owner_user_id FROM agent_accounts WHERE account_id = ANY($1::text[])
`

func (q *Queries) AgentOwnersByIDs(ctx context.Context, dollar_1 []string) ([]string, error) {
	rows, err := q.db.Query(ctx, agentOwnersByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var owner_user_id string
		if err := rows.Scan(&owner_user_id); err != nil {
			return nil, err
		}
		items = append(items, owner_user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const channelGroupVisibleTo = `-- name: ChannelGroupVisibleTo :one
WITH RECURSIVE ancestry AS (
	SELECT id, parent_group_id, visibility AS min_vis
	FROM channel_groups
	UNION ALL
	SELECT a.id, g.parent_group_id, LEAST(a.min_vis, g.visibility)
	FROM ancestry a
	JOIN channel_groups g ON g.id = a.parent_group_id
),
effective AS (
	SELECT id, MIN(min_vis) AS eff_vis
	FROM ancestry
	GROUP BY id
),
viewer AS (
	SELECT owner_user_id AS uid FROM agent_accounts WHERE account_id = $1
	UNION ALL
	SELECT $1 AS uid
)
SELECT EXISTS (
	SELECT 1 FROM channel_groups g
	JOIN effective e ON e.id = g.id
	WHERE g.id = $2 AND (e.eff_vis = 1 OR g.owner_user_id IN (SELECT uid FROM viewer)
       OR g.namespace_owner_id IN (SELECT uid FROM viewer))
)
`

type ChannelGroupVisibleToParams struct {
	AccountID string
	ID        string
}

func (q *Queries) ChannelGroupVisibleTo(ctx context.Context, arg ChannelGroupVisibleToParams) (bool, error) {
	row := q.db.QueryRow(ctx, channelGroupVisibleTo, arg.AccountID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const channelMemberExists = `-- name: ChannelMemberExists :one
SELECT EXISTS (SELECT 1 FROM channel_members WHERE channel_id = $1 AND account_id = $2)
`

type ChannelMemberExistsParams struct {
	ChannelID string
	AccountID string
}

func (q *Queries) ChannelMemberExists(ctx context.Context, arg ChannelMemberExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, channelMemberExists, arg.ChannelID, arg.AccountID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const channelMembersByChannelIDs = `-- name: ChannelMembersByChannelIDs :many
WITH RECURSIVE stored AS (
    SELECT cm.channel_id, cm.account_id, cm.subscribed
    FROM channel_members cm
    JOIN channels c ON c.id = cm.channel_id
    WHERE cm.channel_id = ANY($1::text[]) AND c.membership_mode = 0
), subtree AS (
    SELECT c.id AS channel_id, c.parent_agent_id AS account_id
    FROM channels c
    WHERE c.id = ANY($1::text[]) AND c.membership_mode = 1
    UNION
    SELECT s.channel_id, a.account_id
    FROM agent_accounts a
    JOIN subtree s ON a.parent_agent_id = s.account_id
), participants AS (
    SELECT channel_id, account_id FROM subtree
    UNION
    SELECT c.id AS channel_id, aa.owner_user_id AS account_id
    FROM channels c
    JOIN agent_accounts aa ON aa.account_id = c.parent_agent_id
    WHERE c.id = ANY($1::text[]) AND c.membership_mode = 1
)
SELECT channel_id, account_id, subscribed FROM stored
UNION ALL
SELECT p.channel_id, p.account_id, COALESCE(cs.subscribed, FALSE) AS subscribed
FROM participants p
LEFT JOIN channel_subscriptions cs
    ON cs.channel_id = p.channel_id AND cs.account_id = p.account_id
ORDER BY channel_id, account_id
`

type ChannelMembersByChannelIDsRow struct {
	ChannelID  string
	AccountID  string
	Subscribed bool
}

func (q *Queries) ChannelMembersByChannelIDs(ctx context.Context, dollar_1 []string) ([]ChannelMembersByChannelIDsRow, error) {
	rows, err := q.db.Query(ctx, channelMembersByChannelIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelMembersByChannelIDsRow
	for rows.Next() {
		var i ChannelMembersByChannelIDsRow
		if err := rows.Scan(&i.ChannelID, &i.AccountID, &i.Subscribed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const channelParticipant = `-- name: ChannelParticipant :one
WITH RECURSIVE chain AS (
    SELECT aa.account_id, aa.parent_agent_id
    FROM agent_accounts aa
    WHERE aa.account_id = $2
      AND EXISTS (SELECT 1 FROM channels WHERE id = $1 AND membership_mode = 1)
    UNION
    SELECT a.account_id, a.parent_agent_id
    FROM agent_accounts a
    JOIN chain ch ON a.account_id = ch.parent_agent_id
)
SELECT EXISTS (
    SELECT 1 FROM channel_members cm
    WHERE cm.channel_id = $1 AND cm.account_id = $2
) OR (
    EXISTS (SELECT 1 FROM channels WHERE id = $1 AND membership_mode = 1)
    AND EXISTS (
        SELECT 1 FROM channels c
        WHERE c.id = $1 AND (
            c.parent_agent_id IN (SELECT ch.account_id FROM chain ch)
            OR $2 = (SELECT aa.owner_user_id FROM agent_accounts aa
                     WHERE aa.account_id = c.parent_agent_id)
        )
    )
)
`

type ChannelParticipantParams struct {
	ChannelID string
	AccountID string
}

// Explicit member row, or (TREE only) the actor is in the anchor's subtree or
// owns the anchor. UNION, not UNION ALL: agent parent rows are not guaranteed
// acyclic, and deduplication is what stops the walk on a cycle.
func (q *Queries) ChannelParticipant(ctx context.Context, arg ChannelParticipantParams) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, channelParticipant, arg.ChannelID, arg.AccountID)
	var column_1 pgtype.Bool
	err := row.Scan(&column_1)
	return column_1, err
}

const channelVisibleTo = `-- name: ChannelVisibleTo :one
WITH RECURSIVE ancestry AS (
	SELECT id, parent_group_id, visibility AS min_vis
	FROM channel_groups
	UNION ALL
	SELECT a.id, g.parent_group_id, LEAST(a.min_vis, g.visibility)
	FROM ancestry a
	JOIN channel_groups g ON g.id = a.parent_group_id
),
effective AS (
	SELECT id, MIN(min_vis) AS eff_vis
	FROM ancestry
	GROUP BY id
),
viewer AS (
	SELECT owner_user_id AS uid FROM agent_accounts WHERE account_id = $1
	UNION ALL
	SELECT $1 AS uid
)
SELECT EXISTS (
	SELECT 1 FROM channels c
	WHERE c.id = $2 AND (
		EXISTS (
		    SELECT 1 FROM channel_members cm
		    WHERE cm.channel_id = c.id AND cm.account_id = $1
		)
		OR (
		    c.kind = 0 AND c.group_id IS NOT NULL AND EXISTS (
		        SELECT 1 FROM effective e WHERE e.id = c.group_id AND e.eff_vis = 1
		    )
		)
		OR (
		    c.parent_agent_id IS NOT NULL
		    AND (SELECT aa.owner_user_id FROM agent_accounts aa WHERE aa.account_id = c.parent_agent_id)
		        IN (SELECT uid FROM viewer)
		)
	)
)
`

type ChannelVisibleToParams struct {
	AccountID string
	ID        string
}

func (q *Queries) ChannelVisibleTo(ctx context.Context, arg ChannelVisibleToParams) (bool, error) {
	row := q.db.QueryRow(ctx, channelVisibleTo, arg.AccountID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const channelsByNameForViewer = `-- name: ChannelsByNameForViewer :many
WITH RECURSIVE ancestry AS (
	SELECT id, parent_group_id, visibility AS min_vis
	FROM channel_groups
	UNION ALL
	SELECT a.id, g.parent_group_id, LEAST(a.min_vis, g.visibility)
	FROM ancestry a
	JOIN channel_groups g ON g.id = a.parent_group_id
),
effective AS (
	SELECT id, MIN(min_vis) AS eff_vis
	FROM ancestry
	GROUP BY id
),
viewer AS (
	SELECT owner_user_id AS uid FROM agent_accounts WHERE account_id = $1
	UNION ALL
	SELECT $1 AS uid
)
SELECT c.id, c.name, COALESCE(c.group_id, '') AS group_id, c.kind, c.post_policy,
       COALESCE(c.owner_account_id, '') AS owner_account_id, c.mandatory_subscription,
       COALESCE(c.parent_agent_id, '') AS parent_agent_id, c.membership_mode
FROM channels c
WHERE c.name = $2 AND (
		EXISTS (
		    SELECT 1 FROM channel_members cm
		    WHERE cm.channel_id = c.id AND cm.account_id = $1
		)
		OR (
		    c.kind = 0 AND c.group_id IS NOT NULL AND EXISTS (
		        SELECT 1 FROM effective e WHERE e.id = c.group_id AND e.eff_vis = 1
		    )
		)
		OR (
		    c.parent_agent_id IS NOT NULL
		    AND (SELECT aa.owner_user_id FROM agent_accounts aa WHERE aa.account_id = c.parent_agent_id)
		        IN (SELECT uid FROM viewer)
		)
	)
ORDER BY c.id
`

type ChannelsByNameForViewerParams struct {
	AccountID string
	Name      string
}

type ChannelsByNameForViewerRow struct {
	ID                    string
	Name                  string
	GroupID               string
	Kind                  int16
	PostPolicy            int16
	OwnerAccountID        string
	MandatorySubscription bool
	ParentAgentID         string
	MembershipMode        int16
}

func (q *Queries) ChannelsByNameForViewer(ctx context.Context, arg ChannelsByNameForViewerParams) ([]ChannelsByNameForViewerRow, error) {
	rows, err := q.db.Query(ctx, channelsByNameForViewer, arg.AccountID, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelsByNameForViewerRow
	for rows.Next() {
		var i ChannelsByNameForViewerRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.GroupID,
			&i.Kind,
			&i.PostPolicy,
			&i.OwnerAccountID,
			&i.MandatorySubscription,
			&i.ParentAgentID,
			&i.MembershipMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const convertDMChannel = `-- name: ConvertDMChannel :exec
UPDATE channels SET kind = $1, name = $2, group_id = NULL, mandatory_subscription = FALSE WHERE id = $3
`

type ConvertDMChannelParams struct {
	Kind int16
	Name string
	ID   string
}

func (q *Queries) ConvertDMChannel(ctx context.Context, arg ConvertDMChannelParams) error {
	_, err := q.db.Exec(ctx, convertDMChannel, arg.Kind, arg.Name, arg.ID)
	return err
}

const countAgentMembers = `-- name: CountAgentMembers :one
SELECT COUNT(*) FROM channel_members cm
JOIN agent_accounts aa ON aa.account_id = cm.account_id
WHERE cm.channel_id = $1
`

func (q *Queries) CountAgentMembers(ctx context.Context, channelID string) (int64, error) {
	row := q.db.QueryRow(ctx, countAgentMembers, channelID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteChannelMember = `-- name: DeleteChannelMember :execrows
DELETE FROM channel_members WHERE channel_id = $1 AND account_id = $2
`

type DeleteChannelMemberParams struct {
	ChannelID string
	AccountID string
}

func (q *Queries) DeleteChannelMember(ctx context.Context, arg DeleteChannelMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChannelMember, arg.ChannelID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAgentWorkspaceID = `-- name: GetAgentWorkspaceID :one
SELECT id FROM agent_workspaces WHERE agent_account_id = $1
`

func (q *Queries) GetAgentWorkspaceID(ctx context.Context, agentAccountID string) (string, error) {
	row := q.db.QueryRow(ctx, getAgentWorkspaceID, agentAccountID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getChannel = `-- name: GetChannel :one
SELECT id, name, COALESCE(group_id, '') AS group_id, kind, post_policy,
       COALESCE(owner_account_id, '') AS owner_account_id, mandatory_subscription,
       COALESCE(parent_agent_id, '') AS parent_agent_id, membership_mode
FROM channels WHERE id = $1
`

type GetChannelRow struct {
	ID                    string
	Name                  string
	GroupID               string
	Kind                  int16
	PostPolicy            int16
	OwnerAccountID        string
	MandatorySubscription bool
	ParentAgentID         string
	MembershipMode        int16
}

func (q *Queries) GetChannel(ctx context.Context, id string) (GetChannelRow, error) {
	row := q.db.QueryRow(ctx, getChannel, id)
	var i GetChannelRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GroupID,
		&i.Kind,
		&i.PostPolicy,
		&i.OwnerAccountID,
		&i.MandatorySubscription,
		&i.ParentAgentID,
		&i.MembershipMode,
	)
	return i, err
}

const getChannelGroupVisibility = `-- name: GetChannelGroupVisibility :one
SELECT visibility FROM channel_groups WHERE id = $1
`

func (q *Queries) GetChannelGroupVisibility(ctx context.Context, id string) (int16, error) {
	row := q.db.QueryRow(ctx, getChannelGroupVisibility, id)
	var visibility int16
	err := row.Scan(&visibility)
	return visibility, err
}

const globalHandlesByAccountIDs = `-- name: GlobalHandlesByAccountIDs :many
SELECT account_id, handle FROM account_handles
WHERE owner_user_id IS NULL AND account_id = ANY($1::text[])
`

type GlobalHandlesByAccountIDsRow struct {
	AccountID string
	Handle    string
}

func (q *Queries) GlobalHandlesByAccountIDs(ctx context.Context, dollar_1 []string) ([]GlobalHandlesByAccountIDsRow, error) {
	rows, err := q.db.Query(ctx, globalHandlesByAccountIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GlobalHandlesByAccountIDsRow
	for rows.Next() {
		var i GlobalHandlesByAccountIDsRow
		if err := rows.Scan(&i.AccountID, &i.Handle); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAgentWorkspaceIgnore = `-- name: InsertAgentWorkspaceIgnore :exec
INSERT INTO agent_workspaces (id, agent_account_id)
VALUES ($1, $2)
ON CONFLICT (agent_account_id) DO NOTHING
`

type InsertAgentWorkspaceIgnoreParams struct {
	ID             string
	AgentAccountID string
}

func (q *Queries) InsertAgentWorkspaceIgnore(ctx context.Context, arg InsertAgentWorkspaceIgnoreParams) error {
	_, err := q.db.Exec(ctx, insertAgentWorkspaceIgnore, arg.ID, arg.AgentAccountID)
	return err
}

const insertChannel = `-- name: InsertChannel :exec
INSERT INTO channels (id, name, group_id, kind, post_policy, owner_account_id, mandatory_subscription, parent_agent_id, membership_mode)
VALUES ($1, $2, NULLIF($3, ''), $4, $5, NULLIF($6, ''), $7, NULLIF($8, ''), $9)
`

type InsertChannelParams struct {
	ID                    string
	Name                  string
	Column3               interface{}
	Kind                  int16
	PostPolicy            int16
	Column6               interface{}
	MandatorySubscription bool
	Column8               interface{}
	MembershipMode        int16
}

func (q *Queries) InsertChannel(ctx context.Context, arg InsertChannelParams) error {
	_, err := q.db.Exec(ctx, insertChannel,
		arg.ID,
		arg.Name,
		arg.Column3,
		arg.Kind,
		arg.PostPolicy,
		arg.Column6,
		arg.MandatorySubscription,
		arg.Column8,
		arg.MembershipMode,
	)
	return err
}

const insertChannelGroup = `-- name: InsertChannelGroup :one

INSERT INTO channel_groups (id, name, parent_group_id, owner_user_id, visibility, namespace_owner_id)
VALUES ($1, $2, NULLIF($3, ''), $4, $5,
        COALESCE((SELECT owner_user_id FROM agent_accounts WHERE account_id = $4), $4))
RETURNING namespace_owner_id
`

type InsertChannelGroupParams struct {
	ID          string
	Name        string
	Column3     interface{}
	OwnerUserID string
	Visibility  int16
}

// Channel-domain queries (sqlc adoption T3, RIG-3034). These replace the inline
// SQL literals that lived in internal/store/channels.go; the hand-written Store
// methods keep their exact signatures and wrap these generated calls, mapping
// the generated row structs back to the domain Channel / ChannelGroup.
//
// The channel-visibility CTE (effective(id, eff_vis)) and the channel/group
// visibility predicates are repeated per read because sqlc has no query-fragment
// composition — they replace the former channels.go const fragments
// (effectiveVisibilityCTE / viewerCTE / channelVisiblePredicate /
// groupVisiblePredicate). The copies MUST stay textually identical so the stream
// edge's single-id visibility check cannot drift from the list read (the
// anti-drift guarantee the design record requires).
// An agent's group lives in its owner's namespace, which keys top-level names.
func (q *Queries) InsertChannelGroup(ctx context.Context, arg InsertChannelGroupParams) (string, error) {
	row := q.db.QueryRow(ctx, insertChannelGroup,
		arg.ID,
		arg.Name,
		arg.Column3,
		arg.OwnerUserID,
		arg.Visibility,
	)
	var namespace_owner_id string
	err := row.Scan(&namespace_owner_id)
	return namespace_owner_id, err
}

const listChannelGroups = `-- name: ListChannelGroups :many
WITH RECURSIVE ancestry AS (
	SELECT id, parent_group_id, visibility AS min_vis
	FROM channel_groups
	UNION ALL
	SELECT a.id, g.parent_group_id, LEAST(a.min_vis, g.visibility)
	FROM ancestry a
	JOIN channel_groups g ON g.id = a.parent_group_id
),
effective AS (
	SELECT id, MIN(min_vis) AS eff_vis
	FROM ancestry
	GROUP BY id
),
viewer AS (
	SELECT owner_user_id AS uid FROM agent_accounts WHERE account_id = $1
	UNION ALL
	SELECT $1 AS uid
)
SELECT g.id, g.name, COALESCE(g.parent_group_id, '') AS parent_group_id, g.owner_user_id, g.visibility, g.namespace_owner_id
FROM channel_groups g
JOIN effective e ON e.id = g.id
WHERE (e.eff_vis = 1 OR g.owner_user_id IN (SELECT uid FROM viewer)
       OR g.namespace_owner_id IN (SELECT uid FROM viewer))
ORDER BY g.name
`

type ListChannelGroupsRow struct {
	ID               string
	Name             string
	ParentGroupID    string
	OwnerUserID      string
	Visibility       int16
	NamespaceOwnerID string
}

func (q *Queries) ListChannelGroups(ctx context.Context, accountID string) ([]ListChannelGroupsRow, error) {
	rows, err := q.db.Query(ctx, listChannelGroups, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelGroupsRow
	for rows.Next() {
		var i ListChannelGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentGroupID,
			&i.OwnerUserID,
			&i.Visibility,
			&i.NamespaceOwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannels = `-- name: ListChannels :many
WITH RECURSIVE ancestry AS (
	SELECT id, parent_group_id, visibility AS min_vis
	FROM channel_groups
	UNION ALL
	SELECT a.id, g.parent_group_id, LEAST(a.min_vis, g.visibility)
	FROM ancestry a
	JOIN channel_groups g ON g.id = a.parent_group_id
),
effective AS (
	SELECT id, MIN(min_vis) AS eff_vis
	FROM ancestry
	GROUP BY id
),
viewer AS (
	SELECT owner_user_id AS uid FROM agent_accounts WHERE account_id = $1
	UNION ALL
	SELECT $1 AS uid
)
SELECT c.id, c.name, COALESCE(c.group_id, '') AS group_id, c.kind, c.post_policy,
       COALESCE(c.owner_account_id, '') AS owner_account_id, c.mandatory_subscription,
       COALESCE(c.parent_agent_id, '') AS parent_agent_id, c.membership_mode
FROM channels c
WHERE (
		EXISTS (
		    SELECT 1 FROM channel_members cm
		    WHERE cm.channel_id = c.id AND cm.account_id = $1
		)
		OR (
		    c.kind = 0 AND c.group_id IS NOT NULL AND EXISTS (
		        SELECT 1 FROM effective e WHERE e.id = c.group_id AND e.eff_vis = 1
		    )
		)
		OR (
		    c.parent_agent_id IS NOT NULL
		    AND (SELECT aa.owner_user_id FROM agent_accounts aa WHERE aa.account_id = c.parent_agent_id)
		        IN (SELECT uid FROM viewer)
		)
	)
ORDER BY c.name
`

type ListChannelsRow struct {
	ID                    string
	Name                  string
	GroupID               string
	Kind                  int16
	PostPolicy            int16
	OwnerAccountID        string
	MandatorySubscription bool
	ParentAgentID         string
	MembershipMode        int16
}

func (q *Queries) ListChannels(ctx context.Context, accountID string) ([]ListChannelsRow, error) {
	rows, err := q.db.Query(ctx, listChannels, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelsRow
	for rows.Next() {
		var i ListChannelsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.GroupID,
			&i.Kind,
			&i.PostPolicy,
			&i.OwnerAccountID,
			&i.MandatorySubscription,
			&i.ParentAgentID,
			&i.MembershipMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockChannelForReparent = `-- name: LockChannelForReparent :one
SELECT channels.group_id, channels.kind, channels.membership_mode,
       EXISTS (SELECT 1 FROM agent_accounts WHERE home_channel_id = channels.id) AS is_home
FROM channels WHERE channels.id = $1 FOR UPDATE OF channels
`

type LockChannelForReparentRow struct {
	GroupID        pgtype.Text
	Kind           int16
	MembershipMode int16
	IsHome         bool
}

func (q *Queries) LockChannelForReparent(ctx context.Context, id string) (LockChannelForReparentRow, error) {
	row := q.db.QueryRow(ctx, lockChannelForReparent, id)
	var i LockChannelForReparentRow
	err := row.Scan(
		&i.GroupID,
		&i.Kind,
		&i.MembershipMode,
		&i.IsHome,
	)
	return i, err
}

const lockChannelMandatoryKind = `-- name: LockChannelMandatoryKind :one
SELECT mandatory_subscription, kind FROM channels WHERE id = $1 FOR UPDATE
`

type LockChannelMandatoryKindRow struct {
	MandatorySubscription bool
	Kind                  int16
}

func (q *Queries) LockChannelMandatoryKind(ctx context.Context, id string) (LockChannelMandatoryKindRow, error) {
	row := q.db.QueryRow(ctx, lockChannelMandatoryKind, id)
	var i LockChannelMandatoryKindRow
	err := row.Scan(&i.MandatorySubscription, &i.Kind)
	return i, err
}

const lockChannelPolicy = `-- name: LockChannelPolicy :one
SELECT mandatory_subscription, COALESCE(owner_account_id, '') AS owner_account_id
FROM channels WHERE id = $1 FOR UPDATE
`

type LockChannelPolicyRow struct {
	MandatorySubscription bool
	OwnerAccountID        string
}

func (q *Queries) LockChannelPolicy(ctx context.Context, id string) (LockChannelPolicyRow, error) {
	row := q.db.QueryRow(ctx, lockChannelPolicy, id)
	var i LockChannelPolicyRow
	err := row.Scan(&i.MandatorySubscription, &i.OwnerAccountID)
	return i, err
}

const ownerHasPresentAgent = `-- name: OwnerHasPresentAgent :one
SELECT EXISTS (
    SELECT 1 FROM agent_accounts aa
    JOIN channel_members cm ON cm.account_id = aa.account_id
    WHERE aa.owner_user_id = $1 AND cm.channel_id = $2 AND aa.account_id <> $1
)
`

type OwnerHasPresentAgentParams struct {
	OwnerUserID string
	ChannelID   string
}

func (q *Queries) OwnerHasPresentAgent(ctx context.Context, arg OwnerHasPresentAgentParams) (bool, error) {
	row := q.db.QueryRow(ctx, ownerHasPresentAgent, arg.OwnerUserID, arg.ChannelID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const subscribeConvertedDMParties = `-- name: SubscribeConvertedDMParties :exec
UPDATE channel_members cm SET subscribed = TRUE
FROM agent_accounts aa WHERE aa.account_id = cm.account_id AND cm.channel_id = $1
`

func (q *Queries) SubscribeConvertedDMParties(ctx context.Context, channelID string) error {
	_, err := q.db.Exec(ctx, subscribeConvertedDMParties, channelID)
	return err
}

const updateChannelParent = `-- name: UpdateChannelParent :exec
UPDATE channels SET parent_agent_id = NULLIF($2, '') WHERE id = $1
`

type UpdateChannelParentParams struct {
	ID      string
	Column2 interface{}
}

func (q *Queries) UpdateChannelParent(ctx context.Context, arg UpdateChannelParentParams) error {
	_, err := q.db.Exec(ctx, updateChannelParent, arg.ID, arg.Column2)
	return err
}

const updateChannelPolicy = `-- name: UpdateChannelPolicy :exec
UPDATE channels SET post_policy = $2, owner_account_id = NULLIF($3, ''), mandatory_subscription = $4 WHERE id = $1
`

type UpdateChannelPolicyParams struct {
	ID                    string
	PostPolicy            int16
	Column3               interface{}
	MandatorySubscription bool
}

func (q *Queries) UpdateChannelPolicy(ctx context.Context, arg UpdateChannelPolicyParams) error {
	_, err := q.db.Exec(ctx, updateChannelPolicy,
		arg.ID,
		arg.PostPolicy,
		arg.Column3,
		arg.MandatorySubscription,
	)
	return err
}

const upsertChannelMember = `-- name: UpsertChannelMember :exec
INSERT INTO channel_members (channel_id, account_id, subscribed)
VALUES ($1, $2, $3)
ON CONFLICT (channel_id, account_id) DO UPDATE SET subscribed = EXCLUDED.subscribed
`

type UpsertChannelMemberParams struct {
	ChannelID  string
	AccountID  string
	Subscribed bool
}

func (q *Queries) UpsertChannelMember(ctx context.Context, arg UpsertChannelMemberParams) error {
	_, err := q.db.Exec(ctx, upsertChannelMember, arg.ChannelID, arg.AccountID, arg.Subscribed)
	return err
}
