// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channels.sql

package db

import (
	"context"
)

const agentOwnersByIDs = `-- name: AgentOwnersByIDs :many
SELECT owner_user_id FROM agent_accounts WHERE account_id = ANY($1::text[])
`

func (q *Queries) AgentOwnersByIDs(ctx context.Context, dollar_1 []string) ([]string, error) {
	rows, err := q.db.Query(ctx, agentOwnersByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var owner_user_id string
		if err := rows.Scan(&owner_user_id); err != nil {
			return nil, err
		}
		items = append(items, owner_user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const channelGroupVisibleTo = `-- name: ChannelGroupVisibleTo :one
WITH RECURSIVE ancestry AS (
	SELECT id, parent_group_id, visibility AS min_vis
	FROM channel_groups
	UNION ALL
	SELECT a.id, g.parent_group_id, LEAST(a.min_vis, g.visibility)
	FROM ancestry a
	JOIN channel_groups g ON g.id = a.parent_group_id
),
effective AS (
	SELECT id, MIN(min_vis) AS eff_vis
	FROM ancestry
	GROUP BY id
),
viewer AS (
	SELECT owner_user_id AS uid FROM agent_accounts WHERE account_id = $1
	UNION ALL
	SELECT $1 AS uid
)
SELECT EXISTS (
	SELECT 1 FROM channel_groups g
	JOIN effective e ON e.id = g.id
	WHERE g.id = $2 AND (e.eff_vis = 1 OR g.owner_user_id IN (SELECT uid FROM viewer))
)
`

type ChannelGroupVisibleToParams struct {
	AccountID string
	ID        string
}

func (q *Queries) ChannelGroupVisibleTo(ctx context.Context, arg ChannelGroupVisibleToParams) (bool, error) {
	row := q.db.QueryRow(ctx, channelGroupVisibleTo, arg.AccountID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const channelMemberExists = `-- name: ChannelMemberExists :one
SELECT EXISTS (SELECT 1 FROM channel_members WHERE channel_id = $1 AND account_id = $2)
`

type ChannelMemberExistsParams struct {
	ChannelID string
	AccountID string
}

func (q *Queries) ChannelMemberExists(ctx context.Context, arg ChannelMemberExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, channelMemberExists, arg.ChannelID, arg.AccountID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const channelMembersByChannelIDs = `-- name: ChannelMembersByChannelIDs :many
SELECT channel_id, account_id, subscribed
FROM channel_members
WHERE channel_id = ANY($1::text[])
ORDER BY account_id
`

func (q *Queries) ChannelMembersByChannelIDs(ctx context.Context, dollar_1 []string) ([]ChannelMember, error) {
	rows, err := q.db.Query(ctx, channelMembersByChannelIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelMember
	for rows.Next() {
		var i ChannelMember
		if err := rows.Scan(&i.ChannelID, &i.AccountID, &i.Subscribed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const channelVisibleTo = `-- name: ChannelVisibleTo :one
WITH RECURSIVE ancestry AS (
	SELECT id, parent_group_id, visibility AS min_vis
	FROM channel_groups
	UNION ALL
	SELECT a.id, g.parent_group_id, LEAST(a.min_vis, g.visibility)
	FROM ancestry a
	JOIN channel_groups g ON g.id = a.parent_group_id
),
effective AS (
	SELECT id, MIN(min_vis) AS eff_vis
	FROM ancestry
	GROUP BY id
)
SELECT EXISTS (
	SELECT 1 FROM channels c
	WHERE c.id = $2 AND (
		EXISTS (
		    SELECT 1 FROM channel_members cm
		    WHERE cm.channel_id = c.id AND cm.account_id = $1
		)
		OR (
		    c.kind = 0 AND c.group_id IS NOT NULL AND EXISTS (
		        SELECT 1 FROM effective e WHERE e.id = c.group_id AND e.eff_vis = 1
		    )
		)
	)
)
`

type ChannelVisibleToParams struct {
	AccountID string
	ID        string
}

func (q *Queries) ChannelVisibleTo(ctx context.Context, arg ChannelVisibleToParams) (bool, error) {
	row := q.db.QueryRow(ctx, channelVisibleTo, arg.AccountID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const channelsByNameForViewer = `-- name: ChannelsByNameForViewer :many
WITH RECURSIVE ancestry AS (
	SELECT id, parent_group_id, visibility AS min_vis
	FROM channel_groups
	UNION ALL
	SELECT a.id, g.parent_group_id, LEAST(a.min_vis, g.visibility)
	FROM ancestry a
	JOIN channel_groups g ON g.id = a.parent_group_id
),
effective AS (
	SELECT id, MIN(min_vis) AS eff_vis
	FROM ancestry
	GROUP BY id
)
SELECT c.id, c.name, COALESCE(c.group_id, '') AS group_id, c.kind, c.post_policy,
       COALESCE(c.owner_account_id, '') AS owner_account_id, c.mandatory_subscription
FROM channels c
WHERE c.name = $2 AND (
		EXISTS (
		    SELECT 1 FROM channel_members cm
		    WHERE cm.channel_id = c.id AND cm.account_id = $1
		)
		OR (
		    c.kind = 0 AND c.group_id IS NOT NULL AND EXISTS (
		        SELECT 1 FROM effective e WHERE e.id = c.group_id AND e.eff_vis = 1
		    )
		)
	)
ORDER BY c.id
`

type ChannelsByNameForViewerParams struct {
	AccountID string
	Name      string
}

type ChannelsByNameForViewerRow struct {
	ID                    string
	Name                  string
	GroupID               string
	Kind                  int16
	PostPolicy            int16
	OwnerAccountID        string
	MandatorySubscription bool
}

func (q *Queries) ChannelsByNameForViewer(ctx context.Context, arg ChannelsByNameForViewerParams) ([]ChannelsByNameForViewerRow, error) {
	rows, err := q.db.Query(ctx, channelsByNameForViewer, arg.AccountID, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelsByNameForViewerRow
	for rows.Next() {
		var i ChannelsByNameForViewerRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.GroupID,
			&i.Kind,
			&i.PostPolicy,
			&i.OwnerAccountID,
			&i.MandatorySubscription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const convertDMChannel = `-- name: ConvertDMChannel :exec
UPDATE channels SET kind = $1, name = $2, group_id = NULL, mandatory_subscription = FALSE WHERE id = $3
`

type ConvertDMChannelParams struct {
	Kind int16
	Name string
	ID   string
}

func (q *Queries) ConvertDMChannel(ctx context.Context, arg ConvertDMChannelParams) error {
	_, err := q.db.Exec(ctx, convertDMChannel, arg.Kind, arg.Name, arg.ID)
	return err
}

const countAgentMembers = `-- name: CountAgentMembers :one
SELECT COUNT(*) FROM channel_members cm
JOIN agent_accounts aa ON aa.account_id = cm.account_id
WHERE cm.channel_id = $1
`

func (q *Queries) CountAgentMembers(ctx context.Context, channelID string) (int64, error) {
	row := q.db.QueryRow(ctx, countAgentMembers, channelID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteChannelMember = `-- name: DeleteChannelMember :execrows
DELETE FROM channel_members WHERE channel_id = $1 AND account_id = $2
`

type DeleteChannelMemberParams struct {
	ChannelID string
	AccountID string
}

func (q *Queries) DeleteChannelMember(ctx context.Context, arg DeleteChannelMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChannelMember, arg.ChannelID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAgentWorkspaceID = `-- name: GetAgentWorkspaceID :one
SELECT id FROM agent_workspaces WHERE agent_account_id = $1
`

func (q *Queries) GetAgentWorkspaceID(ctx context.Context, agentAccountID string) (string, error) {
	row := q.db.QueryRow(ctx, getAgentWorkspaceID, agentAccountID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getChannel = `-- name: GetChannel :one
SELECT id, name, COALESCE(group_id, '') AS group_id, kind, post_policy,
       COALESCE(owner_account_id, '') AS owner_account_id, mandatory_subscription
FROM channels WHERE id = $1
`

type GetChannelRow struct {
	ID                    string
	Name                  string
	GroupID               string
	Kind                  int16
	PostPolicy            int16
	OwnerAccountID        string
	MandatorySubscription bool
}

func (q *Queries) GetChannel(ctx context.Context, id string) (GetChannelRow, error) {
	row := q.db.QueryRow(ctx, getChannel, id)
	var i GetChannelRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GroupID,
		&i.Kind,
		&i.PostPolicy,
		&i.OwnerAccountID,
		&i.MandatorySubscription,
	)
	return i, err
}

const getChannelGroupVisibility = `-- name: GetChannelGroupVisibility :one
SELECT visibility FROM channel_groups WHERE id = $1
`

func (q *Queries) GetChannelGroupVisibility(ctx context.Context, id string) (int16, error) {
	row := q.db.QueryRow(ctx, getChannelGroupVisibility, id)
	var visibility int16
	err := row.Scan(&visibility)
	return visibility, err
}

const insertAgentWorkspaceIgnore = `-- name: InsertAgentWorkspaceIgnore :exec
INSERT INTO agent_workspaces (id, agent_account_id)
VALUES ($1, $2)
ON CONFLICT (agent_account_id) DO NOTHING
`

type InsertAgentWorkspaceIgnoreParams struct {
	ID             string
	AgentAccountID string
}

func (q *Queries) InsertAgentWorkspaceIgnore(ctx context.Context, arg InsertAgentWorkspaceIgnoreParams) error {
	_, err := q.db.Exec(ctx, insertAgentWorkspaceIgnore, arg.ID, arg.AgentAccountID)
	return err
}

const insertChannel = `-- name: InsertChannel :exec
INSERT INTO channels (id, name, group_id, kind, post_policy, owner_account_id, mandatory_subscription)
VALUES ($1, $2, NULLIF($3, ''), $4, $5, NULLIF($6, ''), $7)
`

type InsertChannelParams struct {
	ID                    string
	Name                  string
	Column3               interface{}
	Kind                  int16
	PostPolicy            int16
	Column6               interface{}
	MandatorySubscription bool
}

func (q *Queries) InsertChannel(ctx context.Context, arg InsertChannelParams) error {
	_, err := q.db.Exec(ctx, insertChannel,
		arg.ID,
		arg.Name,
		arg.Column3,
		arg.Kind,
		arg.PostPolicy,
		arg.Column6,
		arg.MandatorySubscription,
	)
	return err
}

const insertChannelGroup = `-- name: InsertChannelGroup :exec

INSERT INTO channel_groups (id, name, parent_group_id, owner_user_id, visibility)
VALUES ($1, $2, NULLIF($3, ''), $4, $5)
`

type InsertChannelGroupParams struct {
	ID          string
	Name        string
	Column3     interface{}
	OwnerUserID string
	Visibility  int16
}

// Channel-domain queries (sqlc adoption T3, RIG-3034). These replace the inline
// SQL literals that lived in internal/store/channels.go; the hand-written Store
// methods keep their exact signatures and wrap these generated calls, mapping
// the generated row structs back to the domain Channel / ChannelGroup.
//
// The channel-visibility CTE (effective(id, eff_vis)) and the channel/group
// visibility predicates are repeated per read because sqlc has no query-fragment
// composition — they replace the former channels.go const fragments
// (effectiveVisibilityCTE / viewerCTE / channelVisiblePredicate /
// groupVisiblePredicate). The copies MUST stay textually identical so the stream
// edge's single-id visibility check cannot drift from the list read (the
// anti-drift guarantee the frozen record requires).
func (q *Queries) InsertChannelGroup(ctx context.Context, arg InsertChannelGroupParams) error {
	_, err := q.db.Exec(ctx, insertChannelGroup,
		arg.ID,
		arg.Name,
		arg.Column3,
		arg.OwnerUserID,
		arg.Visibility,
	)
	return err
}

const listChannelGroups = `-- name: ListChannelGroups :many
WITH RECURSIVE ancestry AS (
	SELECT id, parent_group_id, visibility AS min_vis
	FROM channel_groups
	UNION ALL
	SELECT a.id, g.parent_group_id, LEAST(a.min_vis, g.visibility)
	FROM ancestry a
	JOIN channel_groups g ON g.id = a.parent_group_id
),
effective AS (
	SELECT id, MIN(min_vis) AS eff_vis
	FROM ancestry
	GROUP BY id
),
viewer AS (
	SELECT owner_user_id AS uid FROM agent_accounts WHERE account_id = $1
	UNION ALL
	SELECT $1 AS uid
)
SELECT g.id, g.name, COALESCE(g.parent_group_id, '') AS parent_group_id, g.owner_user_id, g.visibility
FROM channel_groups g
JOIN effective e ON e.id = g.id
WHERE (e.eff_vis = 1 OR g.owner_user_id IN (SELECT uid FROM viewer))
ORDER BY g.name
`

type ListChannelGroupsRow struct {
	ID            string
	Name          string
	ParentGroupID string
	OwnerUserID   string
	Visibility    int16
}

func (q *Queries) ListChannelGroups(ctx context.Context, accountID string) ([]ListChannelGroupsRow, error) {
	rows, err := q.db.Query(ctx, listChannelGroups, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelGroupsRow
	for rows.Next() {
		var i ListChannelGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentGroupID,
			&i.OwnerUserID,
			&i.Visibility,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannels = `-- name: ListChannels :many
WITH RECURSIVE ancestry AS (
	SELECT id, parent_group_id, visibility AS min_vis
	FROM channel_groups
	UNION ALL
	SELECT a.id, g.parent_group_id, LEAST(a.min_vis, g.visibility)
	FROM ancestry a
	JOIN channel_groups g ON g.id = a.parent_group_id
),
effective AS (
	SELECT id, MIN(min_vis) AS eff_vis
	FROM ancestry
	GROUP BY id
)
SELECT c.id, c.name, COALESCE(c.group_id, '') AS group_id, c.kind, c.post_policy,
       COALESCE(c.owner_account_id, '') AS owner_account_id, c.mandatory_subscription
FROM channels c
WHERE (
		EXISTS (
		    SELECT 1 FROM channel_members cm
		    WHERE cm.channel_id = c.id AND cm.account_id = $1
		)
		OR (
		    c.kind = 0 AND c.group_id IS NOT NULL AND EXISTS (
		        SELECT 1 FROM effective e WHERE e.id = c.group_id AND e.eff_vis = 1
		    )
		)
	)
ORDER BY c.name
`

type ListChannelsRow struct {
	ID                    string
	Name                  string
	GroupID               string
	Kind                  int16
	PostPolicy            int16
	OwnerAccountID        string
	MandatorySubscription bool
}

func (q *Queries) ListChannels(ctx context.Context, accountID string) ([]ListChannelsRow, error) {
	rows, err := q.db.Query(ctx, listChannels, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelsRow
	for rows.Next() {
		var i ListChannelsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.GroupID,
			&i.Kind,
			&i.PostPolicy,
			&i.OwnerAccountID,
			&i.MandatorySubscription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockChannelMandatoryKind = `-- name: LockChannelMandatoryKind :one
SELECT mandatory_subscription, kind FROM channels WHERE id = $1 FOR UPDATE
`

type LockChannelMandatoryKindRow struct {
	MandatorySubscription bool
	Kind                  int16
}

func (q *Queries) LockChannelMandatoryKind(ctx context.Context, id string) (LockChannelMandatoryKindRow, error) {
	row := q.db.QueryRow(ctx, lockChannelMandatoryKind, id)
	var i LockChannelMandatoryKindRow
	err := row.Scan(&i.MandatorySubscription, &i.Kind)
	return i, err
}

const lockChannelPolicy = `-- name: LockChannelPolicy :one
SELECT mandatory_subscription, COALESCE(owner_account_id, '') AS owner_account_id
FROM channels WHERE id = $1 FOR UPDATE
`

type LockChannelPolicyRow struct {
	MandatorySubscription bool
	OwnerAccountID        string
}

func (q *Queries) LockChannelPolicy(ctx context.Context, id string) (LockChannelPolicyRow, error) {
	row := q.db.QueryRow(ctx, lockChannelPolicy, id)
	var i LockChannelPolicyRow
	err := row.Scan(&i.MandatorySubscription, &i.OwnerAccountID)
	return i, err
}

const ownerHasPresentAgent = `-- name: OwnerHasPresentAgent :one
SELECT EXISTS (
    SELECT 1 FROM agent_accounts aa
    JOIN channel_members cm ON cm.account_id = aa.account_id
    WHERE aa.owner_user_id = $1 AND cm.channel_id = $2 AND aa.account_id <> $1
)
`

type OwnerHasPresentAgentParams struct {
	OwnerUserID string
	ChannelID   string
}

func (q *Queries) OwnerHasPresentAgent(ctx context.Context, arg OwnerHasPresentAgentParams) (bool, error) {
	row := q.db.QueryRow(ctx, ownerHasPresentAgent, arg.OwnerUserID, arg.ChannelID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const subscribeConvertedDMParties = `-- name: SubscribeConvertedDMParties :exec
UPDATE channel_members cm SET subscribed = TRUE
FROM agent_accounts aa WHERE aa.account_id = cm.account_id AND cm.channel_id = $1
`

func (q *Queries) SubscribeConvertedDMParties(ctx context.Context, channelID string) error {
	_, err := q.db.Exec(ctx, subscribeConvertedDMParties, channelID)
	return err
}

const updateChannelPolicy = `-- name: UpdateChannelPolicy :exec
UPDATE channels SET post_policy = $2, owner_account_id = NULLIF($3, ''), mandatory_subscription = $4 WHERE id = $1
`

type UpdateChannelPolicyParams struct {
	ID                    string
	PostPolicy            int16
	Column3               interface{}
	MandatorySubscription bool
}

func (q *Queries) UpdateChannelPolicy(ctx context.Context, arg UpdateChannelPolicyParams) error {
	_, err := q.db.Exec(ctx, updateChannelPolicy,
		arg.ID,
		arg.PostPolicy,
		arg.Column3,
		arg.MandatorySubscription,
	)
	return err
}

const upsertChannelMember = `-- name: UpsertChannelMember :exec
INSERT INTO channel_members (channel_id, account_id, subscribed)
VALUES ($1, $2, $3)
ON CONFLICT (channel_id, account_id) DO UPDATE SET subscribed = EXCLUDED.subscribed
`

type UpsertChannelMemberParams struct {
	ChannelID  string
	AccountID  string
	Subscribed bool
}

func (q *Queries) UpsertChannelMember(ctx context.Context, arg UpsertChannelMemberParams) error {
	_, err := q.db.Exec(ctx, upsertChannelMember, arg.ChannelID, arg.AccountID, arg.Subscribed)
	return err
}
