// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channel_pins.sql

package db

import (
	"context"
)

const countChannelPins = `-- name: CountChannelPins :one
SELECT count(*) AS count, COALESCE(MAX(position), -1) + 1 AS next_position
FROM channel_pins WHERE channel_id = $1
`

type CountChannelPinsRow struct {
	Count        int64
	NextPosition int32
}

func (q *Queries) CountChannelPins(ctx context.Context, channelID string) (CountChannelPinsRow, error) {
	row := q.db.QueryRow(ctx, countChannelPins, channelID)
	var i CountChannelPinsRow
	err := row.Scan(&i.Count, &i.NextPosition)
	return i, err
}

const deleteChannelPin = `-- name: DeleteChannelPin :exec
DELETE FROM channel_pins WHERE channel_id = $1 AND message_id = $2
`

type DeleteChannelPinParams struct {
	ChannelID string
	MessageID string
}

func (q *Queries) DeleteChannelPin(ctx context.Context, arg DeleteChannelPinParams) error {
	_, err := q.db.Exec(ctx, deleteChannelPin, arg.ChannelID, arg.MessageID)
	return err
}

const deleteChannelPinReturningPosition = `-- name: DeleteChannelPinReturningPosition :one
DELETE FROM channel_pins WHERE channel_id = $1 AND message_id = $2 RETURNING position
`

type DeleteChannelPinReturningPositionParams struct {
	ChannelID string
	MessageID string
}

func (q *Queries) DeleteChannelPinReturningPosition(ctx context.Context, arg DeleteChannelPinReturningPositionParams) (int32, error) {
	row := q.db.QueryRow(ctx, deleteChannelPinReturningPosition, arg.ChannelID, arg.MessageID)
	var position int32
	err := row.Scan(&position)
	return position, err
}

const insertChannelPin = `-- name: InsertChannelPin :exec
INSERT INTO channel_pins (channel_id, message_id, position, pinned_at_unix_ms, pinned_by_account_id)
VALUES ($1, $2, $3, $4, $5)
`

type InsertChannelPinParams struct {
	ChannelID         string
	MessageID         string
	Position          int32
	PinnedAtUnixMs    int64
	PinnedByAccountID string
}

func (q *Queries) InsertChannelPin(ctx context.Context, arg InsertChannelPinParams) error {
	_, err := q.db.Exec(ctx, insertChannelPin,
		arg.ChannelID,
		arg.MessageID,
		arg.Position,
		arg.PinnedAtUnixMs,
		arg.PinnedByAccountID,
	)
	return err
}

const lockChannelForPins = `-- name: LockChannelForPins :one

SELECT post_policy, COALESCE(owner_account_id, '') AS owner_account_id
FROM channels WHERE id = $1 FOR UPDATE
`

type LockChannelForPinsRow struct {
	PostPolicy     int16
	OwnerAccountID string
}

// Channel-pins (pinned board) queries (sqlc adoption T3, RIG-3034). These
// replace the inline SQL literals in internal/store/channel_pins.go; the
// hand-written Store methods and the in-tx FOR UPDATE lock / cap-check control
// flow stay exactly as they were and wrap these generated calls.
func (q *Queries) LockChannelForPins(ctx context.Context, id string) (LockChannelForPinsRow, error) {
	row := q.db.QueryRow(ctx, lockChannelForPins, id)
	var i LockChannelForPinsRow
	err := row.Scan(&i.PostPolicy, &i.OwnerAccountID)
	return i, err
}

const messageInChannel = `-- name: MessageInChannel :one
SELECT 1 FROM messages m JOIN topics t ON t.id = m.topic_id
WHERE m.id = $1 AND t.channel_id = $2
`

type MessageInChannelParams struct {
	ID        string
	ChannelID string
}

func (q *Queries) MessageInChannel(ctx context.Context, arg MessageInChannelParams) (int32, error) {
	row := q.db.QueryRow(ctx, messageInChannel, arg.ID, arg.ChannelID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const pinnedEntries = `-- name: PinnedEntries :many
SELECT message_id, position, pinned_at_unix_ms, pinned_by_account_id
FROM channel_pins WHERE channel_id = $1 ORDER BY position
`

type PinnedEntriesRow struct {
	MessageID         string
	Position          int32
	PinnedAtUnixMs    int64
	PinnedByAccountID string
}

func (q *Queries) PinnedEntries(ctx context.Context, channelID string) ([]PinnedEntriesRow, error) {
	rows, err := q.db.Query(ctx, pinnedEntries, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PinnedEntriesRow
	for rows.Next() {
		var i PinnedEntriesRow
		if err := rows.Scan(
			&i.MessageID,
			&i.Position,
			&i.PinnedAtUnixMs,
			&i.PinnedByAccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
