// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: coordination.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const channelMemberIDs = `-- name: ChannelMemberIDs :many
SELECT account_id FROM channel_members WHERE channel_id = $1
`

func (q *Queries) ChannelMemberIDs(ctx context.Context, channelID string) ([]string, error) {
	rows, err := q.db.Query(ctx, channelMemberIDs, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var account_id string
		if err := rows.Scan(&account_id); err != nil {
			return nil, err
		}
		items = append(items, account_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const coordinationReports = `-- name: CoordinationReports :many
SELECT account_id FROM agent_accounts WHERE parent_agent_id = $1 ORDER BY account_id
`

func (q *Queries) CoordinationReports(ctx context.Context, parentAgentID pgtype.Text) ([]string, error) {
	rows, err := q.db.Query(ctx, coordinationReports, parentAgentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var account_id string
		if err := rows.Scan(&account_id); err != nil {
			return nil, err
		}
		items = append(items, account_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCoordinationChannelByName = `-- name: GetCoordinationChannelByName :one
SELECT id, COALESCE(owner_account_id, '') AS owner_account_id
FROM channels WHERE group_id = $1 AND name = $2
`

type GetCoordinationChannelByNameParams struct {
	GroupID pgtype.Text
	Name    string
}

type GetCoordinationChannelByNameRow struct {
	ID             string
	OwnerAccountID string
}

func (q *Queries) GetCoordinationChannelByName(ctx context.Context, arg GetCoordinationChannelByNameParams) (GetCoordinationChannelByNameRow, error) {
	row := q.db.QueryRow(ctx, getCoordinationChannelByName, arg.GroupID, arg.Name)
	var i GetCoordinationChannelByNameRow
	err := row.Scan(&i.ID, &i.OwnerAccountID)
	return i, err
}

const getCoordinationGroup = `-- name: GetCoordinationGroup :one

SELECT id FROM channel_groups
WHERE owner_user_id = $1 AND name = $2 AND parent_group_id IS NULL AND visibility = $3
`

type GetCoordinationGroupParams struct {
	OwnerUserID string
	Name        string
	Visibility  int16
}

// Coordination-store queries (sqlc adoption T3, RIG-3034). These replace the
// inline SQL literals in internal/store/coordination.go; the hand-written Store
// methods keep their signatures, the per-owner advisory-lock discipline, the
// suffix-search resolution loop, and the WithTx seam (which stays hand-written).
// The member INSERT/DELETE reuse EnsureChannelMember (accounts.sql) and
// DeleteChannelMember (channels.sql) — the statements are identical.
func (q *Queries) GetCoordinationGroup(ctx context.Context, arg GetCoordinationGroupParams) (string, error) {
	row := q.db.QueryRow(ctx, getCoordinationGroup, arg.OwnerUserID, arg.Name, arg.Visibility)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertCoordinationChannel = `-- name: InsertCoordinationChannel :one
INSERT INTO channels (id, name, group_id, kind, post_policy, owner_account_id, mandatory_subscription)
VALUES ($1, $2, $3, $4, $5, NULLIF($6, ''), $7)
ON CONFLICT (group_id, name) WHERE group_id IS NOT NULL DO NOTHING
RETURNING id
`

type InsertCoordinationChannelParams struct {
	ID                    string
	Name                  string
	GroupID               pgtype.Text
	Kind                  int16
	PostPolicy            int16
	Column6               interface{}
	MandatorySubscription bool
}

func (q *Queries) InsertCoordinationChannel(ctx context.Context, arg InsertCoordinationChannelParams) (string, error) {
	row := q.db.QueryRow(ctx, insertCoordinationChannel,
		arg.ID,
		arg.Name,
		arg.GroupID,
		arg.Kind,
		arg.PostPolicy,
		arg.Column6,
		arg.MandatorySubscription,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertCoordinationGroup = `-- name: InsertCoordinationGroup :exec
INSERT INTO channel_groups (id, name, parent_group_id, owner_user_id, visibility)
VALUES ($1, $2, NULL, $3, $4)
`

type InsertCoordinationGroupParams struct {
	ID          string
	Name        string
	OwnerUserID string
	Visibility  int16
}

func (q *Queries) InsertCoordinationGroup(ctx context.Context, arg InsertCoordinationGroupParams) error {
	_, err := q.db.Exec(ctx, insertCoordinationGroup,
		arg.ID,
		arg.Name,
		arg.OwnerUserID,
		arg.Visibility,
	)
	return err
}

const lockOwnerCoordination = `-- name: LockOwnerCoordination :exec
SELECT pg_advisory_xact_lock(hashtext('coordination:' || $1))
`

func (q *Queries) LockOwnerCoordination(ctx context.Context, dollar_1 pgtype.Text) error {
	_, err := q.db.Exec(ctx, lockOwnerCoordination, dollar_1)
	return err
}

const resolveCoordinationManager = `-- name: ResolveCoordinationManager :one
SELECT a.handle, ag.owner_user_id
FROM accounts a
JOIN agent_accounts ag ON ag.account_id = a.id
WHERE a.id = $1
`

type ResolveCoordinationManagerRow struct {
	Handle      string
	OwnerUserID string
}

func (q *Queries) ResolveCoordinationManager(ctx context.Context, id string) (ResolveCoordinationManagerRow, error) {
	row := q.db.QueryRow(ctx, resolveCoordinationManager, id)
	var i ResolveCoordinationManagerRow
	err := row.Scan(&i.Handle, &i.OwnerUserID)
	return i, err
}
