// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delivery_reads.sql

package db

import (
	"context"
)

const channelAgentMembers = `-- name: ChannelAgentMembers :many
SELECT aa.account_id, aa.owner_user_id,
       COALESCE(oh.handle, '') AS owner_handle, COALESCE(ah.handle, '') AS handle
FROM channel_members cm
JOIN agent_accounts aa ON aa.account_id = cm.account_id
LEFT JOIN account_handles ah ON ah.account_id = aa.account_id
    AND ah.owner_user_id = aa.owner_user_id AND ah.tenant_id = aa.tenant_id
LEFT JOIN account_handles oh ON oh.account_id = aa.owner_user_id
    AND oh.owner_user_id IS NULL AND oh.tenant_id = aa.tenant_id
WHERE cm.channel_id = $1
  AND cm.account_id <> $2
  AND
(   aa.owner_user_id = COALESCE((SELECT owner_user_id FROM agent_accounts WHERE account_id = $2), $2)
 OR EXISTS (SELECT 1 FROM system_accounts sy WHERE sy.account_id = $2)
 OR EXISTS (SELECT 1 FROM user_peers p_out
            JOIN user_peers p_in ON p_in.user_id = p_out.peer_user_id AND p_in.peer_user_id = p_out.user_id
            WHERE p_out.user_id = COALESCE((SELECT owner_user_id FROM agent_accounts WHERE account_id = $2), $2)
              AND p_out.peer_user_id = aa.owner_user_id)
)
ORDER BY aa.account_id
`

type ChannelAgentMembersParams struct {
	ChannelID string
	AccountID string
}

type ChannelAgentMembersRow struct {
	AccountID   string
	OwnerUserID string
	OwnerHandle string
	Handle      string
}

// Keep handle joins optional so missing handle rows do not hide @everyone members.
// reach: the author may reach agent aa
func (q *Queries) ChannelAgentMembers(ctx context.Context, arg ChannelAgentMembersParams) ([]ChannelAgentMembersRow, error) {
	rows, err := q.db.Query(ctx, channelAgentMembers, arg.ChannelID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelAgentMembersRow
	for rows.Next() {
		var i ChannelAgentMembersRow
		if err := rows.Scan(
			&i.AccountID,
			&i.OwnerUserID,
			&i.OwnerHandle,
			&i.Handle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isAgentAccount = `-- name: IsAgentAccount :one
SELECT EXISTS (SELECT 1 FROM agent_accounts WHERE account_id = $1)
`

func (q *Queries) IsAgentAccount(ctx context.Context, accountID string) (bool, error) {
	row := q.db.QueryRow(ctx, isAgentAccount, accountID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const messageByID = `-- name: MessageByID :one
SELECT m.id, m.topic_id, m.author_account_id, (CASE WHEN ah.owner_user_id IS NULL THEN COALESCE(ah.handle, '') WHEN oh.handle IS NULL THEN '' ELSE oh.handle || '/' || ah.handle END)::text AS author_handle, m.at_unix_ms, m.blocks, m.turn_sequence
FROM messages m
LEFT JOIN account_handles ah ON ah.account_id = m.author_account_id
LEFT JOIN account_handles oh ON oh.account_id = ah.owner_user_id
WHERE m.id = $1
`

type MessageByIDRow struct {
	ID              string
	TopicID         string
	AuthorAccountID string
	AuthorHandle    string
	AtUnixMs        int64
	Blocks          []byte
	TurnSequence    int64
}

func (q *Queries) MessageByID(ctx context.Context, id string) (MessageByIDRow, error) {
	row := q.db.QueryRow(ctx, messageByID, id)
	var i MessageByIDRow
	err := row.Scan(
		&i.ID,
		&i.TopicID,
		&i.AuthorAccountID,
		&i.AuthorHandle,
		&i.AtUnixMs,
		&i.Blocks,
		&i.TurnSequence,
	)
	return i, err
}

const messageChannel = `-- name: MessageChannel :one
SELECT t.channel_id FROM messages m JOIN topics t ON t.id = m.topic_id WHERE m.id = $1
`

func (q *Queries) MessageChannel(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, messageChannel, id)
	var channel_id string
	err := row.Scan(&channel_id)
	return channel_id, err
}

const subscribedAgents = `-- name: SubscribedAgents :many

SELECT aa.account_id
FROM channel_members cm
JOIN agent_accounts aa ON aa.account_id = cm.account_id
JOIN channels ch ON ch.id = cm.channel_id
WHERE cm.channel_id = $1
  AND (cm.subscribed OR cm.channel_id = aa.home_channel_id OR ch.mandatory_subscription)
  AND cm.account_id <> $2
  AND
(   aa.owner_user_id = COALESCE((SELECT owner_user_id FROM agent_accounts WHERE account_id = $2), $2)
 OR EXISTS (SELECT 1 FROM system_accounts sy WHERE sy.account_id = $2)
 OR EXISTS (SELECT 1 FROM user_peers p_out
            JOIN user_peers p_in ON p_in.user_id = p_out.peer_user_id AND p_in.peer_user_id = p_out.user_id
            WHERE p_out.user_id = COALESCE((SELECT owner_user_id FROM agent_accounts WHERE account_id = $2), $2)
              AND p_out.peer_user_id = aa.owner_user_id)
)
ORDER BY aa.account_id
`

type SubscribedAgentsParams struct {
	ChannelID string
	AccountID string
}

// Delivery-consumer read queries. The recipient sets are reach-gated: a member
// outside the author's owner or live peering is absent from these results.
// Keep the marked reach predicate in sync with delivery_cursors.sql.
// MessageByID shares the message projection the Go drains via messageFromParts.
// reach: the author may reach agent aa
func (q *Queries) SubscribedAgents(ctx context.Context, arg SubscribedAgentsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, subscribedAgents, arg.ChannelID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var account_id string
		if err := rows.Scan(&account_id); err != nil {
			return nil, err
		}
		items = append(items, account_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sweepChannels = `-- name: SweepChannels :many
SELECT cm.channel_id
FROM channel_members cm
JOIN agent_accounts aa ON aa.account_id = cm.account_id
JOIN channels ch ON ch.id = cm.channel_id
WHERE cm.account_id = $1
  AND (cm.subscribed OR cm.channel_id = aa.home_channel_id OR ch.mandatory_subscription)
ORDER BY cm.channel_id
`

func (q *Queries) SweepChannels(ctx context.Context, accountID string) ([]string, error) {
	rows, err := q.db.Query(ctx, sweepChannels, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var channel_id string
		if err := rows.Scan(&channel_id); err != nil {
			return nil, err
		}
		items = append(items, channel_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topicChannelNames = `-- name: TopicChannelNames :one
SELECT t.name AS topic_name, c.name AS channel_name FROM topics t JOIN channels c ON c.id = t.channel_id WHERE t.id = $1
`

type TopicChannelNamesRow struct {
	TopicName   string
	ChannelName string
}

func (q *Queries) TopicChannelNames(ctx context.Context, id string) (TopicChannelNamesRow, error) {
	row := q.db.QueryRow(ctx, topicChannelNames, id)
	var i TopicChannelNamesRow
	err := row.Scan(&i.TopicName, &i.ChannelName)
	return i, err
}
