// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dm.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDMChannelByName = `-- name: GetDMChannelByName :one
SELECT id, kind FROM channels WHERE group_id = $1 AND name = $2
`

type GetDMChannelByNameParams struct {
	GroupID pgtype.Text
	Name    string
}

type GetDMChannelByNameRow struct {
	ID   string
	Kind int16
}

func (q *Queries) GetDMChannelByName(ctx context.Context, arg GetDMChannelByNameParams) (GetDMChannelByNameRow, error) {
	row := q.db.QueryRow(ctx, getDMChannelByName, arg.GroupID, arg.Name)
	var i GetDMChannelByNameRow
	err := row.Scan(&i.ID, &i.Kind)
	return i, err
}

const getGroupNameVisibility = `-- name: GetGroupNameVisibility :one
SELECT name, visibility FROM channel_groups WHERE id = $1
`

type GetGroupNameVisibilityRow struct {
	Name       string
	Visibility int16
}

// Feeds isReservedDMGroupTx: the reserved-DM-group discriminator (name AND
// VisibilityOwner) the CreateChannel create-guard keys on.
func (q *Queries) GetGroupNameVisibility(ctx context.Context, id string) (GetGroupNameVisibilityRow, error) {
	row := q.db.QueryRow(ctx, getGroupNameVisibility, id)
	var i GetGroupNameVisibilityRow
	err := row.Scan(&i.Name, &i.Visibility)
	return i, err
}

const getOwnerDMGroup = `-- name: GetOwnerDMGroup :one

SELECT id FROM channel_groups
WHERE owner_user_id = $1 AND name = $2 AND parent_group_id IS NULL AND visibility = $3
`

type GetOwnerDMGroupParams struct {
	OwnerUserID string
	Name        string
	Visibility  int16
}

// Peer-DM channel queries (sqlc adoption T6, RIG-3034; dm.go was added to the
// store after the design record froze — the record's "plus any residue"). These
// replace the inline SQL literals in internal/store/dm.go; the hand-written Store
// methods keep their signatures and every seam that is NOT a single statement:
// the per-owner advisory lock (LockDM), the resolution/insert loop, the R3
// verify-reconcile belt, the transitive-owner membership expansion, and the
// cursor seeding (seedChannelDeliveryCursors, delivery_cursors.sql). The member
// INSERTs reuse EnsureChannelMember (accounts.sql) — the statement is identical.
// Visibility-discriminated get-half: a wider (SHARED) planted __dm__ group must
// NEVER be adopted, so visibility = $3 (bound to VisibilityOwner) excludes it.
func (q *Queries) GetOwnerDMGroup(ctx context.Context, arg GetOwnerDMGroupParams) (string, error) {
	row := q.db.QueryRow(ctx, getOwnerDMGroup, arg.OwnerUserID, arg.Name, arg.Visibility)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertDMChannel = `-- name: InsertDMChannel :one
INSERT INTO channels (id, name, group_id, kind, post_policy, owner_account_id, mandatory_subscription)
VALUES ($1, $2, $3, $4, $5, NULL, $6)
ON CONFLICT (group_id, name) WHERE group_id IS NOT NULL DO NOTHING
RETURNING id
`

type InsertDMChannelParams struct {
	ID                    string
	Name                  string
	GroupID               pgtype.Text
	Kind                  int16
	PostPolicy            int16
	MandatorySubscription bool
}

// Born kind=DM, zero-value policy (OPEN, ownerless) + mandatory; poison-free via
// ON CONFLICT DO NOTHING on the partial unique index (a concurrent open yields
// zero rows, never a raised unique-violation).
func (q *Queries) InsertDMChannel(ctx context.Context, arg InsertDMChannelParams) (string, error) {
	row := q.db.QueryRow(ctx, insertDMChannel,
		arg.ID,
		arg.Name,
		arg.GroupID,
		arg.Kind,
		arg.PostPolicy,
		arg.MandatorySubscription,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertOwnerDMGroup = `-- name: InsertOwnerDMGroup :exec
INSERT INTO channel_groups (id, name, parent_group_id, owner_user_id, visibility)
VALUES ($1, $2, NULL, $3, $4)
`

type InsertOwnerDMGroupParams struct {
	ID          string
	Name        string
	OwnerUserID string
	Visibility  int16
}

func (q *Queries) InsertOwnerDMGroup(ctx context.Context, arg InsertOwnerDMGroupParams) error {
	_, err := q.db.Exec(ctx, insertOwnerDMGroup,
		arg.ID,
		arg.Name,
		arg.OwnerUserID,
		arg.Visibility,
	)
	return err
}

const lockOwnerDM = `-- name: LockOwnerDM :exec
SELECT pg_advisory_xact_lock(hashtext('dm:' || $1))
`

func (q *Queries) LockOwnerDM(ctx context.Context, dollar_1 pgtype.Text) error {
	_, err := q.db.Exec(ctx, lockOwnerDM, dollar_1)
	return err
}

const reassertDMMandatory = `-- name: ReassertDMMandatory :exec
UPDATE channels SET mandatory_subscription = TRUE WHERE id = $1 AND mandatory_subscription = FALSE
`

func (q *Queries) ReassertDMMandatory(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, reassertDMMandatory, id)
	return err
}
