// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: forge_cursors.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ensureForgeRepoSubscription = `-- name: EnsureForgeRepoSubscription :exec
INSERT INTO forge_repo_subscriptions (forge_provider, forge_host, repo, enabled)
VALUES ($1, $2, $3, $4)
ON CONFLICT (forge_provider, forge_host, repo) DO NOTHING
`

type EnsureForgeRepoSubscriptionParams struct {
	ForgeProvider int16
	ForgeHost     string
	Repo          string
	Enabled       bool
}

func (q *Queries) EnsureForgeRepoSubscription(ctx context.Context, arg EnsureForgeRepoSubscriptionParams) error {
	_, err := q.db.Exec(ctx, ensureForgeRepoSubscription,
		arg.ForgeProvider,
		arg.ForgeHost,
		arg.Repo,
		arg.Enabled,
	)
	return err
}

const isEnabledForgeRepo = `-- name: IsEnabledForgeRepo :one
SELECT EXISTS (
  SELECT 1 FROM forge_repo_subscriptions
   WHERE repo = $1 AND enabled = TRUE)
`

func (q *Queries) IsEnabledForgeRepo(ctx context.Context, repo string) (bool, error) {
	row := q.db.QueryRow(ctx, isEnabledForgeRepo, repo)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listEnabledForgeRepoSubscriptions = `-- name: ListEnabledForgeRepoSubscriptions :many
SELECT forge_provider, forge_host, repo, enabled
FROM forge_repo_subscriptions
WHERE forge_provider = $1 AND forge_host = $2 AND enabled = TRUE
ORDER BY repo ASC
`

type ListEnabledForgeRepoSubscriptionsParams struct {
	ForgeProvider int16
	ForgeHost     string
}

type ListEnabledForgeRepoSubscriptionsRow struct {
	ForgeProvider int16
	ForgeHost     string
	Repo          string
	Enabled       bool
}

func (q *Queries) ListEnabledForgeRepoSubscriptions(ctx context.Context, arg ListEnabledForgeRepoSubscriptionsParams) ([]ListEnabledForgeRepoSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, listEnabledForgeRepoSubscriptions, arg.ForgeProvider, arg.ForgeHost)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnabledForgeRepoSubscriptionsRow
	for rows.Next() {
		var i ListEnabledForgeRepoSubscriptionsRow
		if err := rows.Scan(
			&i.ForgeProvider,
			&i.ForgeHost,
			&i.Repo,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledForgeRepos = `-- name: ListEnabledForgeRepos :many
SELECT repo
FROM forge_repo_subscriptions
WHERE enabled = TRUE
ORDER BY repo ASC
`

func (q *Queries) ListEnabledForgeRepos(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listEnabledForgeRepos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var repo string
		if err := rows.Scan(&repo); err != nil {
			return nil, err
		}
		items = append(items, repo)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadForgeRepoWatermark = `-- name: LoadForgeRepoWatermark :one

SELECT swept_updated_at, list_etag
FROM forge_repo_subscriptions
WHERE forge_provider = $1 AND forge_host = $2 AND repo = $3
`

type LoadForgeRepoWatermarkParams struct {
	ForgeProvider int16
	ForgeHost     string
	Repo          string
}

type LoadForgeRepoWatermarkRow struct {
	SweptUpdatedAt pgtype.Timestamptz
	ListEtag       string
}

// Forge repo-subscription / watermark queries (sqlc adoption T6, RIG-3034). These
// replace the inline SQL literals in internal/store/forge_cursors.go; the
// hand-written Store methods keep their signatures, the door-side validation
// (validCoordinate), the ErrNotFound mapping, and the RowsAffected branches
// (StoreForgeRepoWatermark / SetForgeRepoSubscriptionEnabled are :execrows). The
// read methods map the generated rows (provider int, nullable swept_updated_at)
// back to the domain time.Time / ForgeRepoSubscription.
func (q *Queries) LoadForgeRepoWatermark(ctx context.Context, arg LoadForgeRepoWatermarkParams) (LoadForgeRepoWatermarkRow, error) {
	row := q.db.QueryRow(ctx, loadForgeRepoWatermark, arg.ForgeProvider, arg.ForgeHost, arg.Repo)
	var i LoadForgeRepoWatermarkRow
	err := row.Scan(&i.SweptUpdatedAt, &i.ListEtag)
	return i, err
}

const setForgeRepoSubscriptionEnabled = `-- name: SetForgeRepoSubscriptionEnabled :execrows
UPDATE forge_repo_subscriptions
   SET enabled = $4, updated_at = now()
 WHERE forge_provider = $1 AND forge_host = $2 AND repo = $3
`

type SetForgeRepoSubscriptionEnabledParams struct {
	ForgeProvider int16
	ForgeHost     string
	Repo          string
	Enabled       bool
}

func (q *Queries) SetForgeRepoSubscriptionEnabled(ctx context.Context, arg SetForgeRepoSubscriptionEnabledParams) (int64, error) {
	result, err := q.db.Exec(ctx, setForgeRepoSubscriptionEnabled,
		arg.ForgeProvider,
		arg.ForgeHost,
		arg.Repo,
		arg.Enabled,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const storeForgeRepoWatermark = `-- name: StoreForgeRepoWatermark :execrows
UPDATE forge_repo_subscriptions
   SET swept_updated_at = $4, list_etag = $5, updated_at = now()
 WHERE forge_provider = $1 AND forge_host = $2 AND repo = $3
`

type StoreForgeRepoWatermarkParams struct {
	ForgeProvider  int16
	ForgeHost      string
	Repo           string
	SweptUpdatedAt pgtype.Timestamptz
	ListEtag       string
}

func (q *Queries) StoreForgeRepoWatermark(ctx context.Context, arg StoreForgeRepoWatermarkParams) (int64, error) {
	result, err := q.db.Exec(ctx, storeForgeRepoWatermark,
		arg.ForgeProvider,
		arg.ForgeHost,
		arg.Repo,
		arg.SweptUpdatedAt,
		arg.ListEtag,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
