// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: forge_subscriptions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceForgeDeliveredRevision = `-- name: AdvanceForgeDeliveredRevision :execrows
UPDATE agent_forge_subscriptions
   SET delivered_revision = $3, delivered_at = now()
 WHERE id = $2 AND agent_account_id = $1
`

type AdvanceForgeDeliveredRevisionParams struct {
	AgentAccountID    string
	ID                string
	DeliveredRevision string
}

func (q *Queries) AdvanceForgeDeliveredRevision(ctx context.Context, arg AdvanceForgeDeliveredRevisionParams) (int64, error) {
	result, err := q.db.Exec(ctx, advanceForgeDeliveredRevision, arg.AgentAccountID, arg.ID, arg.DeliveredRevision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countAgentForgeSubscriptionsForArtifact = `-- name: CountAgentForgeSubscriptionsForArtifact :one
SELECT count(*) FROM agent_forge_subscriptions
 WHERE forge_provider = $1 AND forge_host = $2 AND repo = $3 AND kind = $4 AND number = $5
`

type CountAgentForgeSubscriptionsForArtifactParams struct {
	ForgeProvider int16
	ForgeHost     string
	Repo          string
	Kind          int16
	Number        int64
}

func (q *Queries) CountAgentForgeSubscriptionsForArtifact(ctx context.Context, arg CountAgentForgeSubscriptionsForArtifactParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAgentForgeSubscriptionsForArtifact,
		arg.ForgeProvider,
		arg.ForgeHost,
		arg.Repo,
		arg.Kind,
		arg.Number,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAgentForgeSubscription = `-- name: DeleteAgentForgeSubscription :one
DELETE FROM agent_forge_subscriptions
 WHERE id = $1 AND agent_account_id = $2
RETURNING forge_provider, forge_host, repo, kind, number
`

type DeleteAgentForgeSubscriptionParams struct {
	ID             string
	AgentAccountID string
}

type DeleteAgentForgeSubscriptionRow struct {
	ForgeProvider int16
	ForgeHost     string
	Repo          string
	Kind          int16
	Number        int64
}

// Scoped to the calling agent (id AND agent). RETURNING the coordinate drives the
// one-tx GC of the artifact cursor when this was the last subscription.
func (q *Queries) DeleteAgentForgeSubscription(ctx context.Context, arg DeleteAgentForgeSubscriptionParams) (DeleteAgentForgeSubscriptionRow, error) {
	row := q.db.QueryRow(ctx, deleteAgentForgeSubscription, arg.ID, arg.AgentAccountID)
	var i DeleteAgentForgeSubscriptionRow
	err := row.Scan(
		&i.ForgeProvider,
		&i.ForgeHost,
		&i.Repo,
		&i.Kind,
		&i.Number,
	)
	return i, err
}

const ensureAgentForgeSubscription = `-- name: EnsureAgentForgeSubscription :one

INSERT INTO agent_forge_subscriptions
    (id, agent_account_id, forge_provider, forge_host, repo, kind, number, scope, project)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (agent_account_id, forge_provider, forge_host, repo, kind, number, project) DO UPDATE
   SET agent_account_id = EXCLUDED.agent_account_id
RETURNING id
`

type EnsureAgentForgeSubscriptionParams struct {
	ID             string
	AgentAccountID string
	ForgeProvider  int16
	ForgeHost      string
	Repo           string
	Kind           int16
	Number         int64
	Scope          int16
	Project        string
}

// Agent-forge-subscription / artifact-cursor queries (sqlc adoption T6,
// RIG-3034). These replace the inline SQL literals in
// internal/store/forge_subscriptions.go; the hand-written Store methods keep
// their signatures, the door-side validation (validSubscriptionCoordinate /
// validCoordinate), the scope normalization, the ErrConflict/ErrInvalidArgument/
// ErrNotFound mapping via pgErrIs, and the two hand-written tx seams: the
// DeleteAgentForgeSubscription GC (WithTx) and the ListForgeNotifyTargets row
// grouping. The read queries feed the ForgeNotifySubscriber / ForgeArtifactCursor
// / ForgeNotifyTarget mappers, which convert the generated rows (provider/kind
// ints, BIGINT numbers, LEFT-JOIN-nullable cursor columns) back to the domain
// types.
// Idempotent on the UNIQUE coordinate: the no-op DO UPDATE (re-set agent to
// itself) makes RETURNING fire on conflict so a repeat returns the stored id.
func (q *Queries) EnsureAgentForgeSubscription(ctx context.Context, arg EnsureAgentForgeSubscriptionParams) (string, error) {
	row := q.db.QueryRow(ctx, ensureAgentForgeSubscription,
		arg.ID,
		arg.AgentAccountID,
		arg.ForgeProvider,
		arg.ForgeHost,
		arg.Repo,
		arg.Kind,
		arg.Number,
		arg.Scope,
		arg.Project,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const gCForgeArtifactCursorIfUnsubscribed = `-- name: GCForgeArtifactCursorIfUnsubscribed :exec
DELETE FROM forge_artifact_cursors
 WHERE forge_artifact_cursors.forge_provider = $1 AND forge_artifact_cursors.forge_host = $2 AND forge_artifact_cursors.repo = $3 AND forge_artifact_cursors.kind = $4 AND forge_artifact_cursors.number = $5
   AND NOT EXISTS (
       SELECT 1 FROM agent_forge_subscriptions
        WHERE agent_forge_subscriptions.forge_provider = $1 AND agent_forge_subscriptions.forge_host = $2 AND agent_forge_subscriptions.repo = $3 AND agent_forge_subscriptions.kind = $4 AND agent_forge_subscriptions.number = $5
   )
`

type GCForgeArtifactCursorIfUnsubscribedParams struct {
	ForgeProvider int16
	ForgeHost     string
	Repo          string
	Kind          int16
	Number        int64
}

// Collects the coordinate's cursor IFF no subscription for it remains (the NOT
// EXISTS guard leaves it in place if any other agent still subscribes).
func (q *Queries) GCForgeArtifactCursorIfUnsubscribed(ctx context.Context, arg GCForgeArtifactCursorIfUnsubscribedParams) error {
	_, err := q.db.Exec(ctx, gCForgeArtifactCursorIfUnsubscribed,
		arg.ForgeProvider,
		arg.ForgeHost,
		arg.Repo,
		arg.Kind,
		arg.Number,
	)
	return err
}

const listForgeNotifyTargets = `-- name: ListForgeNotifyTargets :many
SELECT s.repo, s.kind,
       (CASE WHEN s.scope = 2 THEN 0 ELSE s.number END)::BIGINT AS coord_number,
       s.id, s.agent_account_id, s.delivered_revision, s.project,
       (c.forge_provider IS NOT NULL)::boolean AS has_cursor,
       c.etag, c.comments_etag, c.checks_etag, c.revision, c.snapshot, c.polled_at
FROM agent_forge_subscriptions s
LEFT JOIN forge_artifact_cursors c
  ON c.forge_provider = s.forge_provider
 AND c.forge_host = s.forge_host
 AND c.repo = s.repo
 AND c.kind = s.kind
 AND c.number = CASE WHEN s.scope = 2 THEN 0 ELSE s.number END
WHERE s.forge_provider = $1 AND s.forge_host = $2
ORDER BY s.repo, s.kind, coord_number
`

type ListForgeNotifyTargetsParams struct {
	ForgeProvider int16
	ForgeHost     string
}

type ListForgeNotifyTargetsRow struct {
	Repo              string
	Kind              int16
	CoordNumber       int64
	ID                string
	AgentAccountID    string
	DeliveredRevision string
	Project           string
	HasCursor         bool
	Etag              pgtype.Text
	CommentsEtag      pgtype.Text
	ChecksEtag        pgtype.Text
	Revision          pgtype.Text
	Snapshot          []byte
	PolledAt          pgtype.Timestamptz
}

// The reconcile sweep's work list for one (provider, host): each subscribed
// coordinate with its LEFT-JOINed shared FETCH cursor (nullable when never
// observed) and the subscriber rows, container-scope rows collapsed per
// (repo, kind) to coord_number 0. The Go groups the flat rows into targets.
func (q *Queries) ListForgeNotifyTargets(ctx context.Context, arg ListForgeNotifyTargetsParams) ([]ListForgeNotifyTargetsRow, error) {
	rows, err := q.db.Query(ctx, listForgeNotifyTargets, arg.ForgeProvider, arg.ForgeHost)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListForgeNotifyTargetsRow
	for rows.Next() {
		var i ListForgeNotifyTargetsRow
		if err := rows.Scan(
			&i.Repo,
			&i.Kind,
			&i.CoordNumber,
			&i.ID,
			&i.AgentAccountID,
			&i.DeliveredRevision,
			&i.Project,
			&i.HasCursor,
			&i.Etag,
			&i.CommentsEtag,
			&i.ChecksEtag,
			&i.Revision,
			&i.Snapshot,
			&i.PolledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadForgeArtifactCursor = `-- name: LoadForgeArtifactCursor :one
SELECT etag, comments_etag, checks_etag, revision, snapshot, polled_at
FROM forge_artifact_cursors
WHERE forge_provider = $1 AND forge_host = $2 AND repo = $3 AND kind = $4 AND number = $5
`

type LoadForgeArtifactCursorParams struct {
	ForgeProvider int16
	ForgeHost     string
	Repo          string
	Kind          int16
	Number        int64
}

type LoadForgeArtifactCursorRow struct {
	Etag         string
	CommentsEtag string
	ChecksEtag   string
	Revision     string
	Snapshot     []byte
	PolledAt     pgtype.Timestamptz
}

func (q *Queries) LoadForgeArtifactCursor(ctx context.Context, arg LoadForgeArtifactCursorParams) (LoadForgeArtifactCursorRow, error) {
	row := q.db.QueryRow(ctx, loadForgeArtifactCursor,
		arg.ForgeProvider,
		arg.ForgeHost,
		arg.Repo,
		arg.Kind,
		arg.Number,
	)
	var i LoadForgeArtifactCursorRow
	err := row.Scan(
		&i.Etag,
		&i.CommentsEtag,
		&i.ChecksEtag,
		&i.Revision,
		&i.Snapshot,
		&i.PolledAt,
	)
	return i, err
}

const subscribersForArtifact = `-- name: SubscribersForArtifact :many
SELECT id, agent_account_id, delivered_revision, project
FROM agent_forge_subscriptions
WHERE forge_provider = $1 AND forge_host = $2 AND repo = $3 AND kind = $4
  AND (
        (scope = 1 AND number = $5)
     OR ($6::boolean AND scope = 2 AND number = 0 AND project = $7)
  )
`

type SubscribersForArtifactParams struct {
	ForgeProvider int16
	ForgeHost     string
	Repo          string
	Kind          int16
	Number        int64
	Column6       bool
	Project       string
}

type SubscribersForArtifactRow struct {
	ID                string
	AgentAccountID    string
	DeliveredRevision string
	Project           string
}

// Exact-artifact subscribers, plus (on an opened event) the container-scope
// subscribers for the same container/project.
func (q *Queries) SubscribersForArtifact(ctx context.Context, arg SubscribersForArtifactParams) ([]SubscribersForArtifactRow, error) {
	rows, err := q.db.Query(ctx, subscribersForArtifact,
		arg.ForgeProvider,
		arg.ForgeHost,
		arg.Repo,
		arg.Kind,
		arg.Number,
		arg.Column6,
		arg.Project,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubscribersForArtifactRow
	for rows.Next() {
		var i SubscribersForArtifactRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentAccountID,
			&i.DeliveredRevision,
			&i.Project,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertForgeArtifactCursor = `-- name: UpsertForgeArtifactCursor :exec
INSERT INTO forge_artifact_cursors
    (forge_provider, forge_host, repo, kind, number, etag, comments_etag, checks_etag, revision, snapshot, polled_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (forge_provider, forge_host, repo, kind, number) DO UPDATE
   SET etag = EXCLUDED.etag,
       comments_etag = EXCLUDED.comments_etag,
       checks_etag = EXCLUDED.checks_etag,
       revision = EXCLUDED.revision,
       snapshot = EXCLUDED.snapshot,
       polled_at = EXCLUDED.polled_at
`

type UpsertForgeArtifactCursorParams struct {
	ForgeProvider int16
	ForgeHost     string
	Repo          string
	Kind          int16
	Number        int64
	Etag          string
	CommentsEtag  string
	ChecksEtag    string
	Revision      string
	Snapshot      []byte
	PolledAt      pgtype.Timestamptz
}

func (q *Queries) UpsertForgeArtifactCursor(ctx context.Context, arg UpsertForgeArtifactCursorParams) error {
	_, err := q.db.Exec(ctx, upsertForgeArtifactCursor,
		arg.ForgeProvider,
		arg.ForgeHost,
		arg.Repo,
		arg.Kind,
		arg.Number,
		arg.Etag,
		arg.CommentsEtag,
		arg.ChecksEtag,
		arg.Revision,
		arg.Snapshot,
		arg.PolledAt,
	)
	return err
}
