// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: forge_scopes.sql

package db

import (
	"context"
)

const forgeScopeUserExists = `-- name: ForgeScopeUserExists :one
SELECT EXISTS (SELECT 1 FROM user_accounts WHERE account_id = $1)
`

func (q *Queries) ForgeScopeUserExists(ctx context.Context, accountID string) (bool, error) {
	row := q.db.QueryRow(ctx, forgeScopeUserExists, accountID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const grantAgentForgeScope = `-- name: GrantAgentForgeScope :execrows
INSERT INTO account_forge_scopes (account_id, forge_provider, forge_host, repo)
SELECT a.account_id, $1, $2, $3
FROM agent_accounts AS a
WHERE a.account_id = $4
ON CONFLICT DO NOTHING
`

type GrantAgentForgeScopeParams struct {
	ForgeProvider int16
	ForgeHost     string
	Repo          string
	AccountID     string
}

// Server-written workstream row; the SELECT runs under RLS.
func (q *Queries) GrantAgentForgeScope(ctx context.Context, arg GrantAgentForgeScopeParams) (int64, error) {
	result, err := q.db.Exec(ctx, grantAgentForgeScope,
		arg.ForgeProvider,
		arg.ForgeHost,
		arg.Repo,
		arg.AccountID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const grantForgeScope = `-- name: GrantForgeScope :execrows
INSERT INTO account_forge_scopes (account_id, forge_provider, forge_host, repo)
SELECT u.account_id, $1, $2, $3
FROM user_accounts AS u
WHERE u.account_id = $4
ON CONFLICT DO NOTHING
`

type GrantForgeScopeParams struct {
	ForgeProvider int16
	ForgeHost     string
	Repo          string
	AccountID     string
}

// Scope grants are managed for user accounts and agent-specific repositories.
// The SELECT runs under RLS, so a user from another tenant inserts nothing.
func (q *Queries) GrantForgeScope(ctx context.Context, arg GrantForgeScopeParams) (int64, error) {
	result, err := q.db.Exec(ctx, grantForgeScope,
		arg.ForgeProvider,
		arg.ForgeHost,
		arg.Repo,
		arg.AccountID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const hasForgeScope = `-- name: HasForgeScope :one
SELECT EXISTS (
    SELECT 1
    FROM account_forge_scopes AS scope
    LEFT JOIN agent_accounts AS agent ON agent.account_id = $1
    WHERE scope.account_id IN ($1, agent.owner_user_id)
      AND scope.forge_provider = $2
      AND scope.forge_host = $3
      AND scope.repo IN ($4, '*')
)
`

type HasForgeScopeParams struct {
	AccountID     string
	ForgeProvider int16
	ForgeHost     string
	Repo          string
}

func (q *Queries) HasForgeScope(ctx context.Context, arg HasForgeScopeParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasForgeScope,
		arg.AccountID,
		arg.ForgeProvider,
		arg.ForgeHost,
		arg.Repo,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listForgeScopeRepos = `-- name: ListForgeScopeRepos :many
SELECT DISTINCT scope.repo
FROM account_forge_scopes AS scope
LEFT JOIN agent_accounts AS agent ON agent.account_id = $1
WHERE scope.account_id IN ($1, agent.owner_user_id)
  AND scope.forge_provider = $2
  AND scope.forge_host = $3
ORDER BY scope.repo
`

type ListForgeScopeReposParams struct {
	AccountID     string
	ForgeProvider int16
	ForgeHost     string
}

func (q *Queries) ListForgeScopeRepos(ctx context.Context, arg ListForgeScopeReposParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listForgeScopeRepos, arg.AccountID, arg.ForgeProvider, arg.ForgeHost)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var repo string
		if err := rows.Scan(&repo); err != nil {
			return nil, err
		}
		items = append(items, repo)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeForgeScope = `-- name: RevokeForgeScope :exec
DELETE FROM account_forge_scopes
WHERE account_id = $1 AND forge_provider = $2 AND forge_host = $3 AND repo = $4
`

type RevokeForgeScopeParams struct {
	AccountID     string
	ForgeProvider int16
	ForgeHost     string
	Repo          string
}

func (q *Queries) RevokeForgeScope(ctx context.Context, arg RevokeForgeScopeParams) error {
	_, err := q.db.Exec(ctx, revokeForgeScope,
		arg.AccountID,
		arg.ForgeProvider,
		arg.ForgeHost,
		arg.Repo,
	)
	return err
}
