// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: forge_authored.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const authoredArtifactByCoordinate = `-- name: AuthoredArtifactByCoordinate :one
SELECT forge_provider, forge_host, repo, kind, number,
       agent_account_id, owner_user_id, session_id, client_request_id, created_at_unix_ms
FROM forge_authored_artifacts
WHERE forge_provider = $1 AND forge_host = $2 AND repo = $3 AND kind = $4 AND number = $5
`

type AuthoredArtifactByCoordinateParams struct {
	ForgeProvider int16
	ForgeHost     string
	Repo          string
	Kind          int16
	Number        int64
}

func (q *Queries) AuthoredArtifactByCoordinate(ctx context.Context, arg AuthoredArtifactByCoordinateParams) (ForgeAuthoredArtifact, error) {
	row := q.db.QueryRow(ctx, authoredArtifactByCoordinate,
		arg.ForgeProvider,
		arg.ForgeHost,
		arg.Repo,
		arg.Kind,
		arg.Number,
	)
	var i ForgeAuthoredArtifact
	err := row.Scan(
		&i.ForgeProvider,
		&i.ForgeHost,
		&i.Repo,
		&i.Kind,
		&i.Number,
		&i.AgentAccountID,
		&i.OwnerUserID,
		&i.SessionID,
		&i.ClientRequestID,
		&i.CreatedAtUnixMs,
	)
	return i, err
}

const authoredArtifactByRequestID = `-- name: AuthoredArtifactByRequestID :one
SELECT forge_provider, forge_host, repo, kind, number,
       agent_account_id, owner_user_id, session_id, client_request_id, created_at_unix_ms
FROM forge_authored_artifacts
WHERE agent_account_id = $1 AND client_request_id = $2
`

type AuthoredArtifactByRequestIDParams struct {
	AgentAccountID  string
	ClientRequestID pgtype.Text
}

func (q *Queries) AuthoredArtifactByRequestID(ctx context.Context, arg AuthoredArtifactByRequestIDParams) (ForgeAuthoredArtifact, error) {
	row := q.db.QueryRow(ctx, authoredArtifactByRequestID, arg.AgentAccountID, arg.ClientRequestID)
	var i ForgeAuthoredArtifact
	err := row.Scan(
		&i.ForgeProvider,
		&i.ForgeHost,
		&i.Repo,
		&i.Kind,
		&i.Number,
		&i.AgentAccountID,
		&i.OwnerUserID,
		&i.SessionID,
		&i.ClientRequestID,
		&i.CreatedAtUnixMs,
	)
	return i, err
}

const listAuthoredArtifactsByAgent = `-- name: ListAuthoredArtifactsByAgent :many
SELECT forge_provider, forge_host, repo, kind, number,
       agent_account_id, owner_user_id, session_id, client_request_id, created_at_unix_ms
FROM forge_authored_artifacts
WHERE agent_account_id = $1
ORDER BY created_at_unix_ms ASC, forge_provider ASC, forge_host ASC, repo ASC, kind ASC, number ASC
`

func (q *Queries) ListAuthoredArtifactsByAgent(ctx context.Context, agentAccountID string) ([]ForgeAuthoredArtifact, error) {
	rows, err := q.db.Query(ctx, listAuthoredArtifactsByAgent, agentAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ForgeAuthoredArtifact
	for rows.Next() {
		var i ForgeAuthoredArtifact
		if err := rows.Scan(
			&i.ForgeProvider,
			&i.ForgeHost,
			&i.Repo,
			&i.Kind,
			&i.Number,
			&i.AgentAccountID,
			&i.OwnerUserID,
			&i.SessionID,
			&i.ClientRequestID,
			&i.CreatedAtUnixMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAuthoredArtifact = `-- name: RecordAuthoredArtifact :exec

INSERT INTO forge_authored_artifacts
    (forge_provider, forge_host, repo, kind, number,
     agent_account_id, owner_user_id, session_id, client_request_id, created_at_unix_ms)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (forge_provider, forge_host, repo, kind, number) DO UPDATE
   SET session_id         = EXCLUDED.session_id,
       client_request_id  = EXCLUDED.client_request_id,
       created_at_unix_ms = EXCLUDED.created_at_unix_ms
`

type RecordAuthoredArtifactParams struct {
	ForgeProvider   int16
	ForgeHost       string
	Repo            string
	Kind            int16
	Number          int64
	AgentAccountID  string
	OwnerUserID     string
	SessionID       string
	ClientRequestID pgtype.Text
	CreatedAtUnixMs int64
}

// Forge-authored-artifact queries (sqlc adoption T6, RIG-3034). These replace the
// inline SQL literals in internal/store/forge_authored.go; the hand-written Store
// methods keep their signatures, the door-side validation (valid/validCoordinate),
// the ErrConflict/ErrInvalidArgument/ErrNotFound mapping via pgErrIs, and the
// textOrNull client_request_id NULL discipline. The read queries feed
// authoredArtifactFromRow, which maps the generated row (provider/kind ints,
// number BIGINT, nullable client_request_id) back to the domain AuthoredArtifact.
// WRITE-ONCE authorship: the DO UPDATE deliberately omits agent_account_id and
// owner_user_id, so a re-land never rewrites who authored the artifact.
func (q *Queries) RecordAuthoredArtifact(ctx context.Context, arg RecordAuthoredArtifactParams) error {
	_, err := q.db.Exec(ctx, recordAuthoredArtifact,
		arg.ForgeProvider,
		arg.ForgeHost,
		arg.Repo,
		arg.Kind,
		arg.Number,
		arg.AgentAccountID,
		arg.OwnerUserID,
		arg.SessionID,
		arg.ClientRequestID,
		arg.CreatedAtUnixMs,
	)
	return err
}
