// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gateway_credentials.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const disableGatewayCredential = `-- name: DisableGatewayCredential :execrows
UPDATE gateway_credentials
SET disabled_at = $1, disabled_cause = $2,
    version = version + 1
WHERE id = $3 AND version = $4 AND disabled_at IS NULL
`

type DisableGatewayCredentialParams struct {
	DisabledAt    pgtype.Timestamptz
	DisabledCause string
	ID            string
	Version       int64
}

func (q *Queries) DisableGatewayCredential(ctx context.Context, arg DisableGatewayCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, disableGatewayCredential,
		arg.DisabledAt,
		arg.DisabledCause,
		arg.ID,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const gatewayAgentTenant = `-- name: GatewayAgentTenant :one
SELECT tenant_id
FROM agent_accounts
WHERE account_id = $1
`

func (q *Queries) GatewayAgentTenant(ctx context.Context, accountID string) (string, error) {
	row := q.db.QueryRow(ctx, gatewayAgentTenant, accountID)
	var tenant_id string
	err := row.Scan(&tenant_id)
	return tenant_id, err
}

const gatewayCredentialOwnerExists = `-- name: GatewayCredentialOwnerExists :one
SELECT EXISTS (
    SELECT 1 FROM user_accounts WHERE account_id = $1
)
`

func (q *Queries) GatewayCredentialOwnerExists(ctx context.Context, ownerUserID string) (bool, error) {
	row := q.db.QueryRow(ctx, gatewayCredentialOwnerExists, ownerUserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getGatewayCredentialForUpdate = `-- name: GetGatewayCredentialForUpdate :one
SELECT id, provider, scope, owner_user_id, kind, version, expires_at_unix_ms,
       value_ciphertext, value_nonce, key_version, disabled_at, disabled_cause,
       created_at, updated_at
FROM gateway_credentials
WHERE id = $1
FOR UPDATE
`

type GetGatewayCredentialForUpdateRow struct {
	ID              string
	Provider        string
	Scope           int16
	OwnerUserID     pgtype.Text
	Kind            int16
	Version         int64
	ExpiresAtUnixMs int64
	ValueCiphertext []byte
	ValueNonce      []byte
	KeyVersion      int16
	DisabledAt      pgtype.Timestamptz
	DisabledCause   string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) GetGatewayCredentialForUpdate(ctx context.Context, id string) (GetGatewayCredentialForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getGatewayCredentialForUpdate, id)
	var i GetGatewayCredentialForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Scope,
		&i.OwnerUserID,
		&i.Kind,
		&i.Version,
		&i.ExpiresAtUnixMs,
		&i.ValueCiphertext,
		&i.ValueNonce,
		&i.KeyVersion,
		&i.DisabledAt,
		&i.DisabledCause,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertGatewayCredential = `-- name: InsertGatewayCredential :exec
INSERT INTO gateway_credentials (
    id, provider, scope, owner_user_id, kind, version, expires_at_unix_ms,
    value_ciphertext, value_nonce, key_version
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10
)
`

type InsertGatewayCredentialParams struct {
	ID              string
	Provider        string
	Scope           int16
	OwnerUserID     pgtype.Text
	Kind            int16
	Version         int64
	ExpiresAtUnixMs int64
	ValueCiphertext []byte
	ValueNonce      []byte
	KeyVersion      int16
}

func (q *Queries) InsertGatewayCredential(ctx context.Context, arg InsertGatewayCredentialParams) error {
	_, err := q.db.Exec(ctx, insertGatewayCredential,
		arg.ID,
		arg.Provider,
		arg.Scope,
		arg.OwnerUserID,
		arg.Kind,
		arg.Version,
		arg.ExpiresAtUnixMs,
		arg.ValueCiphertext,
		arg.ValueNonce,
		arg.KeyVersion,
	)
	return err
}

const listGatewayCredentials = `-- name: ListGatewayCredentials :many
SELECT gc.id, gc.tenant_id, gc.provider, gc.scope, gc.owner_user_id, gc.kind, gc.version, gc.expires_at_unix_ms, gc.value_ciphertext, gc.value_nonce, gc.key_version, gc.disabled_at, gc.disabled_cause, gc.created_at, gc.updated_at
FROM gateway_credentials gc
WHERE gc.disabled_at IS NULL
  AND (gc.scope = 2 OR gc.owner_user_id = $1)
  AND ($2::text = '' OR gc.provider = $2::text)
  AND (
      NOT $3::boolean
      OR gc.scope = 1
      OR NOT EXISTS (
          SELECT 1
          FROM gateway_credentials own
          WHERE own.disabled_at IS NULL
            AND own.scope = 1
            AND own.owner_user_id = $1
            AND own.provider = gc.provider
      )
  )
ORDER BY gc.provider ASC, gc.created_at ASC, gc.id ASC
`

type ListGatewayCredentialsParams struct {
	OwnerUserID pgtype.Text
	Provider    string
	PoolOnly    bool
}

type ListGatewayCredentialsRow struct {
	GatewayCredential GatewayCredential
}

func (q *Queries) ListGatewayCredentials(ctx context.Context, arg ListGatewayCredentialsParams) ([]ListGatewayCredentialsRow, error) {
	rows, err := q.db.Query(ctx, listGatewayCredentials, arg.OwnerUserID, arg.Provider, arg.PoolOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGatewayCredentialsRow
	for rows.Next() {
		var i ListGatewayCredentialsRow
		if err := rows.Scan(
			&i.GatewayCredential.ID,
			&i.GatewayCredential.TenantID,
			&i.GatewayCredential.Provider,
			&i.GatewayCredential.Scope,
			&i.GatewayCredential.OwnerUserID,
			&i.GatewayCredential.Kind,
			&i.GatewayCredential.Version,
			&i.GatewayCredential.ExpiresAtUnixMs,
			&i.GatewayCredential.ValueCiphertext,
			&i.GatewayCredential.ValueNonce,
			&i.GatewayCredential.KeyVersion,
			&i.GatewayCredential.DisabledAt,
			&i.GatewayCredential.DisabledCause,
			&i.GatewayCredential.CreatedAt,
			&i.GatewayCredential.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGatewayOAuthCredential = `-- name: UpdateGatewayOAuthCredential :execrows
UPDATE gateway_credentials
SET value_ciphertext = $1, value_nonce = $2,
    key_version = $3, expires_at_unix_ms = $4,
    version = version + 1
WHERE id = $5 AND version = $6 AND disabled_at IS NULL
`

type UpdateGatewayOAuthCredentialParams struct {
	ValueCiphertext []byte
	ValueNonce      []byte
	KeyVersion      int16
	ExpiresAtUnixMs int64
	ID              string
	Version         int64
}

func (q *Queries) UpdateGatewayOAuthCredential(ctx context.Context, arg UpdateGatewayOAuthCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateGatewayOAuthCredential,
		arg.ValueCiphertext,
		arg.ValueNonce,
		arg.KeyVersion,
		arg.ExpiresAtUnixMs,
		arg.ID,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
