// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: issues.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getIssue = `-- name: GetIssue :one
SELECT id, forge_provider, forge_host, repo, number,
       title, body, forge_state, url, forge_account, labels, agent_handle,
       state, priority, assignee, summary, branch
FROM issues
WHERE id = $1
`

type GetIssueRow struct {
	ID            string
	ForgeProvider int16
	ForgeHost     string
	Repo          string
	Number        int64
	Title         string
	Body          string
	ForgeState    string
	Url           string
	ForgeAccount  string
	Labels        []string
	AgentHandle   string
	State         int16
	Priority      string
	Assignee      string
	Summary       string
	Branch        string
}

func (q *Queries) GetIssue(ctx context.Context, id string) (GetIssueRow, error) {
	row := q.db.QueryRow(ctx, getIssue, id)
	var i GetIssueRow
	err := row.Scan(
		&i.ID,
		&i.ForgeProvider,
		&i.ForgeHost,
		&i.Repo,
		&i.Number,
		&i.Title,
		&i.Body,
		&i.ForgeState,
		&i.Url,
		&i.ForgeAccount,
		&i.Labels,
		&i.AgentHandle,
		&i.State,
		&i.Priority,
		&i.Assignee,
		&i.Summary,
		&i.Branch,
	)
	return i, err
}

const listIssues = `-- name: ListIssues :many
SELECT id, forge_provider, forge_host, repo, number,
       title, body, forge_state, url, forge_account, labels, agent_handle,
       state, priority, assignee, summary, branch
FROM issues
ORDER BY id
`

type ListIssuesRow struct {
	ID            string
	ForgeProvider int16
	ForgeHost     string
	Repo          string
	Number        int64
	Title         string
	Body          string
	ForgeState    string
	Url           string
	ForgeAccount  string
	Labels        []string
	AgentHandle   string
	State         int16
	Priority      string
	Assignee      string
	Summary       string
	Branch        string
}

func (q *Queries) ListIssues(ctx context.Context) ([]ListIssuesRow, error) {
	rows, err := q.db.Query(ctx, listIssues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIssuesRow
	for rows.Next() {
		var i ListIssuesRow
		if err := rows.Scan(
			&i.ID,
			&i.ForgeProvider,
			&i.ForgeHost,
			&i.Repo,
			&i.Number,
			&i.Title,
			&i.Body,
			&i.ForgeState,
			&i.Url,
			&i.ForgeAccount,
			&i.Labels,
			&i.AgentHandle,
			&i.State,
			&i.Priority,
			&i.Assignee,
			&i.Summary,
			&i.Branch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setIssueState = `-- name: SetIssueState :execrows
UPDATE issues SET state = $2 WHERE id = $1
`

type SetIssueStateParams struct {
	ID    string
	State int16
}

func (q *Queries) SetIssueState(ctx context.Context, arg SetIssueStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, setIssueState, arg.ID, arg.State)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertIssueForgeFields = `-- name: UpsertIssueForgeFields :one

WITH up AS (
     INSERT INTO issues
         (id, forge_provider, forge_host, repo, number,
          title, body, forge_state, url, forge_account, labels, agent_handle,
          forge_updated_at)
     VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
     ON CONFLICT (forge_provider, forge_host, repo, number) DO UPDATE
        SET title = EXCLUDED.title, body = EXCLUDED.body,
            forge_state = EXCLUDED.forge_state, url = EXCLUDED.url,
            forge_account = EXCLUDED.forge_account, labels = EXCLUDED.labels,
            agent_handle = EXCLUDED.agent_handle,
            forge_updated_at = EXCLUDED.forge_updated_at
      WHERE issues.forge_updated_at IS NULL
         OR EXCLUDED.forge_updated_at IS NULL
         OR EXCLUDED.forge_updated_at >= issues.forge_updated_at
     RETURNING id
 )
 SELECT id FROM up
 UNION ALL
 SELECT id FROM issues
  WHERE NOT EXISTS (SELECT 1 FROM up)
    AND forge_provider = $2 AND forge_host = $3 AND repo = $4 AND number = $5
 LIMIT 1
`

type UpsertIssueForgeFieldsParams struct {
	ID             string
	ForgeProvider  int16
	ForgeHost      string
	Repo           string
	Number         int64
	Title          string
	Body           string
	ForgeState     string
	Url            string
	ForgeAccount   string
	Labels         []string
	AgentHandle    string
	ForgeUpdatedAt pgtype.Timestamptz
}

// Issue-domain queries (sqlc adoption T6, RIG-3034). These replace the inline
// SQL literals in internal/store/issues.go; the hand-written Store methods keep
// their signatures, the door-side validation, the ErrNotFound/ErrInvalidArgument
// mapping, and the RowsAffected branch (SetIssueState is :execrows). GetIssue /
// ListIssues feed issueFromColumns (via issueFromGetRow / issueFromListRow),
// which maps the generated row (forge_provider/state ints, number BIGINT) back
// to the domain Issue.
// Insert-or-update at the forge coordinate with the OQ-6(a) recency guard; the
// ON CONFLICT sets ONLY forge columns (never state/machinery), and the CTE's
// fallback SELECT keeps the returned id stable when the guard skips the UPDATE.
func (q *Queries) UpsertIssueForgeFields(ctx context.Context, arg UpsertIssueForgeFieldsParams) (string, error) {
	row := q.db.QueryRow(ctx, upsertIssueForgeFields,
		arg.ID,
		arg.ForgeProvider,
		arg.ForgeHost,
		arg.Repo,
		arg.Number,
		arg.Title,
		arg.Body,
		arg.ForgeState,
		arg.Url,
		arg.ForgeAccount,
		arg.Labels,
		arg.AgentHandle,
		arg.ForgeUpdatedAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
