// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: linear_routing.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLinearRoutingChannel = `-- name: GetLinearRoutingChannel :one
SELECT id, kind FROM channels WHERE group_id = $1 AND name = $2
`

type GetLinearRoutingChannelParams struct {
	GroupID pgtype.Text
	Name    string
}

type GetLinearRoutingChannelRow struct {
	ID   string
	Kind int16
}

func (q *Queries) GetLinearRoutingChannel(ctx context.Context, arg GetLinearRoutingChannelParams) (GetLinearRoutingChannelRow, error) {
	row := q.db.QueryRow(ctx, getLinearRoutingChannel, arg.GroupID, arg.Name)
	var i GetLinearRoutingChannelRow
	err := row.Scan(&i.ID, &i.Kind)
	return i, err
}

const getLinearRoutingGroup = `-- name: GetLinearRoutingGroup :one

SELECT id FROM channel_groups
WHERE owner_user_id = $1 AND name = $2 AND parent_group_id IS NULL AND visibility = $3
ORDER BY id
LIMIT 1
`

type GetLinearRoutingGroupParams struct {
	OwnerUserID string
	Name        string
	Visibility  int16
}

// Linear routing channel queries: the admin's reserved __linear__ group and the one
// routing channel inside it, keyed by (group, name) so a planted look-alike is never adopted.
// Visibility-discriminated like GetOwnerDMGroup: a planted wider __linear__ group is never adopted.
func (q *Queries) GetLinearRoutingGroup(ctx context.Context, arg GetLinearRoutingGroupParams) (string, error) {
	row := q.db.QueryRow(ctx, getLinearRoutingGroup, arg.OwnerUserID, arg.Name, arg.Visibility)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertLinearRoutingChannel = `-- name: InsertLinearRoutingChannel :one
INSERT INTO channels (id, name, group_id, kind, post_policy, owner_account_id, mandatory_subscription)
VALUES ($1, $2, $3, $4, $5, NULL, $6)
ON CONFLICT (group_id, name) WHERE group_id IS NOT NULL DO NOTHING
RETURNING id
`

type InsertLinearRoutingChannelParams struct {
	ID                    string
	Name                  string
	GroupID               pgtype.Text
	Kind                  int16
	PostPolicy            int16
	MandatorySubscription bool
}

// ON CONFLICT DO NOTHING keeps a lost race from poisoning the tx; the caller re-selects.
func (q *Queries) InsertLinearRoutingChannel(ctx context.Context, arg InsertLinearRoutingChannelParams) (string, error) {
	row := q.db.QueryRow(ctx, insertLinearRoutingChannel,
		arg.ID,
		arg.Name,
		arg.GroupID,
		arg.Kind,
		arg.PostPolicy,
		arg.MandatorySubscription,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertLinearRoutingGroup = `-- name: InsertLinearRoutingGroup :exec
INSERT INTO channel_groups (id, name, parent_group_id, owner_user_id, visibility, namespace_owner_id)
VALUES ($1, $2, NULL, $3, $4,
        COALESCE((SELECT owner_user_id FROM agent_accounts WHERE account_id = $3), $3))
`

type InsertLinearRoutingGroupParams struct {
	ID          string
	Name        string
	OwnerUserID string
	Visibility  int16
}

func (q *Queries) InsertLinearRoutingGroup(ctx context.Context, arg InsertLinearRoutingGroupParams) error {
	_, err := q.db.Exec(ctx, insertLinearRoutingGroup,
		arg.ID,
		arg.Name,
		arg.OwnerUserID,
		arg.Visibility,
	)
	return err
}

const lockLinearRouting = `-- name: LockLinearRouting :exec
SELECT pg_advisory_xact_lock(hashtext('linear-routing:' || $1))
`

func (q *Queries) LockLinearRouting(ctx context.Context, dollar_1 pgtype.Text) error {
	_, err := q.db.Exec(ctx, lockLinearRouting, dollar_1)
	return err
}

const reassertLinearRoutingShape = `-- name: ReassertLinearRoutingShape :exec
UPDATE channels SET mandatory_subscription = TRUE, post_policy = $2, owner_account_id = NULL
WHERE id = $1 AND (mandatory_subscription = FALSE OR post_policy <> $2 OR owner_account_id IS NOT NULL)
`

type ReassertLinearRoutingShapeParams struct {
	ID         string
	PostPolicy int16
}

// The bridge posts as a non-owner, so owner-only or owned drift would refuse every cold delegation.
func (q *Queries) ReassertLinearRoutingShape(ctx context.Context, arg ReassertLinearRoutingShapeParams) error {
	_, err := q.db.Exec(ctx, reassertLinearRoutingShape, arg.ID, arg.PostPolicy)
	return err
}
