// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package db

import (
	"context"
)

const findAskMessage = `-- name: FindAskMessage :many
SELECT m.id, m.topic_id, m.author_account_id, m.at_unix_ms, m.blocks
FROM messages m
JOIN topics t ON t.id = m.topic_id
JOIN channel_members cm ON cm.channel_id = t.channel_id AND cm.account_id = $1
WHERE m.blocks @> $2::jsonb
FOR UPDATE OF m
`

type FindAskMessageParams struct {
	AccountID string
	Column2   []byte
}

type FindAskMessageRow struct {
	ID              string
	TopicID         string
	AuthorAccountID string
	AtUnixMs        int64
	Blocks          []byte
}

func (q *Queries) FindAskMessage(ctx context.Context, arg FindAskMessageParams) ([]FindAskMessageRow, error) {
	rows, err := q.db.Query(ctx, findAskMessage, arg.AccountID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindAskMessageRow
	for rows.Next() {
		var i FindAskMessageRow
		if err := rows.Scan(
			&i.ID,
			&i.TopicID,
			&i.AuthorAccountID,
			&i.AtUnixMs,
			&i.Blocks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChannelPostPolicy = `-- name: GetChannelPostPolicy :one

SELECT post_policy, COALESCE(owner_account_id, '') AS owner_account_id
FROM channels WHERE id = $1
`

type GetChannelPostPolicyRow struct {
	PostPolicy     int16
	OwnerAccountID string
}

// Message-domain queries (sqlc adoption T4, RIG-3034). These replace the inline
// SQL literals in internal/store/messages.go; the hand-written Store methods keep
// their exact signatures, their tx orchestration (AppendMessage/AnswerAsk begin
// and commit their own txns), the ON CONFLICT idempotency signalling
// (errMessageInsertConflict), the JSONB block (de)serialization, and the D9
// not-found/forbidden error mapping — all hand-written around these generated
// calls. Every message read shares the id/topic_id/author_account_id/at_unix_ms/
// blocks projection (the former scanMessages order) so the Go maps each row the
// same way via messageFromParts.
func (q *Queries) GetChannelPostPolicy(ctx context.Context, id string) (GetChannelPostPolicyRow, error) {
	row := q.db.QueryRow(ctx, getChannelPostPolicy, id)
	var i GetChannelPostPolicyRow
	err := row.Scan(&i.PostPolicy, &i.OwnerAccountID)
	return i, err
}

const getMessageBlocks = `-- name: GetMessageBlocks :one
SELECT blocks FROM messages WHERE id = $1
`

func (q *Queries) GetMessageBlocks(ctx context.Context, id string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getMessageBlocks, id)
	var blocks []byte
	err := row.Scan(&blocks)
	return blocks, err
}

const getMessageByRequestID = `-- name: GetMessageByRequestID :many
SELECT id, topic_id, author_account_id, at_unix_ms, blocks
FROM messages
WHERE author_account_id = $1 AND client_request_id = $2
`

type GetMessageByRequestIDParams struct {
	AuthorAccountID string
	ClientRequestID string
}

type GetMessageByRequestIDRow struct {
	ID              string
	TopicID         string
	AuthorAccountID string
	AtUnixMs        int64
	Blocks          []byte
}

func (q *Queries) GetMessageByRequestID(ctx context.Context, arg GetMessageByRequestIDParams) ([]GetMessageByRequestIDRow, error) {
	rows, err := q.db.Query(ctx, getMessageByRequestID, arg.AuthorAccountID, arg.ClientRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessageByRequestIDRow
	for rows.Next() {
		var i GetMessageByRequestIDRow
		if err := rows.Scan(
			&i.ID,
			&i.TopicID,
			&i.AuthorAccountID,
			&i.AtUnixMs,
			&i.Blocks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPageCursorSeq = `-- name: GetPageCursorSeq :one
SELECT m.seq FROM messages m
JOIN topics t ON t.id = m.topic_id
JOIN channel_members cm ON cm.channel_id = t.channel_id AND cm.account_id = $1
WHERE m.id = $2 AND t.channel_id = $3
`

type GetPageCursorSeqParams struct {
	AccountID string
	ID        string
	ChannelID string
}

func (q *Queries) GetPageCursorSeq(ctx context.Context, arg GetPageCursorSeqParams) (int64, error) {
	row := q.db.QueryRow(ctx, getPageCursorSeq, arg.AccountID, arg.ID, arg.ChannelID)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const getTopicByName = `-- name: GetTopicByName :one
SELECT id, archived FROM topics WHERE channel_id = $1 AND lower(name) = lower($2)
`

type GetTopicByNameParams struct {
	ChannelID string
	Lower     string
}

type GetTopicByNameRow struct {
	ID       string
	Archived bool
}

func (q *Queries) GetTopicByName(ctx context.Context, arg GetTopicByNameParams) (GetTopicByNameRow, error) {
	row := q.db.QueryRow(ctx, getTopicByName, arg.ChannelID, arg.Lower)
	var i GetTopicByNameRow
	err := row.Scan(&i.ID, &i.Archived)
	return i, err
}

const getTopicChannel = `-- name: GetTopicChannel :one
SELECT channel_id FROM topics WHERE id = $1
`

func (q *Queries) GetTopicChannel(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getTopicChannel, id)
	var channel_id string
	err := row.Scan(&channel_id)
	return channel_id, err
}

const insertMessage = `-- name: InsertMessage :one
INSERT INTO messages (id, topic_id, author_account_id, at_unix_ms, blocks, text_content, client_request_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (author_account_id, client_request_id) WHERE client_request_id <> ''
DO NOTHING
RETURNING id, at_unix_ms, seq
`

type InsertMessageParams struct {
	ID              string
	TopicID         string
	AuthorAccountID string
	AtUnixMs        int64
	Blocks          []byte
	TextContent     string
	ClientRequestID string
}

type InsertMessageRow struct {
	ID       string
	AtUnixMs int64
	Seq      int64
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (InsertMessageRow, error) {
	row := q.db.QueryRow(ctx, insertMessage,
		arg.ID,
		arg.TopicID,
		arg.AuthorAccountID,
		arg.AtUnixMs,
		arg.Blocks,
		arg.TextContent,
		arg.ClientRequestID,
	)
	var i InsertMessageRow
	err := row.Scan(&i.ID, &i.AtUnixMs, &i.Seq)
	return i, err
}

const insertTopicIgnore = `-- name: InsertTopicIgnore :exec
INSERT INTO topics (id, channel_id, name, created_by_account_id, created_at_unix_ms)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (channel_id, lower(name)) DO NOTHING
`

type InsertTopicIgnoreParams struct {
	ID                 string
	ChannelID          string
	Name               string
	CreatedByAccountID string
	CreatedAtUnixMs    int64
}

func (q *Queries) InsertTopicIgnore(ctx context.Context, arg InsertTopicIgnoreParams) error {
	_, err := q.db.Exec(ctx, insertTopicIgnore,
		arg.ID,
		arg.ChannelID,
		arg.Name,
		arg.CreatedByAccountID,
		arg.CreatedAtUnixMs,
	)
	return err
}

const listMessages = `-- name: ListMessages :many
SELECT m.id, m.topic_id, m.author_account_id, m.at_unix_ms, m.blocks
FROM messages m
JOIN topics t ON t.id = m.topic_id
JOIN channel_members cm ON cm.channel_id = t.channel_id AND cm.account_id = $1
WHERE t.channel_id = $2 AND ($3 = 0 OR m.seq < $3) AND ($5 = 0 OR m.seq <= $5)
  AND ($6 = '' OR m.topic_id = $6)
ORDER BY m.seq DESC
LIMIT $4
`

type ListMessagesParams struct {
	AccountID string
	ChannelID string
	Column3   interface{}
	Limit     int32
	Column5   interface{}
	Column6   interface{}
}

type ListMessagesRow struct {
	ID              string
	TopicID         string
	AuthorAccountID string
	AtUnixMs        int64
	Blocks          []byte
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]ListMessagesRow, error) {
	rows, err := q.db.Query(ctx, listMessages,
		arg.AccountID,
		arg.ChannelID,
		arg.Column3,
		arg.Limit,
		arg.Column5,
		arg.Column6,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesRow
	for rows.Next() {
		var i ListMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.TopicID,
			&i.AuthorAccountID,
			&i.AtUnixMs,
			&i.Blocks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const messagesHeadSeq = `-- name: MessagesHeadSeq :one
SELECT COALESCE(MAX(seq), 0)::BIGINT AS head FROM messages
`

func (q *Queries) MessagesHeadSeq(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, messagesHeadSeq)
	var head int64
	err := row.Scan(&head)
	return head, err
}

const reviveTopic = `-- name: ReviveTopic :exec
UPDATE topics SET archived = FALSE WHERE id = $1
`

func (q *Queries) ReviveTopic(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, reviveTopic, id)
	return err
}

const searchMessages = `-- name: SearchMessages :many
SELECT m.id, m.topic_id, m.author_account_id, m.at_unix_ms, m.blocks
FROM messages m
JOIN topics t ON t.id = m.topic_id
JOIN channel_members cm ON cm.channel_id = t.channel_id AND cm.account_id = $1
WHERE m.search_tsv @@ websearch_to_tsquery('english', $2)
  AND ($3 = '' OR t.channel_id = $3)
  AND ($5 = 0 OR m.seq <= $5)
ORDER BY ts_rank(m.search_tsv, websearch_to_tsquery('english', $2)) DESC, m.seq DESC
LIMIT $4
`

type SearchMessagesParams struct {
	AccountID          string
	WebsearchToTsquery string
	Column3            interface{}
	Limit              int32
	Column5            interface{}
}

type SearchMessagesRow struct {
	ID              string
	TopicID         string
	AuthorAccountID string
	AtUnixMs        int64
	Blocks          []byte
}

func (q *Queries) SearchMessages(ctx context.Context, arg SearchMessagesParams) ([]SearchMessagesRow, error) {
	rows, err := q.db.Query(ctx, searchMessages,
		arg.AccountID,
		arg.WebsearchToTsquery,
		arg.Column3,
		arg.Limit,
		arg.Column5,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchMessagesRow
	for rows.Next() {
		var i SearchMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.TopicID,
			&i.AuthorAccountID,
			&i.AtUnixMs,
			&i.Blocks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMessageBlocks = `-- name: UpdateMessageBlocks :execrows
UPDATE messages SET blocks = $1, text_content = $2 WHERE id = $3
`

type UpdateMessageBlocksParams struct {
	Blocks      []byte
	TextContent string
	ID          string
}

func (q *Queries) UpdateMessageBlocks(ctx context.Context, arg UpdateMessageBlocksParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateMessageBlocks, arg.Blocks, arg.TextContent, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateMessageBlocksAsAuthor = `-- name: UpdateMessageBlocksAsAuthor :one
UPDATE messages m
SET blocks = $1, text_content = $2
FROM topics t
WHERE m.id = $3
  AND t.id = m.topic_id
  AND m.author_account_id = $4
  AND EXISTS (
    SELECT 1 FROM channel_members cm
    WHERE cm.channel_id = t.channel_id AND cm.account_id = $4
  )
RETURNING m.id, m.topic_id, m.author_account_id, m.at_unix_ms, m.blocks
`

type UpdateMessageBlocksAsAuthorParams struct {
	Blocks          []byte
	TextContent     string
	ID              string
	AuthorAccountID string
}

type UpdateMessageBlocksAsAuthorRow struct {
	ID              string
	TopicID         string
	AuthorAccountID string
	AtUnixMs        int64
	Blocks          []byte
}

func (q *Queries) UpdateMessageBlocksAsAuthor(ctx context.Context, arg UpdateMessageBlocksAsAuthorParams) (UpdateMessageBlocksAsAuthorRow, error) {
	row := q.db.QueryRow(ctx, updateMessageBlocksAsAuthor,
		arg.Blocks,
		arg.TextContent,
		arg.ID,
		arg.AuthorAccountID,
	)
	var i UpdateMessageBlocksAsAuthorRow
	err := row.Scan(
		&i.ID,
		&i.TopicID,
		&i.AuthorAccountID,
		&i.AtUnixMs,
		&i.Blocks,
	)
	return i, err
}

const updateTopicLastSeq = `-- name: UpdateTopicLastSeq :exec
UPDATE topics SET last_seq = GREATEST(last_seq, $2) WHERE id = $1
`

type UpdateTopicLastSeqParams struct {
	ID      string
	LastSeq int64
}

func (q *Queries) UpdateTopicLastSeq(ctx context.Context, arg UpdateTopicLastSeqParams) error {
	_, err := q.db.Exec(ctx, updateTopicLastSeq, arg.ID, arg.LastSeq)
	return err
}
