// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID          string
	Handle      string
	DisplayName string
	TenantID    string
	CreatedAt   pgtype.Timestamptz
}

type AccountHandle struct {
	AccountID   string
	Handle      string
	OwnerUserID pgtype.Text
}

type AgentAccount struct {
	AccountID     string
	OwnerUserID   string
	HomeChannelID pgtype.Text
	Persona       string
	ParentAgentID pgtype.Text
	Role          string
}

type AgentActivity struct {
	AgentAccountID   string
	Activity         string
	ActivityAtUnixMs int64
}

type AgentConfigBundle struct {
	Singleton bool
	Version   string
	Bundle    []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type AgentDeliveryCursor struct {
	AgentAccountID string
	ChannelID      string
	AckedSeq       int64
	AboveSeqs      []int64
	AckedAt        pgtype.Timestamptz
}

type AgentForgeSubscription struct {
	ID                string
	AgentAccountID    string
	ForgeProvider     int16
	ForgeHost         string
	Repo              string
	Kind              int16
	Number            int64
	Scope             int16
	Project           string
	DeliveredRevision string
	DeliveredAt       pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
}

type AgentPlacement struct {
	AgentAccountID string
	RunnerID       string
	ContainerName  string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type AgentSession struct {
	SessionID        string
	AgentAccountID   string
	BaseEntrySeq     int64
	RecordedAtUnixMs int64
}

type AgentSessionArchiveSegment struct {
	SessionID   string
	ObjectKey   string
	MinEntrySeq int64
	MaxEntrySeq int64
	Kind        string
}

type AgentSessionTranscriptEntry struct {
	SessionID      string
	EntrySeq       int64
	Checkpoint     bool
	EntryJson      string
	IdempotencyKey string
}

type AgentWorkspace struct {
	ID             string
	AgentAccountID string
}

type Channel struct {
	ID                    string
	Name                  string
	GroupID               pgtype.Text
	Kind                  int16
	CreatedAt             pgtype.Timestamptz
	PostPolicy            int16
	OwnerAccountID        pgtype.Text
	MandatorySubscription bool
}

type ChannelGroup struct {
	ID            string
	Name          string
	ParentGroupID pgtype.Text
	OwnerUserID   string
	Visibility    int16
}

type ChannelMember struct {
	ChannelID  string
	AccountID  string
	Subscribed bool
}

type ChannelPin struct {
	ChannelID         string
	MessageID         string
	Position          int32
	PinnedAtUnixMs    int64
	PinnedByAccountID string
}

type ForgeArtifactCursor struct {
	ForgeProvider int16
	ForgeHost     string
	Repo          string
	Kind          int16
	Number        int64
	Etag          string
	CommentsEtag  string
	ChecksEtag    string
	Revision      string
	Snapshot      []byte
	PolledAt      pgtype.Timestamptz
}

type ForgeAuthoredArtifact struct {
	ForgeProvider   int16
	ForgeHost       string
	Repo            string
	Kind            int16
	Number          int64
	AgentAccountID  string
	OwnerUserID     string
	SessionID       string
	ClientRequestID pgtype.Text
	CreatedAtUnixMs int64
}

type ForgeRepoSubscription struct {
	ForgeProvider  int16
	ForgeHost      string
	Repo           string
	Enabled        bool
	SweptUpdatedAt pgtype.Timestamptz
	ListEtag       string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Issue struct {
	ID             string
	ForgeProvider  int16
	ForgeHost      string
	Repo           string
	Number         int64
	Title          string
	Body           string
	ForgeState     string
	Url            string
	ForgeAccount   string
	Labels         []string
	AgentHandle    string
	ForgeUpdatedAt pgtype.Timestamptz
	State          int16
	Priority       string
	Assignee       string
	Summary        string
	Branch         string
}

type LinearAgentSession struct {
	LinearSessionID  string
	ManagerAccountID string
	ChannelID        string
	TopicID          string
	LinearIssueID    pgtype.Text
	CreatedAt        pgtype.Timestamptz
}

type Message struct {
	ID               string
	AuthorAccountID  string
	AtUnixMs         int64
	Seq              int64
	Blocks           []byte
	TextContent      string
	ClientRequestID  string
	SearchTsv        interface{}
	TopicID          string
	MentionsRoutedAt pgtype.Int8
}

type OwedMention struct {
	AgentAccountID   string
	MessageID        string
	ChannelID        string
	RecordedAtUnixMs int64
}

type Secret struct {
	Name       string
	Delivery   int16
	Kind       int16
	Provider   string
	Host       string
	DeclaredBy string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type SystemAccount struct {
	AccountID string
}

type Tenant struct {
	ID              string
	Slug            string
	DisplayName     string
	CreatedAtUnixMs int64
}

type Token struct {
	Hash        []byte
	SubjectKind int16
	SubjectID   string
	CreatedAt   pgtype.Timestamptz
	RevokedAt   pgtype.Timestamptz
}

type Topic struct {
	ID                 string
	ChannelID          string
	Name               string
	CreatedByAccountID string
	CreatedAtUnixMs    int64
	Archived           bool
	LastSeq            int64
}

type UserAccount struct {
	AccountID string
	Role      int16
}
