// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: model_registry.sql

package db

import (
	"context"
)

const currentModelRegistry = `-- name: CurrentModelRegistry :one

SELECT version, registry FROM model_registry WHERE singleton = TRUE
`

type CurrentModelRegistryRow struct {
	Version  int64
	Registry []byte
}

// Model-registry queries (RIG-3122 P2). Back the hand-written Store methods in
// internal/store/model_registry.go, which own the fail-closed payload
// validation (ValidateModelRegistry), the JSONB marshal/unmarshal, and the
// ErrVersionConflict/ErrNotFound mapping. The registry is a fleet-wide singleton
// row (singleton = TRUE) with a monotonic version supplying the CAS substrate:
// a write only lands if the row still holds the version the caller read.
func (q *Queries) CurrentModelRegistry(ctx context.Context) (CurrentModelRegistryRow, error) {
	row := q.db.QueryRow(ctx, currentModelRegistry)
	var i CurrentModelRegistryRow
	err := row.Scan(&i.Version, &i.Registry)
	return i, err
}

const deleteModelRegistry = `-- name: DeleteModelRegistry :exec
DELETE FROM model_registry WHERE singleton = TRUE
`

func (q *Queries) DeleteModelRegistry(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteModelRegistry)
	return err
}

const insertModelRegistry = `-- name: InsertModelRegistry :one
INSERT INTO model_registry (singleton, version, registry)
VALUES (TRUE, 1, $1)
ON CONFLICT (singleton) DO NOTHING
RETURNING version
`

// InsertModelRegistry seeds the FIRST registry (the caller read no row, expected
// version 0). ON CONFLICT DO NOTHING makes it a CAS: it lands only when the
// singleton is still absent, so a racing seed loses (zero rows, ErrNoRows via
// RETURNING) rather than clobbering the winner. The seeded version is 1.
func (q *Queries) InsertModelRegistry(ctx context.Context, registry []byte) (int64, error) {
	row := q.db.QueryRow(ctx, insertModelRegistry, registry)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const updateModelRegistry = `-- name: UpdateModelRegistry :one
UPDATE model_registry
   SET registry = $1, version = version + 1, updated_at = now()
 WHERE singleton = TRUE AND version = $2
RETURNING version
`

type UpdateModelRegistryParams struct {
	Registry []byte
	Version  int64
}

// UpdateModelRegistry is the compare-and-set write over an existing row: it
// lands only when the row still holds $2 (the version the caller read), bumping
// to version + 1 and returning the new version. A stale/racing expected version
// matches no row (ErrNoRows via RETURNING) — the caller maps that to
// ErrVersionConflict.
func (q *Queries) UpdateModelRegistry(ctx context.Context, arg UpdateModelRegistryParams) (int64, error) {
	row := q.db.QueryRow(ctx, updateModelRegistry, arg.Registry, arg.Version)
	var version int64
	err := row.Scan(&version)
	return version, err
}
