// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: model_registry.sql

package db

import (
	"context"
)

const currentModelRegistry = `-- name: CurrentModelRegistry :one

SELECT version, registry FROM model_registry WHERE singleton = TRUE
`

type CurrentModelRegistryRow struct {
	Version  int64
	Registry []byte
}

// Model-registry queries preserve a monotonic singleton version.
func (q *Queries) CurrentModelRegistry(ctx context.Context) (CurrentModelRegistryRow, error) {
	row := q.db.QueryRow(ctx, currentModelRegistry)
	var i CurrentModelRegistryRow
	err := row.Scan(&i.Version, &i.Registry)
	return i, err
}

const deleteModelRegistry = `-- name: DeleteModelRegistry :exec
UPDATE model_registry
   SET registry = 'null'::jsonb, version = version + 1
 WHERE singleton = TRUE AND registry <> 'null'::jsonb
`

// Delete marks the row as unconfigured while retaining its monotonic version.
func (q *Queries) DeleteModelRegistry(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteModelRegistry)
	return err
}

const insertModelRegistry = `-- name: InsertModelRegistry :one
INSERT INTO model_registry (singleton, version, registry)
VALUES (TRUE, 1, $1)
ON CONFLICT (singleton) DO UPDATE
   SET registry = EXCLUDED.registry, version = model_registry.version + 1
 WHERE model_registry.registry = 'null'::jsonb
RETURNING version
`

// InsertModelRegistry seeds or revives the singleton. A tombstone retains its
// version, so reseeding after delete increments instead of reusing it.
func (q *Queries) InsertModelRegistry(ctx context.Context, registry []byte) (int64, error) {
	row := q.db.QueryRow(ctx, insertModelRegistry, registry)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const modelRegistryVersion = `-- name: ModelRegistryVersion :one
SELECT version FROM model_registry WHERE singleton = TRUE
`

func (q *Queries) ModelRegistryVersion(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, modelRegistryVersion)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const updateModelRegistry = `-- name: UpdateModelRegistry :one
UPDATE model_registry
   SET registry = $1, version = version + 1
 WHERE singleton = TRUE AND registry <> 'null'::jsonb AND version = $2
RETURNING version
`

type UpdateModelRegistryParams struct {
	Registry []byte
	Version  int64
}

// UpdateModelRegistry applies a compare-and-set only to a live row.
func (q *Queries) UpdateModelRegistry(ctx context.Context, arg UpdateModelRegistryParams) (int64, error) {
	row := q.db.QueryRow(ctx, updateModelRegistry, arg.Registry, arg.Version)
	var version int64
	err := row.Scan(&version)
	return version, err
}
