// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: presence_reads.sql

package db

import (
	"context"
)

const agentHasOpenAsk = `-- name: AgentHasOpenAsk :one

SELECT EXISTS (
	SELECT 1 FROM messages
	WHERE author_account_id = $1
	  AND blocks @? '$[*] ? (@.kind == "ask" && (!exists(@.ask.answered) || @.ask.answered == false))'
)
`

// Presence-component read queries (sqlc adoption T4, RIG-3034). These replace the
// const-hoisted SQL in internal/store/presence_reads.go (it was never in the
// inline-sql-gate allowlist — the gate is literal-at-callsite scoped and this
// file passed its SQL as a const identifier). The hand-written Store methods keep
// their signatures and error mapping.
func (q *Queries) AgentHasOpenAsk(ctx context.Context, authorAccountID string) (bool, error) {
	row := q.db.QueryRow(ctx, agentHasOpenAsk, authorAccountID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const sharesVisibleChannel = `-- name: SharesVisibleChannel :one
SELECT EXISTS (
	SELECT 1
	FROM channel_members cm1
	JOIN channel_members cm2 ON cm2.channel_id = cm1.channel_id
	WHERE cm1.account_id = $1
	  AND cm2.account_id = $2
)
`

type SharesVisibleChannelParams struct {
	AccountID   string
	AccountID_2 string
}

func (q *Queries) SharesVisibleChannel(ctx context.Context, arg SharesVisibleChannelParams) (bool, error) {
	row := q.db.QueryRow(ctx, sharesVisibleChannel, arg.AccountID, arg.AccountID_2)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
