// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pull_requests.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteClosingRefLink = `-- name: DeleteClosingRefLink :exec
DELETE FROM pull_request_issue_links
 WHERE pr_forge_provider = $1 AND pr_forge_host = $2 AND pr_repo = $3 AND pr_number = $4
   AND issue_forge_provider = $5 AND issue_forge_host = $6 AND issue_repo = $7
   AND issue_number = $8 AND source = 2
`

type DeleteClosingRefLinkParams struct {
	PrForgeProvider    int16
	PrForgeHost        string
	PrRepo             string
	PrNumber           int64
	IssueForgeProvider int16
	IssueForgeHost     string
	IssueRepo          string
	IssueNumber        int64
}

func (q *Queries) DeleteClosingRefLink(ctx context.Context, arg DeleteClosingRefLinkParams) error {
	_, err := q.db.Exec(ctx, deleteClosingRefLink,
		arg.PrForgeProvider,
		arg.PrForgeHost,
		arg.PrRepo,
		arg.PrNumber,
		arg.IssueForgeProvider,
		arg.IssueForgeHost,
		arg.IssueRepo,
		arg.IssueNumber,
	)
	return err
}

const fallbackIssuesForTarget = `-- name: FallbackIssuesForTarget :many
SELECT DISTINCT c.issue_forge_provider, c.issue_forge_host, c.issue_repo, c.issue_number
  FROM pull_request_issue_links e
  JOIN pull_request_issue_links c
    ON c.tenant_id = e.tenant_id AND c.pr_forge_provider = e.pr_forge_provider
   AND c.pr_forge_host = e.pr_forge_host AND c.pr_repo = e.pr_repo AND c.pr_number = e.pr_number
 WHERE e.source = 1 AND c.source = 2
   AND e.issue_forge_provider = $1 AND e.issue_forge_host = $2
   AND e.issue_repo = $3 AND e.issue_number = $4
 ORDER BY c.issue_forge_provider, c.issue_forge_host, c.issue_repo, c.issue_number
`

type FallbackIssuesForTargetParams struct {
	IssueForgeProvider int16
	IssueForgeHost     string
	IssueRepo          string
	IssueNumber        int64
}

type FallbackIssuesForTargetRow struct {
	IssueForgeProvider int16
	IssueForgeHost     string
	IssueRepo          string
	IssueNumber        int64
}

func (q *Queries) FallbackIssuesForTarget(ctx context.Context, arg FallbackIssuesForTargetParams) ([]FallbackIssuesForTargetRow, error) {
	rows, err := q.db.Query(ctx, fallbackIssuesForTarget,
		arg.IssueForgeProvider,
		arg.IssueForgeHost,
		arg.IssueRepo,
		arg.IssueNumber,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FallbackIssuesForTargetRow
	for rows.Next() {
		var i FallbackIssuesForTargetRow
		if err := rows.Scan(
			&i.IssueForgeProvider,
			&i.IssueForgeHost,
			&i.IssueRepo,
			&i.IssueNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertClosingRefLink = `-- name: InsertClosingRefLink :exec
INSERT INTO pull_request_issue_links
    (pr_forge_provider, pr_forge_host, pr_repo, pr_number,
     issue_forge_provider, issue_forge_host, issue_repo, issue_number, source)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, 2)
ON CONFLICT (tenant_id, pr_forge_provider, pr_forge_host, pr_repo, pr_number,
             issue_forge_provider, issue_forge_host, issue_repo, issue_number)
DO NOTHING
`

type InsertClosingRefLinkParams struct {
	PrForgeProvider    int16
	PrForgeHost        string
	PrRepo             string
	PrNumber           int64
	IssueForgeProvider int16
	IssueForgeHost     string
	IssueRepo          string
	IssueNumber        int64
}

func (q *Queries) InsertClosingRefLink(ctx context.Context, arg InsertClosingRefLinkParams) error {
	_, err := q.db.Exec(ctx, insertClosingRefLink,
		arg.PrForgeProvider,
		arg.PrForgeHost,
		arg.PrRepo,
		arg.PrNumber,
		arg.IssueForgeProvider,
		arg.IssueForgeHost,
		arg.IssueRepo,
		arg.IssueNumber,
	)
	return err
}

const insertPullRequestIfAbsent = `-- name: InsertPullRequestIfAbsent :exec
INSERT INTO pull_requests
    (forge_provider, forge_host, repo, number, forge_state,
     forge_created_at, forge_updated_at, pr)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (tenant_id, forge_provider, forge_host, repo, number) DO NOTHING
`

type InsertPullRequestIfAbsentParams struct {
	ForgeProvider  int16
	ForgeHost      string
	Repo           string
	Number         int64
	ForgeState     string
	ForgeCreatedAt pgtype.Timestamptz
	ForgeUpdatedAt pgtype.Timestamptz
	Pr             []byte
}

// The create path's write: a webhook-hydrated row already present always wins.
func (q *Queries) InsertPullRequestIfAbsent(ctx context.Context, arg InsertPullRequestIfAbsentParams) error {
	_, err := q.db.Exec(ctx, insertPullRequestIfAbsent,
		arg.ForgeProvider,
		arg.ForgeHost,
		arg.Repo,
		arg.Number,
		arg.ForgeState,
		arg.ForgeCreatedAt,
		arg.ForgeUpdatedAt,
		arg.Pr,
	)
	return err
}

const listPullRequestLinks = `-- name: ListPullRequestLinks :many
SELECT issue_forge_provider, issue_forge_host, issue_repo, issue_number, source
  FROM pull_request_issue_links
 WHERE pr_forge_provider = $1 AND pr_forge_host = $2 AND pr_repo = $3 AND pr_number = $4
 ORDER BY issue_forge_provider, issue_forge_host, issue_repo, issue_number
`

type ListPullRequestLinksParams struct {
	PrForgeProvider int16
	PrForgeHost     string
	PrRepo          string
	PrNumber        int64
}

type ListPullRequestLinksRow struct {
	IssueForgeProvider int16
	IssueForgeHost     string
	IssueRepo          string
	IssueNumber        int64
	Source             int16
}

func (q *Queries) ListPullRequestLinks(ctx context.Context, arg ListPullRequestLinksParams) ([]ListPullRequestLinksRow, error) {
	rows, err := q.db.Query(ctx, listPullRequestLinks,
		arg.PrForgeProvider,
		arg.PrForgeHost,
		arg.PrRepo,
		arg.PrNumber,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPullRequestLinksRow
	for rows.Next() {
		var i ListPullRequestLinksRow
		if err := rows.Scan(
			&i.IssueForgeProvider,
			&i.IssueForgeHost,
			&i.IssueRepo,
			&i.IssueNumber,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pullRequestForgeUpdatedAt = `-- name: PullRequestForgeUpdatedAt :one
SELECT forge_updated_at FROM pull_requests
 WHERE forge_provider = $1 AND forge_host = $2 AND repo = $3 AND number = $4
`

type PullRequestForgeUpdatedAtParams struct {
	ForgeProvider int16
	ForgeHost     string
	Repo          string
	Number        int64
}

func (q *Queries) PullRequestForgeUpdatedAt(ctx context.Context, arg PullRequestForgeUpdatedAtParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, pullRequestForgeUpdatedAt,
		arg.ForgeProvider,
		arg.ForgeHost,
		arg.Repo,
		arg.Number,
	)
	var forge_updated_at pgtype.Timestamptz
	err := row.Scan(&forge_updated_at)
	return forge_updated_at, err
}

const pullRequestsForIssues = `-- name: PullRequestsForIssues :many
WITH want AS (
    SELECT unnest($1::smallint[]) AS provider,
           unnest($2::text[]) AS host,
           unnest($3::text[]) AS repo,
           unnest($4::bigint[]) AS number
)
SELECT l.issue_forge_provider, l.issue_forge_host, l.issue_repo, l.issue_number,
       p.forge_provider, p.forge_host, p.repo, p.number, p.forge_state,
       p.forge_created_at, p.forge_updated_at, p.pr
  FROM pull_request_issue_links l
  JOIN want w
    ON l.issue_forge_provider = w.provider AND l.issue_forge_host = w.host
   AND l.issue_repo = w.repo AND l.issue_number = w.number
  JOIN pull_requests p
    ON p.tenant_id = l.tenant_id AND p.forge_provider = l.pr_forge_provider
   AND p.forge_host = l.pr_forge_host AND p.repo = l.pr_repo AND p.number = l.pr_number
 WHERE l.source = 1
    OR NOT EXISTS (
        SELECT 1
          FROM pull_request_issue_links e
          JOIN issues i
            ON i.tenant_id = e.tenant_id AND i.forge_provider = e.issue_forge_provider
           AND i.forge_host = e.issue_forge_host AND i.repo = e.issue_repo
           AND i.number = e.issue_number
         WHERE e.source = 1 AND e.tenant_id = l.tenant_id
           AND e.pr_forge_provider = l.pr_forge_provider AND e.pr_forge_host = l.pr_forge_host
           AND e.pr_repo = l.pr_repo AND e.pr_number = l.pr_number)
 ORDER BY p.forge_created_at, p.forge_provider, p.forge_host, p.repo, p.number
`

type PullRequestsForIssuesParams struct {
	IssueProviders []int16
	IssueHosts     []string
	IssueRepos     []string
	IssueNumbers   []int64
}

type PullRequestsForIssuesRow struct {
	IssueForgeProvider int16
	IssueForgeHost     string
	IssueRepo          string
	IssueNumber        int64
	ForgeProvider      int16
	ForgeHost          string
	Repo               string
	Number             int64
	ForgeState         string
	ForgeCreatedAt     pgtype.Timestamptz
	ForgeUpdatedAt     pgtype.Timestamptz
	Pr                 []byte
}

// Explicit links attach directly; a closing reference attaches only when none
// of the PR's explicit targets is an issue on the board.
func (q *Queries) PullRequestsForIssues(ctx context.Context, arg PullRequestsForIssuesParams) ([]PullRequestsForIssuesRow, error) {
	rows, err := q.db.Query(ctx, pullRequestsForIssues,
		arg.IssueProviders,
		arg.IssueHosts,
		arg.IssueRepos,
		arg.IssueNumbers,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PullRequestsForIssuesRow
	for rows.Next() {
		var i PullRequestsForIssuesRow
		if err := rows.Scan(
			&i.IssueForgeProvider,
			&i.IssueForgeHost,
			&i.IssueRepo,
			&i.IssueNumber,
			&i.ForgeProvider,
			&i.ForgeHost,
			&i.Repo,
			&i.Number,
			&i.ForgeState,
			&i.ForgeCreatedAt,
			&i.ForgeUpdatedAt,
			&i.Pr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertExplicitPullRequestLink = `-- name: UpsertExplicitPullRequestLink :exec
INSERT INTO pull_request_issue_links
    (pr_forge_provider, pr_forge_host, pr_repo, pr_number,
     issue_forge_provider, issue_forge_host, issue_repo, issue_number, source)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, 1)
ON CONFLICT (tenant_id, pr_forge_provider, pr_forge_host, pr_repo, pr_number,
             issue_forge_provider, issue_forge_host, issue_repo, issue_number)
DO UPDATE SET source = 1
`

type UpsertExplicitPullRequestLinkParams struct {
	PrForgeProvider    int16
	PrForgeHost        string
	PrRepo             string
	PrNumber           int64
	IssueForgeProvider int16
	IssueForgeHost     string
	IssueRepo          string
	IssueNumber        int64
}

func (q *Queries) UpsertExplicitPullRequestLink(ctx context.Context, arg UpsertExplicitPullRequestLinkParams) error {
	_, err := q.db.Exec(ctx, upsertExplicitPullRequestLink,
		arg.PrForgeProvider,
		arg.PrForgeHost,
		arg.PrRepo,
		arg.PrNumber,
		arg.IssueForgeProvider,
		arg.IssueForgeHost,
		arg.IssueRepo,
		arg.IssueNumber,
	)
	return err
}

const upsertPullRequestGuarded = `-- name: UpsertPullRequestGuarded :execrows
INSERT INTO pull_requests
    (forge_provider, forge_host, repo, number, forge_state,
     forge_created_at, forge_updated_at, pr)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (tenant_id, forge_provider, forge_host, repo, number) DO UPDATE
   SET forge_state = EXCLUDED.forge_state,
       forge_created_at = EXCLUDED.forge_created_at,
       forge_updated_at = EXCLUDED.forge_updated_at,
       pr = EXCLUDED.pr
 WHERE EXCLUDED.forge_updated_at >= pull_requests.forge_updated_at
`

type UpsertPullRequestGuardedParams struct {
	ForgeProvider  int16
	ForgeHost      string
	Repo           string
	Number         int64
	ForgeState     string
	ForgeCreatedAt pgtype.Timestamptz
	ForgeUpdatedAt pgtype.Timestamptz
	Pr             []byte
}

// Zero rows affected means the stored row is newer and the write was skipped.
func (q *Queries) UpsertPullRequestGuarded(ctx context.Context, arg UpsertPullRequestGuardedParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertPullRequestGuarded,
		arg.ForgeProvider,
		arg.ForgeHost,
		arg.Repo,
		arg.Number,
		arg.ForgeState,
		arg.ForgeCreatedAt,
		arg.ForgeUpdatedAt,
		arg.Pr,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
