// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// The tenant an account belongs to. A system-role caller (the delivery loop) reads
	// it to act for that account under its own tenant.
	AccountTenant(ctx context.Context, id string) (string, error)
	AccountVisibleTo(ctx context.Context, arg AccountVisibleToParams) (bool, error)
	AcquireOwnerTreeLock(ctx context.Context, hashtext string) error
	ActivityFor(ctx context.Context, dollar_1 []string) ([]ActivityForRow, error)
	AdvanceDeliveryCursor(ctx context.Context, arg AdvanceDeliveryCursorParams) error
	AdvanceForgeDeliveredRevision(ctx context.Context, arg AdvanceForgeDeliveredRevisionParams) (int64, error)
	// Compare-and-set advance for the notify-router suppress path: the write lands
	// only when delivered_revision still equals $4 (the prior value the router read),
	// so a concurrent route cannot erase a delivery gap it did not observe. Scoped to
	// the owning agent (id AND agent_account_id). Zero rows affected is a lost CAS
	// (someone else advanced first), NOT an error — the wrapper reports it as
	// advanced=false.
	AdvanceForgeDeliveredRevisionCAS(ctx context.Context, arg AdvanceForgeDeliveredRevisionCASParams) (int64, error)
	// AdvanceTokenUsagePruneHorizon commits before the prune deletes anything, and
	// waits for a rebuild that holds the old horizon. It only moves forward.
	AdvanceTokenUsagePruneHorizon(ctx context.Context, cutoff pgtype.Timestamptz) (int64, error)
	AgentForContainer(ctx context.Context, containerName string) (string, error)
	// Presence-component read queries (sqlc adoption T4, RIG-3034). These replace the
	// const-hoisted SQL in internal/store/presence_reads.go (it was never in the
	// inline-sql-gate allowlist — the gate is literal-at-callsite scoped and this
	// file passed its SQL as a const identifier). The hand-written Store methods keep
	// their signatures and error mapping.
	AgentHasOpenAsk(ctx context.Context, authorAccountID string) (bool, error)
	// Agent-tree queries (sqlc adoption T2, RIG-3034). These replace the
	// const-hoisted `agentTreeProjection` + per-caller WHERE composition that lived
	// in internal/store/agent_tree.go and was run through the `queryAgents` helper —
	// exactly the "SQL in a variable" shape the inline-SQL gate cannot grep. Each of
	// the three tree reads is now a full, static, schema-checked query.
	//
	// The projection is column-identical to the former agentTreeProjection: the join
	// to agent_accounts is INNER (the tree is agents-only), so every row scans back
	// through the shared accountFromRow mapping (fed by treeAccountText) into a domain Account with its
	// Agent subtype set. The two `role` columns are aliased (user_role / agent_role)
	// so the generated row fields do not collide.
	AgentNeighborhood(ctx context.Context, id string) ([]AgentNeighborhoodRow, error)
	AgentOwnersByIDs(ctx context.Context, dollar_1 []string) ([]string, error)
	AgentSubtree(ctx context.Context, accountID string) ([]AgentSubtreeRow, error)
	// Feeds isAgentWorkspaceVisible: membership on the agent's home channel.
	AgentWorkspaceVisible(ctx context.Context, arg AgentWorkspaceVisibleParams) (bool, error)
	AgentsByOwner(ctx context.Context, ownerUserID string) ([]AgentsByOwnerRow, error)
	// AppendTokenUsageEvents inserts a batch and adds only the events it inserted
	// to both rollups, so a replayed id counts once. The arrays hold one element
	// per event, and no id repeats.
	AppendTokenUsageEvents(ctx context.Context, arg AppendTokenUsageEventsParams) error
	AuthoredArtifactByCoordinate(ctx context.Context, arg AuthoredArtifactByCoordinateParams) (ForgeAuthoredArtifact, error)
	AuthoredArtifactByRequestID(ctx context.Context, arg AuthoredArtifactByRequestIDParams) (ForgeAuthoredArtifact, error)
	// Agent-transcript queries (sqlc adoption T5, RIG-3034). These replace the
	// inline SQL literals in internal/store/agent_transcripts.go; the hand-written
	// Store methods keep their exact signatures and own the two-tier flush
	// orchestration (PUT-before-prune, the RepeatableRead/ReadOnly resume snapshot
	// tx, the safety-valve cut-point loop) plus the uint64<->int64 seq narrowing
	// (toInt64/toUint64). They map generated rows into TranscriptEntryRow and
	// ArchiveSegmentRow (via the transcriptRowsFromDB/segmentRowsFromDB helpers).
	//
	// COALESCE(MAX/SUM(...), 0) sites carry an explicit ::BIGINT cast so sqlc types
	// them int64 rather than interface{} (mirrors messages.sql MessagesHeadSeq). The
	// SessionTranscript and SafetyValveSegments reads are each issued on BOTH the
	// pool (the eponymous method) and a snapshot tx (SessionResumeSnapshot, via
	// WithTx), so one generated query backs both call sites.
	BindLifetime(ctx context.Context, arg BindLifetimeParams) (int64, error)
	ChannelAgentMembers(ctx context.Context, arg ChannelAgentMembersParams) ([]string, error)
	ChannelGroupVisibleTo(ctx context.Context, arg ChannelGroupVisibleToParams) (bool, error)
	ChannelMemberExists(ctx context.Context, arg ChannelMemberExistsParams) (bool, error)
	ChannelMemberIDs(ctx context.Context, channelID string) ([]string, error)
	ChannelMembersByChannelIDs(ctx context.Context, dollar_1 []string) ([]ChannelMembersByChannelIDsRow, error)
	ChannelVisibleTo(ctx context.Context, arg ChannelVisibleToParams) (bool, error)
	ChannelsByNameForViewer(ctx context.Context, arg ChannelsByNameForViewerParams) ([]ChannelsByNameForViewerRow, error)
	// The unique key makes concurrent first-run attempts a single-winner claim.
	ClaimTourStart(ctx context.Context, arg ClaimTourStartParams) (string, error)
	ClearOwedMention(ctx context.Context, arg ClearOwedMentionParams) (int64, error)
	// Close intervals only after both binding deletion and its end event are absent.
	// The tenant id comes from each start because the system role has no tenant GUC.
	CloseOrphanedComputeIntervals(ctx context.Context) (int64, error)
	CollectSegment(ctx context.Context, arg CollectSegmentParams) ([]CollectSegmentRow, error)
	// Single-statement clear-and-return: the row is claimed and its actor returned
	// in ONE UPDATE, so a memo attributes at most one event and a concurrent second
	// reader matches nothing (consumed_at is no longer NULL). A state mismatch or a
	// memo written before the freshness bound matches nothing either — no actor,
	// which is the correct answer for every human/external transition.
	ConsumeStateTransition(ctx context.Context, arg ConsumeStateTransitionParams) (string, error)
	ConvertDMChannel(ctx context.Context, arg ConvertDMChannelParams) error
	CoordinationReports(ctx context.Context, parentAgentID pgtype.Text) ([]string, error)
	CountAgentForgeSubscriptionsForArtifact(ctx context.Context, arg CountAgentForgeSubscriptionsForArtifactParams) (int64, error)
	CountAgentMembers(ctx context.Context, channelID string) (int64, error)
	CountChannelPins(ctx context.Context, channelID string) (CountChannelPinsRow, error)
	CountOwedMentions(ctx context.Context) (int64, error)
	CountRootAgents(ctx context.Context, ownerUserID string) (int64, error)
	CurrentAgentConfig(ctx context.Context) (CurrentAgentConfigRow, error)
	// Model-registry queries (RIG-3122 P2). Back the hand-written Store methods in
	// internal/store/model_registry.go, which own the fail-closed payload
	// validation (ValidateModelRegistry), the JSONB marshal/unmarshal, and the
	// ErrVersionConflict/ErrNotFound mapping. The registry is a fleet-wide singleton
	// row (singleton = TRUE) with a monotonic version supplying the CAS substrate:
	// a write only lands if the row still holds the version the caller read.
	CurrentModelRegistry(ctx context.Context) (CurrentModelRegistryRow, error)
	// DeclaredSecrets is the names-only view the SERVER SpecResolver's declarations
	// interface still consumes (value-free, all scopes).
	DeclaredSecrets(ctx context.Context) ([]DeclaredSecretsRow, error)
	DeclaredServerSecrets(ctx context.Context) ([]ServerSecret, error)
	DeleteAgentConfig(ctx context.Context) error
	// Scoped to the calling agent (id AND agent). RETURNING the coordinate drives the
	// one-tx GC of the artifact cursor when this was the last subscription.
	DeleteAgentForgeSubscription(ctx context.Context, arg DeleteAgentForgeSubscriptionParams) (DeleteAgentForgeSubscriptionRow, error)
	DeleteAgentPlacement(ctx context.Context, containerName string) error
	DeleteChannelMember(ctx context.Context, arg DeleteChannelMemberParams) (int64, error)
	DeleteChannelPin(ctx context.Context, arg DeleteChannelPinParams) error
	DeleteChannelPinReturningPosition(ctx context.Context, arg DeleteChannelPinReturningPositionParams) (int32, error)
	DeleteModelRegistry(ctx context.Context) error
	// DeleteSecret addresses one scope coordinate — a name alone no longer
	// identifies a row (composite PK).
	DeleteSecret(ctx context.Context, arg DeleteSecretParams) (int64, error)
	DeleteServerSecret(ctx context.Context, name string) (int64, error)
	// Both deletes also write an estimated start for a binding an older server made
	// without one; ON CONFLICT keeps any real start.
	DeleteSessionBinding(ctx context.Context, sessionID string) error
	// DeleteSessionBinding limited to one write of the row: a re-bind since that
	// write set a new binding_version, so it is left alone. Returns rows removed;
	// Postgres runs every data-modifying CTE to completion.
	DeleteSessionBindingVersion(ctx context.Context, arg DeleteSessionBindingVersionParams) (int64, error)
	// The reconnect sweep, run by Hub.enroll under the system role because a Runner
	// is shared across tenants. :many with RETURNING: each removed row drives a
	// presence DISCONNECTED edge, a held-deliver reap, and a tenant-scoped archive.
	// DELETE ... RETURNING takes no ORDER BY, so the Store method sorts by session id.
	DeleteSessionBindingsForRunner(ctx context.Context, runnerID string) ([]DeleteSessionBindingsForRunnerRow, error)
	// DeleteTokenUsageEventsBefore deletes old events of the tx's tenant only,
	// because row-level security scopes it. The prune runs it once per tenant.
	DeleteTokenUsageEventsBefore(ctx context.Context, cutoff pgtype.Timestamptz) (int64, error)
	// DeleteTokenUsageRollupsFrom drops both rollups from the horizon on. Older
	// rollups can hold pruned events, so they stay.
	DeleteTokenUsageRollupsFrom(ctx context.Context, horizon pgtype.Timestamptz) error
	DeleteTopic(ctx context.Context, id string) error
	// The account owner is read in SQL so callers continue to supply only the
	// session binding identity.
	EndComputeUsageInterval(ctx context.Context, arg EndComputeUsageIntervalParams) error
	// Agent-forge-subscription / artifact-cursor queries (sqlc adoption T6,
	// RIG-3034). These replace the inline SQL literals in
	// internal/store/forge_subscriptions.go; the hand-written Store methods keep
	// their signatures, the door-side validation (validSubscriptionCoordinate /
	// validCoordinate), the scope normalization, the ErrConflict/ErrInvalidArgument/
	// ErrNotFound mapping via pgErrIs, and the two hand-written tx seams: the
	// DeleteAgentForgeSubscription GC (WithTx) and the ListForgeNotifyTargets row
	// grouping. The read queries feed the ForgeNotifySubscriber / ForgeArtifactCursor
	// / ForgeNotifyTarget mappers, which convert the generated rows (provider/kind
	// ints, BIGINT numbers, LEFT-JOIN-nullable cursor columns) back to the domain
	// types.
	// Idempotent on the UNIQUE coordinate: the no-op DO UPDATE (re-set agent to
	// itself) makes RETURNING fire on conflict so a repeat returns the stored id.
	EnsureAgentForgeSubscription(ctx context.Context, arg EnsureAgentForgeSubscriptionParams) (string, error)
	EnsureChannelMember(ctx context.Context, arg EnsureChannelMemberParams) error
	// A binding an older server wrote during a rolling deploy has no start event.
	// Its created_at is the best start we hold, so the start is marked estimated.
	EnsureComputeUsageIntervalStart(ctx context.Context, agentAccountID string) error
	EnsureForgeRepoSubscription(ctx context.Context, arg EnsureForgeRepoSubscriptionParams) error
	FindAskMessage(ctx context.Context, arg FindAskMessageParams) ([]FindAskMessageRow, error)
	ForgeScopeUserExists(ctx context.Context, accountID string) (bool, error)
	// Collects the coordinate's cursor IFF no subscription for it remains (the NOT
	// EXISTS guard leaves it in place if any other agent still subscribes).
	GCForgeArtifactCursorIfUnsubscribed(ctx context.Context, arg GCForgeArtifactCursorIfUnsubscribedParams) error
	GetAccount(ctx context.Context, id string) (GetAccountRow, error)
	GetAccountByGlobalHandle(ctx context.Context, handle string) (GetAccountByGlobalHandleRow, error)
	GetAccountByOwnerHandle(ctx context.Context, arg GetAccountByOwnerHandleParams) (GetAccountByOwnerHandleRow, error)
	GetAccountHandle(ctx context.Context, accountID string) (string, error)
	GetAgentOwner(ctx context.Context, accountID string) (string, error)
	GetAgentParent(ctx context.Context, accountID string) (pgtype.Text, error)
	GetAgentWorkspaceID(ctx context.Context, agentAccountID string) (string, error)
	GetChannel(ctx context.Context, id string) (GetChannelRow, error)
	GetChannelGroupVisibility(ctx context.Context, id string) (int16, error)
	// Message-domain queries (sqlc adoption T4, RIG-3034). These replace the inline
	// SQL literals in internal/store/messages.go; the hand-written Store methods keep
	// their exact signatures, their tx orchestration (AppendMessage/AnswerAsk begin
	// and commit their own txns), the ON CONFLICT idempotency signalling
	// (errMessageInsertConflict), the JSONB block (de)serialization, and the D9
	// not-found/forbidden error mapping — all hand-written around these generated
	// calls. Every message read shares the id/topic_id/author_account_id/author_handle/
	// at_unix_ms/blocks projection so the Go maps each row through messageFromParts.
	GetChannelPostPolicy(ctx context.Context, id string) (GetChannelPostPolicyRow, error)
	GetCoordinationChannelByName(ctx context.Context, arg GetCoordinationChannelByNameParams) (GetCoordinationChannelByNameRow, error)
	// Coordination-store queries (sqlc adoption T3, RIG-3034). These replace the
	// inline SQL literals in internal/store/coordination.go; the hand-written Store
	// methods keep their signatures, the per-owner advisory-lock discipline, the
	// suffix-search resolution loop, and the WithTx seam (which stays hand-written).
	// The member INSERT/DELETE reuse EnsureChannelMember (accounts.sql) and
	// DeleteChannelMember (channels.sql) — the statements are identical.
	GetCoordinationGroup(ctx context.Context, arg GetCoordinationGroupParams) (string, error)
	GetDMChannelByName(ctx context.Context, arg GetDMChannelByNameParams) (GetDMChannelByNameRow, error)
	// Feeds isReservedGroupTx: the reserved-group discriminator (top-level AND a reserved name AND
	// VisibilityOwner) the CreateChannel and CreateChannelGroup create-guards key on.
	GetGroupNameVisibility(ctx context.Context, id string) (GetGroupNameVisibilityRow, error)
	GetIssue(ctx context.Context, id string) (GetIssueRow, error)
	GetLinearRoutingChannel(ctx context.Context, arg GetLinearRoutingChannelParams) (GetLinearRoutingChannelRow, error)
	// Linear routing channel queries: the admin's reserved __linear__ group and the one
	// routing channel inside it, keyed by (group, name) so a planted look-alike is never adopted.
	// Visibility-discriminated like GetOwnerDMGroup: a planted wider __linear__ group is never adopted.
	GetLinearRoutingGroup(ctx context.Context, arg GetLinearRoutingGroupParams) (string, error)
	GetMessageBlocksAsAuthor(ctx context.Context, arg GetMessageBlocksAsAuthorParams) ([]byte, error)
	GetMessageByRequestID(ctx context.Context, arg GetMessageByRequestIDParams) ([]GetMessageByRequestIDRow, error)
	// Peer-DM channel queries (sqlc adoption T6, RIG-3034; dm.go was added to the
	// store after the design record froze — the record's "plus any residue"). These
	// replace the inline SQL literals in internal/store/dm.go; the hand-written Store
	// methods keep their signatures and every seam that is NOT a single statement:
	// the per-owner advisory lock (LockDM), the resolution/insert loop, the R3
	// verify-reconcile belt, the transitive-owner membership expansion, and the
	// cursor seeding (seedChannelDeliveryCursors, delivery_cursors.sql). The member
	// INSERTs reuse EnsureChannelMember (accounts.sql) — the statement is identical.
	// Visibility-discriminated get-half: a wider (SHARED) planted __dm__ group must
	// NEVER be adopted, so visibility = $3 (bound to VisibilityOwner) excludes it.
	GetOwnerDMGroup(ctx context.Context, arg GetOwnerDMGroupParams) (string, error)
	GetPageCursorSeq(ctx context.Context, arg GetPageCursorSeqParams) (int64, error)
	// server_key_state queries: the master-key tripwire. Single-row by construction
	// (CHECK (id = 1)); GetServerKeyState reads it, InsertServerKeyState writes it
	// once at first boot. No UPDATE and no DELETE here: rotation is a later
	// record's versioned re-encrypt. The tripwire catches an operator booting the
	// wrong key, not an actor with write access to this table -- UPDATE is granted,
	// so a write-capable actor could restate the digest.
	GetServerKeyState(ctx context.Context) (ServerKeyState, error)
	GetTopic(ctx context.Context, id string) (Topic, error)
	GetTopicByName(ctx context.Context, arg GetTopicByNameParams) (GetTopicByNameRow, error)
	GetTopicChannel(ctx context.Context, id string) (string, error)
	// The caller is bound to one tenant by the store's scoped query path.
	GetTourState(ctx context.Context, accountID string) (GetTourStateRow, error)
	// Scope grants are managed for user accounts; agents inherit their owner's rows.
	// The SELECT runs under RLS, so a user from another tenant inserts nothing.
	GrantForgeScope(ctx context.Context, arg GrantForgeScopeParams) (int64, error)
	// Feeds requireGroupCreateAuthz: owner, agent-owner, or SHARED-visibility group.
	GroupCreateAuthorized(ctx context.Context, arg GroupCreateAuthorizedParams) (bool, error)
	HasForgeScope(ctx context.Context, arg HasForgeScopeParams) (bool, error)
	HotTailBytes(ctx context.Context, arg HotTailBytesParams) (int64, error)
	HotTailSizes(ctx context.Context, arg HotTailSizesParams) ([]HotTailSizesRow, error)
	InSweepSet(ctx context.Context, arg InSweepSetParams) (bool, error)
	// Account-domain queries (sqlc adoption T2, RIG-3034). These replace the inline
	// SQL literals that lived in internal/store/accounts.go; the hand-written Store
	// methods keep their exact signatures and wrap these generated calls, mapping the
	// generated row structs back to the domain Account (see accountFromRow, and
	// accountFromRow via treeAccountText for the tree rows, in the Go).
	//
	// The account projection (a.id … sy.account_id) is repeated per query because
	// sqlc has no query-fragment composition. It is column-identical to the former
	// scanAccount projection (accounts LEFT JOIN user_accounts LEFT JOIN
	// agent_accounts LEFT JOIN system_accounts), with the two `role` columns aliased
	// (user_role / agent_role) so the generated row fields do not collide. The
	// account-visibility predicate (formerly the accountVisibleFromWhere Go const) is
	// likewise inlined into each read that needs it; the four copies MUST stay
	// textually identical so the roster clip cannot drift from the ListAccounts read.
	InsertAccount(ctx context.Context, arg InsertAccountParams) error
	InsertAccountHandle(ctx context.Context, arg InsertAccountHandleParams) error
	InsertAgentAccount(ctx context.Context, arg InsertAgentAccountParams) error
	// Agent-session queries (sqlc adoption T5, RIG-3034). These replace the inline
	// SQL literals that lived in internal/store/agent_sessions.go; the hand-written
	// Store methods keep their exact signatures and wrap these generated calls,
	// mapping AccountID newtypes and the not-found/forbidden merge (D9) by hand. No
	// domain xFromRow mapper — the session reads project scalar columns the methods
	// return directly.
	InsertAgentSession(ctx context.Context, arg InsertAgentSessionParams) error
	InsertAgentWorkspaceIgnore(ctx context.Context, arg InsertAgentWorkspaceIgnoreParams) error
	InsertArchiveSegment(ctx context.Context, arg InsertArchiveSegmentParams) error
	InsertChannel(ctx context.Context, arg InsertChannelParams) error
	// Channel-domain queries (sqlc adoption T3, RIG-3034). These replace the inline
	// SQL literals that lived in internal/store/channels.go; the hand-written Store
	// methods keep their exact signatures and wrap these generated calls, mapping
	// the generated row structs back to the domain Channel / ChannelGroup.
	//
	// The channel-visibility CTE (effective(id, eff_vis)) and the channel/group
	// visibility predicates are repeated per read because sqlc has no query-fragment
	// composition — they replace the former channels.go const fragments
	// (effectiveVisibilityCTE / viewerCTE / channelVisiblePredicate /
	// groupVisiblePredicate). The copies MUST stay textually identical so the stream
	// edge's single-id visibility check cannot drift from the list read (the
	// anti-drift guarantee the design record requires).
	InsertChannelGroup(ctx context.Context, arg InsertChannelGroupParams) error
	InsertChannelPin(ctx context.Context, arg InsertChannelPinParams) error
	InsertCoordinationChannel(ctx context.Context, arg InsertCoordinationChannelParams) (string, error)
	InsertCoordinationGroup(ctx context.Context, arg InsertCoordinationGroupParams) error
	// Born kind=DM, zero-value policy (OPEN, ownerless) + mandatory; poison-free via
	// ON CONFLICT DO NOTHING on the partial unique index (a concurrent open yields
	// zero rows, never a raised unique-violation).
	InsertDMChannel(ctx context.Context, arg InsertDMChannelParams) (string, error)
	InsertHomeChannel(ctx context.Context, arg InsertHomeChannelParams) error
	// ON CONFLICT DO NOTHING keeps a lost race from poisoning the tx; the caller re-selects.
	InsertLinearRoutingChannel(ctx context.Context, arg InsertLinearRoutingChannelParams) (string, error)
	InsertLinearRoutingGroup(ctx context.Context, arg InsertLinearRoutingGroupParams) error
	InsertMessage(ctx context.Context, arg InsertMessageParams) (InsertMessageRow, error)
	// InsertModelRegistry seeds the FIRST registry (the caller read no row, expected
	// version 0). ON CONFLICT DO NOTHING makes it a CAS: it lands only when the
	// singleton is still absent, so a racing seed loses (zero rows, ErrNoRows via
	// RETURNING) rather than clobbering the winner. The seeded version is 1.
	InsertModelRegistry(ctx context.Context, registry []byte) (int64, error)
	InsertOwnerDMGroup(ctx context.Context, arg InsertOwnerDMGroupParams) error
	InsertServerKeyState(ctx context.Context, arg InsertServerKeyStateParams) error
	// Server-secrets registry queries (design record T0, mechanism C1/D6). The
	// SERVER-owned half of the names-only secret registry, physically separate from
	// `secrets` so the inject-all container delivery path can never see these rows.
	// The hand-written Store methods keep the door-side validation (name grammar,
	// reserved-prefix guard) and the ErrConflict/ErrInvalidArgument/ErrNotFound
	// mapping, mirroring the `secrets` methods minus delivery/kind/provider/host.
	//
	// declared_by is NULLABLE here: a server-provisioned row (the master key) has no
	// human actor, so it is written as NULL rather than attributed to the
	// bootstrap-admin account.
	InsertServerSecret(ctx context.Context, arg InsertServerSecretParams) error
	InsertSystemAccount(ctx context.Context, accountID string) error
	// Tenant-bootstrap queries (sqlc adoption T6, RIG-3034). These replace the inline
	// SQL literals in internal/store/tenant.go; the hand-written Store methods keep
	// their signatures and the unique-violation-means-fetch idempotent bootstrap
	// shape (BootstrapTenant falls back to TenantIDBySlug on a duplicate slug).
	InsertTenant(ctx context.Context, arg InsertTenantParams) error
	// Token-domain queries (sqlc adoption T6, RIG-3034). These replace the inline
	// SQL literals in internal/store/tokens.go; the hand-written Store methods keep
	// their signatures, the ErrConflict/ErrNotFound/ErrTokenRevoked mapping, and the
	// RowsAffected branching (RevokeToken is :execrows). ResolveTokenHash maps the
	// generated row (subject_kind/subject_id/tenant_id/revoked) back to the domain Subject.
	InsertTokenHash(ctx context.Context, arg InsertTokenHashParams) error
	InsertTopicIgnore(ctx context.Context, arg InsertTopicIgnoreParams) error
	InsertTranscriptEntry(ctx context.Context, arg InsertTranscriptEntryParams) (int64, error)
	InsertUserAccount(ctx context.Context, arg InsertUserAccountParams) error
	IsAgentAccount(ctx context.Context, accountID string) (bool, error)
	IsEnabledForgeRepo(ctx context.Context, repo string) (bool, error)
	// Secrets-registry queries (sqlc adoption T6, RIG-3034). These back the
	// hand-written Store methods, which keep their signatures, the door-side
	// validation (name grammar, kind/routing, A9 scope shape), the
	// ErrConflict/ErrInvalidArgument/ErrNotFound mapping, and the RowsAffected
	// branch (DeleteSecretDeclaration is :execrows).
	//
	// DeclaredSecrets is the retained value-free READ path (the SERVER SpecResolver's
	// declarations view); the scoped, encrypted path is UpsertSecret +
	// SecretRecordsForAgent (A1/A9), now the sole writer.
	// IsUserAccount reports whether an id names a human account — the user-scope
	// (scope_kind 1) referential check the UpsertSecret door runs in lieu of an FK
	// (A9). The agent-scope check reuses IsAgentAccount.
	IsUserAccount(ctx context.Context, accountID string) (bool, error)
	LatestCheckpointSeq(ctx context.Context, sessionID string) (int64, error)
	LatestSessionForAccount(ctx context.Context, agentAccountID string) (string, error)
	LinearAgentSession(ctx context.Context, linearSessionID string) (LinearAgentSessionRow, error)
	ListAgentPlacementsForRunner(ctx context.Context, runnerID string) ([]ListAgentPlacementsForRunnerRow, error)
	ListAuthoredArtifactsByAgent(ctx context.Context, agentAccountID string) ([]ForgeAuthoredArtifact, error)
	ListChannelGroups(ctx context.Context, accountID string) ([]ListChannelGroupsRow, error)
	ListChannels(ctx context.Context, accountID string) ([]ListChannelsRow, error)
	ListEnabledForgeRepoSubscriptions(ctx context.Context, arg ListEnabledForgeRepoSubscriptionsParams) ([]ListEnabledForgeRepoSubscriptionsRow, error)
	ListEnabledForgeRepos(ctx context.Context) ([]string, error)
	// The reconcile sweep's work list for one (provider, host): each subscribed
	// coordinate with its LEFT-JOINed shared FETCH cursor (nullable when never
	// observed) and the subscriber rows, container-scope rows collapsed per
	// (repo, kind) to coord_number 0. The Go groups the flat rows into targets.
	ListForgeNotifyTargets(ctx context.Context, arg ListForgeNotifyTargetsParams) ([]ListForgeNotifyTargetsRow, error)
	ListForgeScopeRepos(ctx context.Context, arg ListForgeScopeReposParams) ([]string, error)
	ListIssues(ctx context.Context) ([]ListIssuesRow, error)
	ListMessages(ctx context.Context, arg ListMessagesParams) ([]ListMessagesRow, error)
	// ListTenantIDs lists every tenant. tenants has no row-level security, so the
	// app role sees them all without the BYPASSRLS system role.
	ListTenantIDs(ctx context.Context) ([]string, error)
	// Topic-domain queries (sqlc adoption T4, RIG-3034). These replace the inline
	// SQL literals in internal/store/topics.go; the hand-written Store methods keep
	// their signatures, the UpdateTopic tx orchestration, the rename/merge resolution
	// loop, and the D9 not-found/forbidden error mapping. The topic projection
	// (id, channel_id, name, created_by_account_id, created_at_unix_ms, archived,
	// last_seq) matches the former scanTopics order so the Go maps each row to Topic.
	ListTopics(ctx context.Context, arg ListTopicsParams) ([]Topic, error)
	ListVisibleAccounts(ctx context.Context, id string) ([]ListVisibleAccountsRow, error)
	LoadDeliveryCursor(ctx context.Context, arg LoadDeliveryCursorParams) (LoadDeliveryCursorRow, error)
	LoadForgeArtifactCursor(ctx context.Context, arg LoadForgeArtifactCursorParams) (LoadForgeArtifactCursorRow, error)
	// Forge repo-subscription / watermark queries (sqlc adoption T6, RIG-3034). These
	// replace the inline SQL literals in internal/store/forge_cursors.go; the
	// hand-written Store methods keep their signatures, the door-side validation
	// (validCoordinate), the ErrNotFound mapping, and the RowsAffected branches
	// (StoreForgeRepoWatermark / SetForgeRepoSubscriptionEnabled are :execrows). The
	// read methods map the generated rows (provider int, nullable swept_updated_at)
	// back to the domain time.Time / ForgeRepoSubscription.
	LoadForgeRepoWatermark(ctx context.Context, arg LoadForgeRepoWatermarkParams) (LoadForgeRepoWatermarkRow, error)
	// Channel-pins (pinned board) queries (sqlc adoption T3, RIG-3034). These
	// replace the inline SQL literals in internal/store/channel_pins.go; the
	// hand-written Store methods and the in-tx FOR UPDATE lock / cap-check control
	// flow stay exactly as they were and wrap these generated calls.
	LockChannelForPins(ctx context.Context, id string) (LockChannelForPinsRow, error)
	LockChannelMandatoryKind(ctx context.Context, id string) (LockChannelMandatoryKindRow, error)
	LockChannelPolicy(ctx context.Context, id string) (LockChannelPolicyRow, error)
	LockLinearRouting(ctx context.Context, dollar_1 pgtype.Text) error
	LockOwnerCoordination(ctx context.Context, dollar_1 pgtype.Text) error
	LockOwnerDM(ctx context.Context, dollar_1 pgtype.Text) error
	// Session-binding queries (RIG-3108 / RIG-2861 §T4): the durable
	// (session -> agent account, Runner) binding the RunnerHub has so far held only
	// in RAM. The hand-written Store methods in internal/store/session_bindings.go
	// map these rows into the SessionBinding domain struct (the AccountID newtype is
	// done inline in the Go, as agent_placements does).
	//
	// These request-path queries rely on SET LOCAL ROLE compass_app and the
	// compass.tenant_id GUC for RLS and tenant defaults. Delete queries carry the
	// deleted binding's tenant_id into their end-event insert explicitly.
	//
	// Under WithSystemRole (BYPASSRLS, no tenant GUC) these queries run cross-tenant:
	//
	//   * SessionBindingForAccount / SessionBindingAccount / SessionBindingForUpdate
	//     are :one, so a predicate matching rows in several tenants returns an
	//     arbitrary tenant's row without error.
	//   * RecordSessionBinding does not fail closed: tenant_id DEFAULTs from the GUC,
	//     which a pooled connection may leave empty, landing a row no tenant can see.
	//   * DeleteSessionBindingsForRunner sweeps every tenant's bindings for that
	//     runner id. Hub.enroll calls it this way on purpose, since a Runner is shared
	//     across tenants; the returned tenant_id scopes each archive and end event.
	//
	// SessionBindingTenants is the other deliberate system-role read.
	// session_bindings_pgtest_test.go pins the :one behaviour.
	//
	// updated_at is maintained by the set_updated_at() trigger, never here.
	//
	// The per-account serialization the bind takes FIRST, before it reads anything.
	// Auto-released at transaction end. It mirrors LockOwnerDM / LockOwnerCoordination
	// / AcquireOwnerTreeLock, with a DISTINCT key domain ('binding:') so a bind never
	// serializes behind a DM open, a coordination reconcile, or a reparent. hashtext
	// widens the text key to the int the advisory lock takes; a hash collision across
	// two accounts is a benign redundant wait, never a wrong result.
	//
	// It is keyed on TENANT AND ACCOUNT. Every other lock in this package keys on an
	// account id alone, which is globally unique — but two tenants can legitimately
	// hold bindings for one account id (the PK is folded, see 0001_init.sql), and
	// those two binds are independent operations that must not block each other.
	//
	// Why an advisory lock and not just the row lock below: FOR UPDATE on a row that
	// does NOT exist locks NOTHING, so two concurrent FIRST binds for one account
	// both read no prior value and neither blocks the other. The PK does serialize
	// their WRITES — the second INSERT waits on the first's uncommitted tuple and
	// resolves as ON CONFLICT DO UPDATE — but by then both have already read, so both
	// report "displaced nothing" while the second has in fact destroyed the first's
	// live binding. That session is then reported to NOBODY and its held deliveries
	// are stranded. Measured, not assumed: the PK is a write-ordering guarantee and
	// the displaced value is a READ, so the PK cannot cover it. This lock is taken
	// before the read, so it does.
	LockSessionBindingAccount(ctx context.Context, arg LockSessionBindingAccountParams) error
	// Token-usage queries (Plane A). The tenant tx sets the GUC that RLS reads and
	// that tenant_id defaults to, so no statement here names a tenant.
	// LockTokenUsage serializes one tenant's appends and rebuilds. A rebuild beside
	// an append would count the append's events twice or lose them.
	LockTokenUsage(ctx context.Context) error
	MarkMentionsRouted(ctx context.Context, arg MarkMentionsRoutedParams) error
	MergeTopicLastSeq(ctx context.Context, arg MergeTopicLastSeqParams) error
	MessageByID(ctx context.Context, id string) (MessageByIDRow, error)
	MessageChannel(ctx context.Context, id string) (string, error)
	MessageInChannel(ctx context.Context, arg MessageInChannelParams) (int32, error)
	MessagesHeadSeq(ctx context.Context) (int64, error)
	MoveMessagesToTopic(ctx context.Context, arg MoveMessagesToTopicParams) error
	// The accounts still owed a mention: a wake that failed before any Runner could
	// serve it is retried for these once one attaches.
	OwedMentionAccounts(ctx context.Context) ([]string, error)
	OwedMentions(ctx context.Context, agentAccountID string) ([]OwedMentionsRow, error)
	OwnerHasPresentAgent(ctx context.Context, arg OwnerHasPresentAgentParams) (bool, error)
	PinnedEntries(ctx context.Context, channelID string) ([]PinnedEntriesRow, error)
	PlacementForAgent(ctx context.Context, agentAccountID string) (PlacementForAgentRow, error)
	PruneTranscriptEntries(ctx context.Context, arg PruneTranscriptEntriesParams) error
	// Agent config-bundle queries (sqlc adoption T5, RIG-3034). These replace the
	// inline SQL literals in internal/store/agent_config.go; the hand-written Store
	// methods keep their signatures and own the bundle validation/hash and the
	// tar-walk member inventory (Go-side, over the returned BYTEA). The config
	// bundle is a fleet-wide singleton row (singleton = TRUE).
	PutAgentConfig(ctx context.Context, arg PutAgentConfigParams) error
	ReassertDMMandatory(ctx context.Context, id string) error
	// The bridge posts as a non-owner, so owner-only or owned drift would refuse every cold delegation.
	ReassertLinearRoutingShape(ctx context.Context, arg ReassertLinearRoutingShapeParams) error
	// Agent-placement queries (sqlc adoption T5, RIG-3034). These replace the inline
	// SQL literals in internal/store/agent_placements.go; the hand-written Store
	// methods keep their signatures and map the placement rows into the
	// AgentPlacement domain struct (AccountID newtype done inline in the Go).
	RecordAgentPlacement(ctx context.Context, arg RecordAgentPlacementParams) error
	// Forge-authored-artifact queries (sqlc adoption T6, RIG-3034). These replace the
	// inline SQL literals in internal/store/forge_authored.go; the hand-written Store
	// methods keep their signatures, the door-side validation (valid/validCoordinate),
	// the ErrConflict/ErrInvalidArgument/ErrNotFound mapping via pgErrIs, and the
	// textOrNull client_request_id NULL discipline. The read queries feed
	// authoredArtifactFromRow, which maps the generated row (provider/kind ints,
	// number BIGINT, nullable client_request_id) back to the domain AuthoredArtifact.
	// WRITE-ONCE authorship: the DO UPDATE deliberately omits agent_account_id and
	// owner_user_id, so a re-land never rewrites who authored the artifact.
	RecordAuthoredArtifact(ctx context.Context, arg RecordAuthoredArtifactParams) error
	// Runs under the BYPASSRLS system role (delivery consumer, no tenant GUC), so
	// tenant_id is stamped explicitly from the owning account's FK rather than the
	// column DEFAULT (which would NULL-violate with no GUC). The INSERT..SELECT
	// yields zero rows only if $1 has no accounts row — impossible on the no-loss
	// path: the caller always passes an agent resolved from live channel membership
	// (delivery/dispatch.go), whose accounts row exists. A stray user/unknown id
	// would instead FK-violate the owed_mentions -> agent_accounts FK. The
	// ON CONFLICT DO NOTHING is the intended idempotent re-record (a zero-row result
	// there is the NORMAL replay case, not a drop), so asserting rows-affected here
	// would wrongly fail an idempotent re-fire.
	RecordOwedMention(ctx context.Context, arg RecordOwedMentionParams) error
	// What it DISPLACED comes from SessionBindingForUpdate above, not from a
	// RETURNING here. The binding update and event writes share the Store tx.
	RecordSessionBinding(ctx context.Context, arg RecordSessionBindingParams) error
	// Forge state-transition memo queries (compass-forge-state-transition §Actor
	// attribution). The write chokepoint upserts one memo per forge coordinate
	// AFTER a successful agent-driven transition; the notify lane consumes it on
	// match to attribute the echoed STATE event to the acting agent. The
	// hand-written Store methods keep the door-side validation (validCoordinate),
	// the state-domain guard, and the ErrInvalidArgument mapping.
	// Latest transition wins: a re-transition of the same coordinate re-lands on the
	// PK and RESETS consumed_at to NULL, so the newest transition is attributable
	// even when the previous one was already consumed.
	RecordStateTransition(ctx context.Context, arg RecordStateTransitionParams) error
	RemarkSafetyValveSuperseded(ctx context.Context, arg RemarkSafetyValveSupersededParams) error
	RenameTopic(ctx context.Context, arg RenameTopicParams) error
	RequireAgentSessionSubscriber(ctx context.Context, arg RequireAgentSessionSubscriberParams) (bool, error)
	ResolveAckMessage(ctx context.Context, arg ResolveAckMessageParams) (int64, error)
	ResolveCoordinationManager(ctx context.Context, id string) (ResolveCoordinationManagerRow, error)
	ResolveGlobalHandles(ctx context.Context, dollar_1 []string) ([]ResolveGlobalHandlesRow, error)
	ResolveOwner(ctx context.Context, accountID string) (string, error)
	ResolveTokenHash(ctx context.Context, hash []byte) (ResolveTokenHashRow, error)
	ResolveTopicForUpdate(ctx context.Context, arg ResolveTopicForUpdateParams) (string, error)
	ResolveTopicRenameTarget(ctx context.Context, arg ResolveTopicRenameTargetParams) (string, error)
	ResolveVisibleAgentHandles(ctx context.Context, arg ResolveVisibleAgentHandlesParams) ([]ResolveVisibleAgentHandlesRow, error)
	ResolveVisibleGlobalHandles(ctx context.Context, arg ResolveVisibleGlobalHandlesParams) ([]ResolveVisibleGlobalHandlesRow, error)
	ReviveTopic(ctx context.Context, id string) error
	RevokeForgeScope(ctx context.Context, arg RevokeForgeScopeParams) error
	RevokeToken(ctx context.Context, hash []byte) (int64, error)
	// RollUpTokenUsageFrom rebuilds both rollups from the events at or after the
	// horizon.
	RollUpTokenUsageFrom(ctx context.Context, horizon pgtype.Timestamptz) error
	SafetyValveSegments(ctx context.Context, arg SafetyValveSegmentsParams) ([]SafetyValveSegmentsRow, error)
	// Scaffold-only query proving sqlc generation works end to end (T1).
	//
	// This is NOT a real store query: the per-domain query files land in T2..T6 as
	// each store file migrates. It exists so `sqlc generate` produces a non-empty
	// db/ package on current main and the drift gate has something to diff. It
	// selects a genuinely existing column from a genuinely existing table
	// (tenants, 0001_init.sql), so sqlc compiles it against the real schema.
	ScaffoldGetTenant(ctx context.Context, id string) (Tenant, error)
	SearchIssues(ctx context.Context, arg SearchIssuesParams) ([]SearchIssuesRow, error)
	SearchMessages(ctx context.Context, arg SearchMessagesParams) ([]SearchMessagesRow, error)
	// SecretRecordsForAgent collapses the A9 precedence in SQL: DISTINCT ON keeps the
	// first row per name under scope_kind DESC (agent 2 > user 1 > tenant 0), the
	// user tier reached through agent_accounts.owner_user_id. $1 is the calling
	// agent's account id. Ciphertext only — the store never decrypts.
	SecretRecordsForAgent(ctx context.Context, accountID string) ([]Secret, error)
	SeedChannelDeliveryCursors(ctx context.Context, channelID string) error
	// Delivery-cursor queries (sqlc adoption T4, RIG-3034). These replace the inline
	// SQL literals in internal/store/delivery_cursors.go; the hand-written Store
	// methods keep their signatures, the AckDelivery tx orchestration (the owed-clear
	// FIRST, the commit-if-cleared arm, the contiguous-advance loop in Go), and the
	// D2 seed self-guard/idempotency contract. The two message-fanout reads
	// (OwedMentions, UndeliveredMessages) share the per-channel projection the Go
	// drains with an inline loop calling messageFromParts.
	SeedDeliveryCursor(ctx context.Context, arg SeedDeliveryCursorParams) error
	SeedHomeChannelMembers(ctx context.Context, arg SeedHomeChannelMembersParams) error
	SelfAuthoredSeqsAbove(ctx context.Context, arg SelfAuthoredSeqsAboveParams) ([]int64, error)
	SessionBase(ctx context.Context, sessionID string) (int64, error)
	SessionBinding(ctx context.Context, sessionID string) (SessionBindingRow, error)
	SessionBindingForAccount(ctx context.Context, agentAccountID string) (SessionBindingForAccountRow, error)
	// The prior-value read follows the account advisory lock. It shares a tx with
	// event writes and the binding upsert. FOR UPDATE also protects against a writer
	// that reaches the row without taking the advisory lock.
	//
	// The single-statement form this replaces (a `prev` CTE beside the upsert) could
	// not do that: under READ COMMITTED the CTE reads the statement-start snapshot
	// while ON CONFLICT DO UPDATE blocks on the row lock and then re-reads the LATEST
	// committed row, so the two halves saw different versions and the reported
	// displacement was wrong — two concurrent re-points away from sess-A both
	// reported sess-A, so the genuinely displaced sess-B was never reaped.
	//
	// A MISS is not an error: a first-ever bind returns pgx.ErrNoRows and the Store
	// maps that to the empty displaced id.
	// The prior binding, including the original Runner and interval identity. The
	// Store closes a displaced interval before it writes a replacement binding.
	SessionBindingForUpdate(ctx context.Context, agentAccountID string) (SessionBindingForUpdateRow, error)
	// The one query here meant for the system role: a Runner-originated call carries
	// no tenant, so the hub reads the session's tenant cross-tenant, then acts under it.
	// :many so a session id minted in two tenants is refused, not resolved arbitrarily.
	SessionBindingTenants(ctx context.Context, arg SessionBindingTenantsParams) ([]string, error)
	SessionMaxEntrySeq(ctx context.Context, sessionID string) (int64, error)
	SessionTranscript(ctx context.Context, sessionID string) ([]SessionTranscriptRow, error)
	// Agent-activity queries (sqlc adoption T5, RIG-3034). These replace the inline
	// SQL literals in internal/store/agent_activity.go; the hand-written Store
	// methods keep their signatures and map the ActivityFor rows into the
	// AgentActivity domain struct (agentActivityFromRow-equivalent, done inline in
	// the Go — absent-from-table means absent-from-map).
	SetActivity(ctx context.Context, arg SetActivityParams) error
	SetForgeRepoSubscriptionEnabled(ctx context.Context, arg SetForgeRepoSubscriptionEnabledParams) (int64, error)
	SetIssueState(ctx context.Context, arg SetIssueStateParams) (int64, error)
	SetTopicArchived(ctx context.Context, arg SetTopicArchivedParams) error
	SetTourState(ctx context.Context, arg SetTourStateParams) error
	SharesVisibleChannel(ctx context.Context, arg SharesVisibleChannelParams) (bool, error)
	// Event writes share RecordSessionBinding's transaction, so neither half of an
	// interval can commit without its binding transition.
	// clock_timestamp records after lock waits, unlike now() which uses tx start time.
	StartComputeUsageInterval(ctx context.Context, arg StartComputeUsageIntervalParams) error
	StoreForgeRepoWatermark(ctx context.Context, arg StoreForgeRepoWatermarkParams) (int64, error)
	SubscribeConvertedDMParties(ctx context.Context, channelID string) error
	// Delivery-consumer read queries (sqlc adoption T4, RIG-3034). These replace the
	// inline SQL literals in internal/store/delivery_reads.go; the hand-written Store
	// methods keep their signatures, the D1 sweep-set disjunct (kept textually in
	// sync with delivery_cursors.sql UndeliveredMessages/InSweepSet), and the D9
	// error mapping. MessageByID shares the message projection the Go drains via
	// messageFromParts.
	SubscribedAgents(ctx context.Context, arg SubscribedAgentsParams) ([]string, error)
	// Exact-artifact subscribers, plus (on an opened event) the container-scope
	// subscribers for the same container/project.
	SubscribersForArtifact(ctx context.Context, arg SubscribersForArtifactParams) ([]SubscribersForArtifactRow, error)
	SweepChannels(ctx context.Context, accountID string) ([]string, error)
	TenantIDBySlug(ctx context.Context, slug string) (string, error)
	TokenHashExists(ctx context.Context, hash []byte) (bool, error)
	// TokenUsagePruneHorizon reads the prune horizon and holds it until the tx
	// ends, so a prune cannot delete the events a rebuild is about to count.
	TokenUsagePruneHorizon(ctx context.Context) (pgtype.Timestamptz, error)
	// TokenUsageSeries sums one granularity's rollup rows per bucket. granularity
	// is the usage.Granularity value: 1 is hourly, 2 is daily. An empty agent list
	// or provider means no filter.
	TokenUsageSeries(ctx context.Context, arg TokenUsageSeriesParams) ([]TokenUsageSeriesRow, error)
	// Authorization-probe queries (sqlc adoption T6, RIG-3034). These replace the
	// inline SQL literals in internal/store/authz.go; the hand-written helpers keep
	// their signatures and the not-found/forbidden merge, wrapping these EXISTS
	// probes (each returns a bare bool). requireChannelMember / isChannelMember reuse
	// ChannelMemberExists (channels.sql) — the statement is textually identical — so
	// only the three probes without an existing query live here.
	// Feeds IsTopicChannelMember: membership on the channel that owns the topic.
	TopicChannelMemberExists(ctx context.Context, arg TopicChannelMemberExistsParams) (bool, error)
	TopicChannelNames(ctx context.Context, id string) (TopicChannelNamesRow, error)
	UndeliveredMessages(ctx context.Context, accountID string) ([]UndeliveredMessagesRow, error)
	UnroutedMentionMessages(ctx context.Context, arg UnroutedMentionMessagesParams) ([]UnroutedMentionMessagesRow, error)
	UpdateAgentParent(ctx context.Context, arg UpdateAgentParentParams) error
	UpdateChannelPolicy(ctx context.Context, arg UpdateChannelPolicyParams) error
	UpdateMessageBlocks(ctx context.Context, arg UpdateMessageBlocksParams) (int64, error)
	UpdateMessageBlocksAsAuthor(ctx context.Context, arg UpdateMessageBlocksAsAuthorParams) (UpdateMessageBlocksAsAuthorRow, error)
	// UpdateModelRegistry is the compare-and-set write over an existing row: it
	// lands only when the row still holds $2 (the version the caller read), bumping
	// to version + 1 and returning the new version. A stale/racing expected version
	// matches no row (ErrNoRows via RETURNING) — the caller maps that to
	// ErrVersionConflict.
	UpdateModelRegistry(ctx context.Context, arg UpdateModelRegistryParams) (int64, error)
	UpdateTopicLastSeq(ctx context.Context, arg UpdateTopicLastSeqParams) error
	UpsertChannelMember(ctx context.Context, arg UpsertChannelMemberParams) error
	UpsertForgeArtifactCursor(ctx context.Context, arg UpsertForgeArtifactCursorParams) error
	// Issue-domain queries (sqlc adoption T6, RIG-3034). These replace the inline
	// SQL literals in internal/store/issues.go; the hand-written Store methods keep
	// their signatures, the door-side validation, the ErrNotFound/ErrInvalidArgument
	// mapping, and the RowsAffected branch (SetIssueState is :execrows). GetIssue /
	// ListIssues feed issueFromColumns (via issueFromGetRow / issueFromListRow),
	// which maps the generated row (forge_provider/state ints, number BIGINT) back
	// to the domain Issue.
	// Insert-or-update at the forge coordinate with the OQ-6(a) recency guard; the
	// ON CONFLICT sets ONLY forge columns (never state/machinery), and the CTE's
	// fallback SELECT keeps the returned id stable when the guard skips the UPDATE.
	UpsertIssueForgeFields(ctx context.Context, arg UpsertIssueForgeFieldsParams) (string, error)
	// Linear-agent-session queries (sqlc adoption T6, RIG-3034). These replace the
	// inline SQL literals in internal/store/linear_sessions.go; the hand-written
	// Store methods keep their signatures, the RowsAffected branch (Upsert returns
	// created via :execrows), the textOrNull nullable issue fields, and the
	// ErrNotFound/ErrInvalidArgument mapping. The LinearAgentSession read maps the
	// generated nullable fields back to LinearAgentSessionRow inline.
	UpsertLinearAgentSession(ctx context.Context, arg UpsertLinearAgentSessionParams) (int64, error)
	// UpsertSecret writes declaration+value in one row and, on a re-write of an
	// existing (name, scope_kind, scope_id), rewrites value/nonce/key_version and the
	// routing metadata. updated_at is maintained by the set_updated_at trigger, which
	// fires on the ON CONFLICT DO UPDATE path — never set here.
	UpsertSecret(ctx context.Context, arg UpsertSecretParams) error
}

var _ Querier = (*Queries)(nil)
