// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scaffold.sql

package db

import (
	"context"
)

const scaffoldGetTenant = `-- name: ScaffoldGetTenant :one

SELECT id, slug, display_name, created_at_unix_ms
FROM tenants
WHERE id = $1
`

// Scaffold-only query proving sqlc generation works end to end (T1).
//
// This is NOT a real store query: the per-domain query files land in T2..T6 as
// each store file migrates. It exists so `sqlc generate` produces a non-empty
// db/ package on current main and the drift gate has something to diff. It
// selects a genuinely existing column from a genuinely existing table
// (tenants, 0001_init.sql), so sqlc compiles it against the real schema.
func (q *Queries) ScaffoldGetTenant(ctx context.Context, id string) (Tenant, error) {
	row := q.db.QueryRow(ctx, scaffoldGetTenant, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.CreatedAtUnixMs,
	)
	return i, err
}
