// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: secrets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const declaredSecrets = `-- name: DeclaredSecrets :many
SELECT name, delivery, kind, provider, host, declared_by, created_at, updated_at
FROM secrets ORDER BY name
`

type DeclaredSecretsRow struct {
	Name       string
	Delivery   int16
	Kind       int16
	Provider   string
	Host       string
	DeclaredBy string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

// DeclaredSecrets is the names-only view the SERVER SpecResolver's declarations
// interface still consumes (value-free, all scopes).
func (q *Queries) DeclaredSecrets(ctx context.Context) ([]DeclaredSecretsRow, error) {
	rows, err := q.db.Query(ctx, declaredSecrets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeclaredSecretsRow
	for rows.Next() {
		var i DeclaredSecretsRow
		if err := rows.Scan(
			&i.Name,
			&i.Delivery,
			&i.Kind,
			&i.Provider,
			&i.Host,
			&i.DeclaredBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteSecret = `-- name: DeleteSecret :execrows
DELETE FROM secrets WHERE name = $1 AND scope_kind = $2 AND scope_id = $3
`

type DeleteSecretParams struct {
	Name      string
	ScopeKind int16
	ScopeID   string
}

// DeleteSecret addresses one scope coordinate — a name alone no longer
// identifies a row (composite PK).
func (q *Queries) DeleteSecret(ctx context.Context, arg DeleteSecretParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSecret, arg.Name, arg.ScopeKind, arg.ScopeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const isUserAccount = `-- name: IsUserAccount :one

SELECT EXISTS (SELECT 1 FROM user_accounts WHERE account_id = $1)
`

// Secrets-registry queries (sqlc adoption T6, RIG-3034). These back the
// hand-written Store methods, which keep their signatures, the door-side
// validation (name grammar, kind/routing, A9 scope shape), the
// ErrConflict/ErrInvalidArgument/ErrNotFound mapping, and the RowsAffected
// branch (DeleteSecretDeclaration is :execrows).
//
// DeclaredSecrets is the retained value-free READ path (the SERVER SpecResolver's
// declarations view); the scoped, encrypted path is UpsertSecret +
// SecretRecordsForAgent (A1/A9), now the sole writer.
// IsUserAccount reports whether an id names a human account — the user-scope
// (scope_kind 1) referential check the UpsertSecret door runs in lieu of an FK
// (A9). The agent-scope check reuses IsAgentAccount.
func (q *Queries) IsUserAccount(ctx context.Context, accountID string) (bool, error) {
	row := q.db.QueryRow(ctx, isUserAccount, accountID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const secretRecordsForAgent = `-- name: SecretRecordsForAgent :many
SELECT DISTINCT ON (s.name) s.name, s.scope_kind, s.scope_id, s.delivery, s.kind,
       s.provider, s.host, s.value_ciphertext, s.value_nonce, s.key_version,
       s.declared_by, s.created_at, s.updated_at, s.tenant_id
  FROM secrets s
  JOIN agent_accounts a ON a.account_id = $1
 WHERE (s.scope_kind = 0 AND s.scope_id = '')
    OR (s.scope_kind = 1 AND s.scope_id = a.owner_user_id)
    OR (s.scope_kind = 2 AND s.scope_id = a.account_id)
 ORDER BY s.name, s.scope_kind DESC
`

// SecretRecordsForAgent collapses the A9 precedence in SQL: DISTINCT ON keeps the
// first row per name under scope_kind DESC (agent 2 > user 1 > tenant 0), the
// user tier reached through agent_accounts.owner_user_id. $1 is the calling
// agent's account id. Ciphertext only — the store never decrypts.
func (q *Queries) SecretRecordsForAgent(ctx context.Context, accountID string) ([]Secret, error) {
	rows, err := q.db.Query(ctx, secretRecordsForAgent, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Secret
	for rows.Next() {
		var i Secret
		if err := rows.Scan(
			&i.Name,
			&i.ScopeKind,
			&i.ScopeID,
			&i.Delivery,
			&i.Kind,
			&i.Provider,
			&i.Host,
			&i.ValueCiphertext,
			&i.ValueNonce,
			&i.KeyVersion,
			&i.DeclaredBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSecret = `-- name: UpsertSecret :exec
INSERT INTO secrets (name, scope_kind, scope_id, delivery, kind, provider, host,
                     value_ciphertext, value_nonce, key_version, declared_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (name, scope_kind, scope_id) DO UPDATE SET
    value_ciphertext = EXCLUDED.value_ciphertext,
    value_nonce      = EXCLUDED.value_nonce,
    key_version      = EXCLUDED.key_version,
    delivery         = EXCLUDED.delivery,
    kind             = EXCLUDED.kind,
    provider         = EXCLUDED.provider,
    host             = EXCLUDED.host
`

type UpsertSecretParams struct {
	Name            string
	ScopeKind       int16
	ScopeID         string
	Delivery        int16
	Kind            int16
	Provider        string
	Host            string
	ValueCiphertext []byte
	ValueNonce      []byte
	KeyVersion      int16
	DeclaredBy      string
}

// UpsertSecret writes declaration+value in one row and, on a re-write of an
// existing (name, scope_kind, scope_id), rewrites value/nonce/key_version and the
// routing metadata. updated_at is maintained by the set_updated_at trigger, which
// fires on the ON CONFLICT DO UPDATE path — never set here.
func (q *Queries) UpsertSecret(ctx context.Context, arg UpsertSecretParams) error {
	_, err := q.db.Exec(ctx, upsertSecret,
		arg.Name,
		arg.ScopeKind,
		arg.ScopeID,
		arg.Delivery,
		arg.Kind,
		arg.Provider,
		arg.Host,
		arg.ValueCiphertext,
		arg.ValueNonce,
		arg.KeyVersion,
		arg.DeclaredBy,
	)
	return err
}
