// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: secrets.sql

package db

import (
	"context"
)

const declaredSecrets = `-- name: DeclaredSecrets :many
SELECT name, delivery, kind, provider, host, declared_by, created_at, updated_at
FROM secrets ORDER BY name
`

func (q *Queries) DeclaredSecrets(ctx context.Context) ([]Secret, error) {
	rows, err := q.db.Query(ctx, declaredSecrets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Secret
	for rows.Next() {
		var i Secret
		if err := rows.Scan(
			&i.Name,
			&i.Delivery,
			&i.Kind,
			&i.Provider,
			&i.Host,
			&i.DeclaredBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteSecret = `-- name: DeleteSecret :execrows
DELETE FROM secrets WHERE name = $1
`

func (q *Queries) DeleteSecret(ctx context.Context, name string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSecret, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertSecret = `-- name: InsertSecret :exec

INSERT INTO secrets (name, delivery, kind, provider, host, declared_by)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertSecretParams struct {
	Name       string
	Delivery   int16
	Kind       int16
	Provider   string
	Host       string
	DeclaredBy string
}

// Secrets-registry queries (sqlc adoption T6, RIG-3034). These replace the inline
// SQL literals in internal/store/secrets.go; the hand-written Store methods keep
// their signatures, the door-side validation (name grammar, kind routing), the
// ErrConflict/ErrInvalidArgument/ErrNotFound mapping, and the RowsAffected branch
// (DeleteSecretDeclaration is :execrows). DeclaredSecrets maps the generated row
// back to the domain SecretDeclaration (delivery/kind ints -> named types).
func (q *Queries) InsertSecret(ctx context.Context, arg InsertSecretParams) error {
	_, err := q.db.Exec(ctx, insertSecret,
		arg.Name,
		arg.Delivery,
		arg.Kind,
		arg.Provider,
		arg.Host,
		arg.DeclaredBy,
	)
	return err
}
