// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session_bindings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSessionBinding = `-- name: DeleteSessionBinding :exec
WITH d AS (
    DELETE FROM session_bindings AS b
     WHERE b.session_id = $1
    RETURNING b.tenant_id, b.usage_interval_id, b.agent_account_id,
              b.session_id, b.runner_id
)
INSERT INTO compute_usage_events (
    tenant_id, id, interval_id, kind, occurred_at, agent_account_id,
    owner_user_id, session_id, runner_id
)
SELECT d.tenant_id, gen_random_uuid()::text, d.usage_interval_id, 'end', now(),
       d.agent_account_id, a.owner_user_id, d.session_id, d.runner_id
  FROM d
  JOIN agent_accounts AS a ON a.account_id = d.agent_account_id
ON CONFLICT DO NOTHING
`

func (q *Queries) DeleteSessionBinding(ctx context.Context, sessionID string) error {
	_, err := q.db.Exec(ctx, deleteSessionBinding, sessionID)
	return err
}

const deleteSessionBindingsForRunner = `-- name: DeleteSessionBindingsForRunner :many
WITH d AS (
    DELETE FROM session_bindings AS b
     WHERE b.runner_id = $1
    RETURNING b.tenant_id, b.usage_interval_id, b.agent_account_id,
              b.session_id, b.runner_id
), ins AS (
    INSERT INTO compute_usage_events (
        tenant_id, id, interval_id, kind, occurred_at, agent_account_id,
        owner_user_id, session_id, runner_id
    )
    SELECT d.tenant_id, gen_random_uuid()::text, d.usage_interval_id, 'end', now(),
           d.agent_account_id, a.owner_user_id, d.session_id, d.runner_id
      FROM d
      JOIN agent_accounts AS a ON a.account_id = d.agent_account_id
    ON CONFLICT DO NOTHING
    RETURNING 1
)
SELECT d.session_id, d.agent_account_id FROM d
`

type DeleteSessionBindingsForRunnerRow struct {
	SessionID      string
	AgentAccountID string
}

// The reconnect sweep. Hub.enroll (internal/runnerhub/hub.go:905-957) clears
// every binding when a Runner (re-)enrolls: a reconnecting Runner has no live
// sessions, so a surviving binding would resolve a re-minted session id to a
// stale account. A durable table does not forget on reconnect, so the sweep must
// be explicit.
//
// :many with RETURNING, deliberately NOT :exec. enroll snapshots the bindings
// BEFORE clearing them (hub.go:912-928) because each cleared binding drives a
// presence DISCONNECTED edge (RIG-1569 T8) and each cleared session id must be
// reaped from the delivery held-deliver registry (RIG-1569 T3). A bare DELETE
// would satisfy the invariant while silently dropping both side-effects, leaving
// a long-WORKING agent stuck WORKING in the projection forever. RETURNING is
// what preserves them, so the returned rows are load-bearing, not diagnostic.
// A DELETE ... RETURNING takes no ORDER BY, so the Store method sorts the
// returned slice by session id to keep a sweep pass deterministic and diffable.
func (q *Queries) DeleteSessionBindingsForRunner(ctx context.Context, runnerID string) ([]DeleteSessionBindingsForRunnerRow, error) {
	rows, err := q.db.Query(ctx, deleteSessionBindingsForRunner, runnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeleteSessionBindingsForRunnerRow
	for rows.Next() {
		var i DeleteSessionBindingsForRunnerRow
		if err := rows.Scan(&i.SessionID, &i.AgentAccountID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const endComputeUsageInterval = `-- name: EndComputeUsageInterval :exec
INSERT INTO compute_usage_events (
    id, interval_id, kind, occurred_at, agent_account_id, owner_user_id,
    session_id, runner_id
)
SELECT gen_random_uuid()::text, $1::text, 'end', now(),
       a.account_id, a.owner_user_id, $2::text, $3::text
  FROM agent_accounts AS a
 WHERE a.account_id = $4::text
ON CONFLICT (tenant_id, interval_id, kind) DO NOTHING
`

type EndComputeUsageIntervalParams struct {
	IntervalID     string
	SessionID      string
	RunnerID       string
	AgentAccountID string
}

// The account owner is read in SQL so callers continue to supply only the
// session binding identity.
func (q *Queries) EndComputeUsageInterval(ctx context.Context, arg EndComputeUsageIntervalParams) error {
	_, err := q.db.Exec(ctx, endComputeUsageInterval,
		arg.IntervalID,
		arg.SessionID,
		arg.RunnerID,
		arg.AgentAccountID,
	)
	return err
}

const lockSessionBindingAccount = `-- name: LockSessionBindingAccount :exec

SELECT pg_advisory_xact_lock(hashtext('binding:' || $1 || ':' || $2))
`

type LockSessionBindingAccountParams struct {
	Column1 pgtype.Text
	Column2 pgtype.Text
}

// Session-binding queries (RIG-3108 / RIG-2861 §T4): the durable
// (session -> agent account, Runner) binding the RunnerHub has so far held only
// in RAM. The hand-written Store methods in internal/store/session_bindings.go
// map these rows into the SessionBinding domain struct (the AccountID newtype is
// done inline in the Go, as agent_placements does).
//
// These request-path queries rely on SET LOCAL ROLE compass_app and the
// compass.tenant_id GUC for RLS and tenant defaults. Delete queries carry the
// deleted binding's tenant_id into their end-event insert explicitly.
//
// It is NOT complete under WithSystemRole (tenant_tx.go), which arms the
// BYPASSRLS compass_system role and NO tenant GUC. Every query here then runs
// cross-tenant and unscoped, and each one changes meaning:
//
//   - SessionBindingForAccount / SessionBindingAccount / SessionBindingForUpdate
//     are :one, but with RLS gone their single predicate can match rows in
//     SEVERAL tenants. pgx's QueryRow takes the first and discards the rest
//     without error, so the caller gets a plausible answer from an arbitrary
//     tenant.
//   - DeleteSessionBindingsForRunner sweeps EVERY tenant's bindings for that
//     runner id — runner ids are not tenant-unique either.
//   - RecordSessionBinding does not fail closed. tenant_id DEFAULTs to
//     current_setting('compass.tenant_id', TRUE); on a pooled connection that
//     previously served an ARMED statement, the ended SET LOCAL leaves that
//     custom GUC defined-and-EMPTY rather than undefined, so the DEFAULT
//     resolves to ” and the NOT NULL is satisfied. The row lands stamped with a
//     tenant that does not exist — and tenant_id here has no FK to tenants
//     (accounts.tenant_id does), so nothing catches it. No RLS policy matches
//     ”, so that row is then invisible to every tenant and releasable by
//     nothing on the request path. On a connection that never carried an armed
//     statement the GUC is genuinely undefined, the DEFAULT is NULL, and the
//     insert fails not-null instead — so which of the two a caller gets depends
//     on the pooled connection it draws.
//
// Nothing calls these under the system role today (WithSystemRole is set at
// delivery/consumer.go and runnerhub/hub.go); a PR3 caller that wants to must
// scope them deliberately rather than inherit scoping from here.
// session_bindings_pgtest_test.go pins the observed behaviour so it is recorded
// rather than latent.
//
// updated_at is NEVER assigned here: the set_updated_at() BEFORE UPDATE trigger
// (0001_init.sql, RIG-3495) is the one mechanism, and a hand-written
// `updated_at = now()` is the exact defect that convention removes.
//
// The per-account serialization the bind takes FIRST, before it reads anything.
// Auto-released at transaction end. It mirrors LockOwnerDM / LockOwnerCoordination
// / AcquireOwnerTreeLock, with a DISTINCT key domain ('binding:') so a bind never
// serializes behind a DM open, a coordination reconcile, or a reparent. hashtext
// widens the text key to the int the advisory lock takes; a hash collision across
// two accounts is a benign redundant wait, never a wrong result.
//
// It is keyed on TENANT AND ACCOUNT. Every other lock in this package keys on an
// account id alone, which is globally unique — but two tenants can legitimately
// hold bindings for one account id (the PK is folded, see 0001_init.sql), and
// those two binds are independent operations that must not block each other.
//
// Why an advisory lock and not just the row lock below: FOR UPDATE on a row that
// does NOT exist locks NOTHING, so two concurrent FIRST binds for one account
// both read no prior value and neither blocks the other. The PK does serialize
// their WRITES — the second INSERT waits on the first's uncommitted tuple and
// resolves as ON CONFLICT DO UPDATE — but by then both have already read, so both
// report "displaced nothing" while the second has in fact destroyed the first's
// live binding. That session is then reported to NOBODY and its held deliveries
// are stranded. Measured, not assumed: the PK is a write-ordering guarantee and
// the displaced value is a READ, so the PK cannot cover it. This lock is taken
// before the read, so it does.
func (q *Queries) LockSessionBindingAccount(ctx context.Context, arg LockSessionBindingAccountParams) error {
	_, err := q.db.Exec(ctx, lockSessionBindingAccount, arg.Column1, arg.Column2)
	return err
}

const recordSessionBinding = `-- name: RecordSessionBinding :exec
INSERT INTO session_bindings (agent_account_id, session_id, runner_id, usage_interval_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id, agent_account_id) DO UPDATE
    SET session_id = EXCLUDED.session_id,
        runner_id = EXCLUDED.runner_id,
        usage_interval_id = EXCLUDED.usage_interval_id
`

type RecordSessionBindingParams struct {
	AgentAccountID  string
	SessionID       string
	RunnerID        string
	UsageIntervalID string
}

// What it DISPLACED comes from SessionBindingForUpdate above, not from a
// RETURNING here. The binding update and event writes share the Store tx.
func (q *Queries) RecordSessionBinding(ctx context.Context, arg RecordSessionBindingParams) error {
	_, err := q.db.Exec(ctx, recordSessionBinding,
		arg.AgentAccountID,
		arg.SessionID,
		arg.RunnerID,
		arg.UsageIntervalID,
	)
	return err
}

const sessionBinding = `-- name: SessionBinding :one
SELECT agent_account_id, runner_id FROM session_bindings WHERE session_id = $1
`

type SessionBindingRow struct {
	AgentAccountID string
	RunnerID       string
}

func (q *Queries) SessionBinding(ctx context.Context, sessionID string) (SessionBindingRow, error) {
	row := q.db.QueryRow(ctx, sessionBinding, sessionID)
	var i SessionBindingRow
	err := row.Scan(&i.AgentAccountID, &i.RunnerID)
	return i, err
}

const sessionBindingForAccount = `-- name: SessionBindingForAccount :one
SELECT session_id FROM session_bindings WHERE agent_account_id = $1
`

func (q *Queries) SessionBindingForAccount(ctx context.Context, agentAccountID string) (string, error) {
	row := q.db.QueryRow(ctx, sessionBindingForAccount, agentAccountID)
	var session_id string
	err := row.Scan(&session_id)
	return session_id, err
}

const sessionBindingForUpdate = `-- name: SessionBindingForUpdate :one
SELECT b.session_id, b.usage_interval_id, b.runner_id
  FROM session_bindings AS b
 WHERE b.agent_account_id = $1
   FOR UPDATE
`

type SessionBindingForUpdateRow struct {
	SessionID       string
	UsageIntervalID string
	RunnerID        string
}

// The prior-value read follows the account advisory lock. It shares a tx with
// event writes and the binding upsert. FOR UPDATE also protects against a writer
// that reaches the row without taking the advisory lock.
//
// The single-statement form this replaces (a `prev` CTE beside the upsert) could
// not do that: under READ COMMITTED the CTE reads the statement-start snapshot
// while ON CONFLICT DO UPDATE blocks on the row lock and then re-reads the LATEST
// committed row, so the two halves saw different versions and the reported
// displacement was wrong — two concurrent re-points away from sess-A both
// reported sess-A, so the genuinely displaced sess-B was never reaped.
//
// A MISS is not an error: a first-ever bind returns pgx.ErrNoRows and the Store
// maps that to the empty displaced id.
// The prior binding, including the original Runner and interval identity. The
// Store closes a displaced interval before it writes a replacement binding.
func (q *Queries) SessionBindingForUpdate(ctx context.Context, agentAccountID string) (SessionBindingForUpdateRow, error) {
	row := q.db.QueryRow(ctx, sessionBindingForUpdate, agentAccountID)
	var i SessionBindingForUpdateRow
	err := row.Scan(&i.SessionID, &i.UsageIntervalID, &i.RunnerID)
	return i, err
}

const sessionBindingTenants = `-- name: SessionBindingTenants :many
SELECT tenant_id FROM session_bindings WHERE session_id = $1 AND runner_id = $2
`

type SessionBindingTenantsParams struct {
	SessionID string
	RunnerID  string
}

// The one query here meant for the system role: a Runner-originated call carries
// no tenant, so the hub reads the session's tenant cross-tenant, then acts under it.
// :many so a session id minted in two tenants is refused, not resolved arbitrarily.
func (q *Queries) SessionBindingTenants(ctx context.Context, arg SessionBindingTenantsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, sessionBindingTenants, arg.SessionID, arg.RunnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var tenant_id string
		if err := rows.Scan(&tenant_id); err != nil {
			return nil, err
		}
		items = append(items, tenant_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startComputeUsageInterval = `-- name: StartComputeUsageInterval :exec
INSERT INTO compute_usage_events (
    id, interval_id, kind, occurred_at, agent_account_id, owner_user_id,
    session_id, runner_id
)
SELECT gen_random_uuid()::text, $1::text, 'start', now(),
       a.account_id, a.owner_user_id, $2::text, $3::text
  FROM agent_accounts AS a
 WHERE a.account_id = $4::text
ON CONFLICT (tenant_id, interval_id, kind) DO NOTHING
`

type StartComputeUsageIntervalParams struct {
	IntervalID     string
	SessionID      string
	RunnerID       string
	AgentAccountID string
}

// Event writes share RecordSessionBinding's transaction, so neither half of an
// interval can commit without its binding transition.
func (q *Queries) StartComputeUsageInterval(ctx context.Context, arg StartComputeUsageIntervalParams) error {
	_, err := q.db.Exec(ctx, startComputeUsageInterval,
		arg.IntervalID,
		arg.SessionID,
		arg.RunnerID,
		arg.AgentAccountID,
	)
	return err
}
