// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant.sql

package db

import (
	"context"
)

const insertTenant = `-- name: InsertTenant :exec

INSERT INTO tenants (id, slug, display_name, created_at_unix_ms) VALUES ($1, $2, $3, $4)
`

type InsertTenantParams struct {
	ID              string
	Slug            string
	DisplayName     string
	CreatedAtUnixMs int64
}

// Tenant-bootstrap queries (sqlc adoption T6, RIG-3034). These replace the inline
// SQL literals in internal/store/tenant.go; the hand-written Store methods keep
// their signatures and the unique-violation-means-fetch idempotent bootstrap
// shape (BootstrapTenant falls back to TenantIDBySlug on a duplicate slug).
func (q *Queries) InsertTenant(ctx context.Context, arg InsertTenantParams) error {
	_, err := q.db.Exec(ctx, insertTenant,
		arg.ID,
		arg.Slug,
		arg.DisplayName,
		arg.CreatedAtUnixMs,
	)
	return err
}

const listTenantIDs = `-- name: ListTenantIDs :many
SELECT id FROM tenants ORDER BY id
`

// ListTenantIDs lists every tenant. tenants has no row-level security, so the
// app role sees them all without the BYPASSRLS system role.
func (q *Queries) ListTenantIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listTenantIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tenantIDBySlug = `-- name: TenantIDBySlug :one
SELECT id FROM tenants WHERE slug = $1
`

func (q *Queries) TenantIDBySlug(ctx context.Context, slug string) (string, error) {
	row := q.db.QueryRow(ctx, tenantIDBySlug, slug)
	var id string
	err := row.Scan(&id)
	return id, err
}
