// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant.sql

package db

import (
	"context"
)

const insertTenant = `-- name: InsertTenant :exec

INSERT INTO tenants (id, slug, display_name, created_at_unix_ms) VALUES ($1, $2, $3, $4)
`

type InsertTenantParams struct {
	ID              string
	Slug            string
	DisplayName     string
	CreatedAtUnixMs int64
}

// Tenant-bootstrap queries (sqlc adoption T6, RIG-3034). These replace the inline
// SQL literals in internal/store/tenant.go; the hand-written Store methods keep
// their signatures and the unique-violation-means-fetch idempotent bootstrap
// shape (BootstrapTenant falls back to TenantIDBySlug on a duplicate slug).
func (q *Queries) InsertTenant(ctx context.Context, arg InsertTenantParams) error {
	_, err := q.db.Exec(ctx, insertTenant,
		arg.ID,
		arg.Slug,
		arg.DisplayName,
		arg.CreatedAtUnixMs,
	)
	return err
}

const tenantIDBySlug = `-- name: TenantIDBySlug :one
SELECT id FROM tenants WHERE slug = $1
`

func (q *Queries) TenantIDBySlug(ctx context.Context, slug string) (string, error) {
	row := q.db.QueryRow(ctx, tenantIDBySlug, slug)
	var id string
	err := row.Scan(&id)
	return id, err
}
