// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tokens.sql

package db

import (
	"context"
)

const insertTokenHash = `-- name: InsertTokenHash :exec

INSERT INTO tokens (hash, subject_kind, subject_id) VALUES ($1, $2, $3)
`

type InsertTokenHashParams struct {
	Hash        []byte
	SubjectKind int16
	SubjectID   string
}

// Token-domain queries (sqlc adoption T6, RIG-3034). These replace the inline
// SQL literals in internal/store/tokens.go; the hand-written Store methods keep
// their signatures, the ErrConflict/ErrNotFound/ErrTokenRevoked mapping, and the
// RowsAffected branching (RevokeToken is :execrows). ResolveTokenHash maps the
// generated row (subject_kind/subject_id/revoked) back to the domain Subject.
func (q *Queries) InsertTokenHash(ctx context.Context, arg InsertTokenHashParams) error {
	_, err := q.db.Exec(ctx, insertTokenHash, arg.Hash, arg.SubjectKind, arg.SubjectID)
	return err
}

const resolveTokenHash = `-- name: ResolveTokenHash :one
SELECT subject_kind, subject_id, (revoked_at IS NOT NULL)::boolean AS revoked FROM tokens WHERE hash = $1
`

type ResolveTokenHashRow struct {
	SubjectKind int16
	SubjectID   string
	Revoked     bool
}

func (q *Queries) ResolveTokenHash(ctx context.Context, hash []byte) (ResolveTokenHashRow, error) {
	row := q.db.QueryRow(ctx, resolveTokenHash, hash)
	var i ResolveTokenHashRow
	err := row.Scan(&i.SubjectKind, &i.SubjectID, &i.Revoked)
	return i, err
}

const revokeToken = `-- name: RevokeToken :execrows
UPDATE tokens SET revoked_at = now() WHERE hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeToken(ctx context.Context, hash []byte) (int64, error) {
	result, err := q.db.Exec(ctx, revokeToken, hash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const tokenHashExists = `-- name: TokenHashExists :one
SELECT EXISTS (SELECT 1 FROM tokens WHERE hash = $1)
`

func (q *Queries) TokenHashExists(ctx context.Context, hash []byte) (bool, error) {
	row := q.db.QueryRow(ctx, tokenHashExists, hash)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
