// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: topics.sql

package db

import (
	"context"
)

const deleteTopic = `-- name: DeleteTopic :exec
DELETE FROM topics WHERE id = $1
`

func (q *Queries) DeleteTopic(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteTopic, id)
	return err
}

const getTopic = `-- name: GetTopic :one
SELECT id, channel_id, name, created_by_account_id, created_at_unix_ms, archived, last_seq
FROM topics WHERE id = $1
`

func (q *Queries) GetTopic(ctx context.Context, id string) (Topic, error) {
	row := q.db.QueryRow(ctx, getTopic, id)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Name,
		&i.CreatedByAccountID,
		&i.CreatedAtUnixMs,
		&i.Archived,
		&i.LastSeq,
	)
	return i, err
}

const listTopics = `-- name: ListTopics :many

SELECT id, channel_id, name, created_by_account_id, created_at_unix_ms, archived, last_seq
FROM topics
WHERE channel_id = $1 AND ($2 OR NOT archived)
ORDER BY last_seq DESC, created_at_unix_ms DESC, id
`

type ListTopicsParams struct {
	ChannelID string
	Column2   interface{}
}

// Topic-domain queries (sqlc adoption T4, RIG-3034). These replace the inline
// SQL literals in internal/store/topics.go; the hand-written Store methods keep
// their signatures, the UpdateTopic tx orchestration, the rename/merge resolution
// loop, and the D9 not-found/forbidden error mapping. The topic projection
// (id, channel_id, name, created_by_account_id, created_at_unix_ms, archived,
// last_seq) matches the former scanTopics order so the Go maps each row to Topic.
func (q *Queries) ListTopics(ctx context.Context, arg ListTopicsParams) ([]Topic, error) {
	rows, err := q.db.Query(ctx, listTopics, arg.ChannelID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Topic
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.Name,
			&i.CreatedByAccountID,
			&i.CreatedAtUnixMs,
			&i.Archived,
			&i.LastSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mergeTopicLastSeq = `-- name: MergeTopicLastSeq :exec
UPDATE topics dst SET last_seq = GREATEST(dst.last_seq, src.last_seq)
FROM topics src WHERE dst.id = $1 AND src.id = $2
`

type MergeTopicLastSeqParams struct {
	ID   string
	ID_2 string
}

func (q *Queries) MergeTopicLastSeq(ctx context.Context, arg MergeTopicLastSeqParams) error {
	_, err := q.db.Exec(ctx, mergeTopicLastSeq, arg.ID, arg.ID_2)
	return err
}

const moveMessagesToTopic = `-- name: MoveMessagesToTopic :exec
UPDATE messages SET topic_id = $1 WHERE topic_id = $2
`

type MoveMessagesToTopicParams struct {
	TopicID   string
	TopicID_2 string
}

func (q *Queries) MoveMessagesToTopic(ctx context.Context, arg MoveMessagesToTopicParams) error {
	_, err := q.db.Exec(ctx, moveMessagesToTopic, arg.TopicID, arg.TopicID_2)
	return err
}

const renameTopic = `-- name: RenameTopic :exec
UPDATE topics SET name = $2 WHERE id = $1
`

type RenameTopicParams struct {
	ID   string
	Name string
}

func (q *Queries) RenameTopic(ctx context.Context, arg RenameTopicParams) error {
	_, err := q.db.Exec(ctx, renameTopic, arg.ID, arg.Name)
	return err
}

const resolveTopicForUpdate = `-- name: ResolveTopicForUpdate :one
SELECT t.channel_id FROM topics t
JOIN channel_members cm ON cm.channel_id = t.channel_id AND cm.account_id = $1
WHERE t.id = $2
FOR UPDATE OF t
`

type ResolveTopicForUpdateParams struct {
	AccountID string
	ID        string
}

func (q *Queries) ResolveTopicForUpdate(ctx context.Context, arg ResolveTopicForUpdateParams) (string, error) {
	row := q.db.QueryRow(ctx, resolveTopicForUpdate, arg.AccountID, arg.ID)
	var channel_id string
	err := row.Scan(&channel_id)
	return channel_id, err
}

const resolveTopicRenameTarget = `-- name: ResolveTopicRenameTarget :one
SELECT id FROM topics
WHERE channel_id = $1 AND lower(name) = lower($2) AND id <> $3
FOR UPDATE
`

type ResolveTopicRenameTargetParams struct {
	ChannelID string
	Lower     string
	ID        string
}

func (q *Queries) ResolveTopicRenameTarget(ctx context.Context, arg ResolveTopicRenameTargetParams) (string, error) {
	row := q.db.QueryRow(ctx, resolveTopicRenameTarget, arg.ChannelID, arg.Lower, arg.ID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const setTopicArchived = `-- name: SetTopicArchived :exec
UPDATE topics SET archived = $2 WHERE id = $1
`

type SetTopicArchivedParams struct {
	ID       string
	Archived bool
}

func (q *Queries) SetTopicArchived(ctx context.Context, arg SetTopicArchivedParams) error {
	_, err := q.db.Exec(ctx, setTopicArchived, arg.ID, arg.Archived)
	return err
}
