// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_peers.sql

package db

import (
	"context"
)

const deleteUserPeer = `-- name: DeleteUserPeer :execrows
DELETE FROM user_peers
WHERE user_id = $1 AND peer_user_id = $2
`

type DeleteUserPeerParams struct {
	UserID     string
	PeerUserID string
}

func (q *Queries) DeleteUserPeer(ctx context.Context, arg DeleteUserPeerParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserPeer, arg.UserID, arg.PeerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertUserPeer = `-- name: InsertUserPeer :execrows
INSERT INTO user_peers (user_id, peer_user_id)
VALUES ($1, $2)
ON CONFLICT (user_id, peer_user_id) DO NOTHING
`

type InsertUserPeerParams struct {
	UserID     string
	PeerUserID string
}

func (q *Queries) InsertUserPeer(ctx context.Context, arg InsertUserPeerParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertUserPeer, arg.UserID, arg.PeerUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listUserPeerings = `-- name: ListUserPeerings :many
SELECT COALESCE(outgoing.peer_user_id, incoming.user_id) AS peer_id,
       ah.handle,
       (outgoing.peer_user_id IS NOT NULL)::boolean AS outgoing,
       (incoming.user_id IS NOT NULL)::boolean AS incoming
FROM (SELECT p_out.peer_user_id FROM user_peers p_out WHERE p_out.user_id = $1) outgoing
FULL OUTER JOIN (SELECT p_in.user_id FROM user_peers p_in WHERE p_in.peer_user_id = $1) incoming
  ON incoming.user_id = outgoing.peer_user_id
JOIN accounts a
  ON a.id = COALESCE(outgoing.peer_user_id, incoming.user_id)
JOIN account_handles ah ON ah.account_id = a.id
ORDER BY ah.handle
`

type ListUserPeeringsRow struct {
	PeerID   string
	Handle   string
	Outgoing bool
	Incoming bool
}

func (q *Queries) ListUserPeerings(ctx context.Context, userID string) ([]ListUserPeeringsRow, error) {
	rows, err := q.db.Query(ctx, listUserPeerings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserPeeringsRow
	for rows.Next() {
		var i ListUserPeeringsRow
		if err := rows.Scan(
			&i.PeerID,
			&i.Handle,
			&i.Outgoing,
			&i.Incoming,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userPeerPair = `-- name: UserPeerPair :one
SELECT EXISTS (SELECT 1 FROM user_peers p_out WHERE p_out.user_id = $1 AND p_out.peer_user_id = $2) AS outgoing,
       EXISTS (SELECT 1 FROM user_peers p_in WHERE p_in.user_id = $2 AND p_in.peer_user_id = $1) AS incoming
`

type UserPeerPairParams struct {
	UserID     string
	PeerUserID string
}

type UserPeerPairRow struct {
	Outgoing bool
	Incoming bool
}

func (q *Queries) UserPeerPair(ctx context.Context, arg UserPeerPairParams) (UserPeerPairRow, error) {
	row := q.db.QueryRow(ctx, userPeerPair, arg.UserID, arg.PeerUserID)
	var i UserPeerPairRow
	err := row.Scan(&i.Outgoing, &i.Incoming)
	return i, err
}
